# Lecture 07a: Introduction to Pandas — DataFrames, Indexing & Slicing

## What is [pandas?](https://pandas.pydata.org/)

[Pandas wikipedia entry](https://en.wikipedia.org/wiki/Pandas_(software))

**Necessary homework reading:**
1) From the [User Guide](https://pandas.pydata.org/docs/user_guide/index.html), study: [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html). As the title says, it takes no more than 2 hours and 10 minutes!
2) More on [indexing and selecting data](https://pandas.pydata.org/docs/user_guide/indexing.html#)   

Advanced Reading: more complex recipes in the pandas [Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook).

### Lecture outline:
1. Open a `.csv` file and read the data as a pandas DataFrame.
2. Basic DataFrame methods, attributes, and descriptive statistics.
3. Columns and Index — understanding the structure.
4. Select (Locate) data with `.loc` (label-based) and `.iloc` (position-based).
5. Alternative slicing syntax (bracket notation, dot notation).
6. Transpose a DataFrame — `.loc` vs `.iloc` with string labels.

### Datasets used:
- `temp_to_coffee.csv` — a small, simple dataset to get started.
- `predict_heart_disease_train.csv` — a medical dataset with 426 patients and 15 features for the main examples.

In [2]:
!pwd  # Present working directory. This is where your notebook is running on your computer.

/home/tharg/venv_projects/uoa_py_course/lectures_07_13_pandas_plots_scikit/lecture_07_pandas

#### Module not found error if not installed.
**To Install it, open CLI, go to course folder, activate venv, type`pip install pandas` .**

In [3]:
# Import module_name as alias (useful convention)
import pandas as pd

## 1. Open a `.csv` file and read the data as a pandas dataframe.

#### If you get a very red, angry "FileNotFoundError" (file not found Error):  

Guess what is the problem:   
a) You don't have the file in the correct folder.   
b) You don't use the correct file name.   
c) YOu don't run the notebook from the correct folder.

**d) Our teacher is sooo bad, and it is his fault!**

e) All of the above.   

e) Is is the correct answer, if you are a beginner, and that's normal because it is mainly **d)**.

In [ ]:
# First download the file from the eclass directory!

# Uncomment to use the code below if you put the data file in the same folder as the notebook.
df = pd.read_csv("temp_to_coffee.csv")

In [8]:
# Use the code below if you put the data file in a directory that has the same structure as I do.
# If not, comment it out.
# df = pd.read_csv("../../data/temp_to_coffee.csv")

In [9]:
# see the dataframe
df

     X    Y
0   20  396
1   22  297
2   23  397
3   18  425
4   19  425
5   24  260
6   25  250
7   20  299
8   22  520
9   18  498
10  16  434
11  16  285
12  17  496
13  20  360
14  21  417
15  19  409
16  15  493
17  15  509
18  18  406
19  20  410

In [11]:
# first 4 rows
df.head(2)

    X    Y
0  20  396
1  22  297

In [12]:
type(df)

pandas.DataFrame

## 2. Basic DataFrame methods, attributes, and descriptive statistics.
These work on any DataFrame, regardless of the dataset.

In [13]:
# Number of rows (observations).
len(df)

20

In [14]:
# The names of the columns (features) in the data.
df.columns

Index(['X', 'Y'], dtype='str')

In [15]:
# Number of non-null observations per column.
df.count()

X    20
Y    20
dtype: int64

In [16]:
# Total number of data points (rows × columns).
df.size

40

In [17]:
# Shape: (rows, columns) as a tuple.
df.shape

(20, 2)

In [18]:
# Number of rows only.
df.shape[0]

20

In [19]:
# Number of columns only.
df.shape[1]

2

In [20]:
# The row index — a RangeIndex starting from 0.
df.index

RangeIndex(start=0, stop=20, step=1)

In [21]:
type(df.index)

pandas.RangeIndex

In [22]:
# Descriptive statistics for all numeric columns.
df.describe()

               X           Y
count  20.000000   20.000000
mean   19.400000  399.300000
std     2.872739   84.109014
min    15.000000  250.000000
25%    17.750000  344.750000
50%    19.500000  409.500000
75%    21.250000  448.750000
max    25.000000  520.000000

In [23]:
# Custom percentiles — pass a list of percentile values.
df.describe(percentiles=[0.1, 0.2, 0.4, 0.95])

               X           Y
count  20.000000   20.000000
mean   19.400000  399.300000
std     2.872739   84.109014
min    15.000000  250.000000
10%    15.900000  282.500000
20%    16.800000  298.600000
40%    18.600000  402.400000
95%    24.050000  509.550000
max    25.000000  520.000000

### A real-world DataFrame: Heart Disease Prediction
We now load a larger, more realistic dataset: **predict_heart_disease_train.csv**.  
It contains medical data for 630k patients, with features like Age, Blood Pressure, Cholesterol, and a target column `Heart Disease` (Presence/Absence).

We reuse the same variable name `df`. Why? **Convention, Reproducibility, Readability.**  
In practice, you work with one main DataFrame at a time, and `df` is the standard name for it.

In [ ]:
# Explore available read methods by uncommenting and pressing Tab:
# pd.read_

# Comment it out again after exploring.

In [25]:
# Uncomment to see the full docstring for read_csv:
# pd.read_csv?

# Comment it out again.

In [4]:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
# NOTE: We intentionally omit index_col here to demonstrate the duplicated index issue below.
df = pd.read_csv("predict_heart_disease_train.csv")

# Use the code below if you put the data file in the data/ directory.
# df = pd.read_csv("../../data/predict_heart_disease_train.csv")

In [5]:
# Display the full DataFrame. Notice: 630000 rows × 15 columns.
df

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,56,0,1,110,226,0,0,132,0,0.0,1,0,7,Absence
629996,629996,54,1,4,128,249,1,2,150,0,0.0,2,0,3,Absence
629997,629997,67,1,4,130,275,0,0,149,0,0.0,1,2,7,Presence
629998,629998,52,1,4,140,199,0,2,157,0,0.0,1,0,6,Presence
629999,629999,51,0,2,130,199,0,0,168,0,0.0,1,0,3,Absence

#### Spot the problem: the `id` column duplicates the index!

Look at the DataFrame above. The leftmost bold numbers (0, 1, 2, ...) are the **auto-generated RangeIndex**.  
The `id` column also contains 0, 1, 2, ... — **the exact same values**.

**Root cause:** The CSV file has an `id` column that was meant to be the row identifier.  
But `pd.read_csv()` doesn't know that — it always creates its own default integer index.  
So you end up with **two copies** of the same information: one as the index, one as a column.

**Fix:** Use the `index_col` parameter to tell pandas which column IS the index.

In [6]:
# Fix: re-read with index_col="id" so the id column becomes the index.
df = pd.read_csv("predict_heart_disease_train.csv", index_col="id")
df.head(3)  # Now "id" is the index, not a separate column.

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence

In [9]:
# A random sample of 5 rows — useful for a quick peek at the data.
df.sample(5)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
116596,52,1,3,132,226,0,0,165,1,0.0,1,0,3,Absence
5456,58,1,3,108,234,0,0,172,0,0.0,1,0,3,Absence
147113,37,1,4,130,305,0,2,144,1,0.6,1,1,7,Presence
423515,70,1,4,130,303,1,2,165,0,2.5,2,1,7,Presence
279646,53,1,4,140,177,0,0,165,0,2.0,2,0,7,Presence

In [10]:
# Column names — notice some have spaces (e.g. "Chest pain type", "Max HR").
df.columns

Index(['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease'],
      dtype='str')

In [11]:
df.head(3)  # First 3 rows to see the column names and index.

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence

In [12]:
df.tail(3)  # Last 3 rows to see the index and data at the end of the DataFrame.

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
629997,67,1,4,130,275,0,0,149,0,0.0,1,2,7,Presence
629998,52,1,4,140,199,0,2,157,0,0.0,1,0,6,Presence
629999,51,0,2,130,199,0,0,168,0,0.0,1,0,3,Absence

In [13]:
len(df)

630000

In [14]:
# Info on column types, non-null counts, and memory usage.
# This dataset has no missing values — all columns show 426 non-null entries.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Age                      630000 non-null  int64
 1   Sex                      630000 non-null  int64
 2   Chest pain type          630000 non-null  int64
 3   BP                       630000 non-null  int64
 4   Cholesterol              630000 non-null  int64
 5   FBS over 120             630000 non-null  int64
 6   EKG results              630000 non-null  int64
 7   Max HR                   630000 non-null  int64
 8   Exercise angina          630000 non-null  int64
 9   ST depression            630000 non-null  float64
 10  Slope of ST              630000 non-null  int64
 11  Number of vessels fluro  630000 non-null  int64
 12  Thallium                 630000 non-null  int64
 13  Heart Disease            630000 non-null  str
dtypes: float64(1), int64(12), str(1)
memory usage: 67.3 MB

## 3. Columns and Index 
**Columns** = features, dimensions, variables (independent X, dependent y).  
In our heart disease dataset: Age, BP, Cholesterol, etc. are **features (X)**; `Heart Disease` is the **target (y)**.

**Integer Index** = row numbers, representing individual observations/patients (usually).  
By default, pandas creates a `RangeIndex` starting from 0.

In [15]:
# Row index: RangeIndex(start=0, stop=426, step=1)
df.index

RangeIndex(start=0, stop=630000, step=1, name='id')

In [16]:
# Data types per column — mostly int64/float64 for medical measurements, object for "Heart Disease".
df.dtypes

Age                          int64
Sex                          int64
Chest pain type              int64
BP                           int64
Cholesterol                  int64
FBS over 120                 int64
EKG results                  int64
Max HR                       int64
Exercise angina              int64
ST depression              float64
Slope of ST                  int64
Number of vessels fluro      int64
Thallium                     int64
Heart Disease                  str
dtype: object

## 4. Select (Locate) data: `.loc` vs `.iloc`
Recommended [StackOverflow answer](https://stackoverflow.com/a/31593712) on the difference.

| Method | Based on | End is... | Example |
|--------|----------|-----------|---------|
| `.iloc` | **Position** (integer) | Exclusive | `df.iloc[0:2]` → rows 0, 1 |
| `.loc`  | **Label** (name)       | Inclusive  | `df.loc[0:2]` → rows 0, 1, 2 |

**Syntax: (Rows, Columns)** — row index first, column index second.

### 4.1 Slice rows

In [20]:
# .iloc: first row (position 0). Returns a Series.
df.iloc[0:3]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence

In [19]:
# .loc: row with label 0. Same result here because labels happen to be integers.
df.loc[0:3]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence

In [34]:
# Second row (position 1).
df.iloc[1]

Age                             52
Sex                              1
Chest pain type                  1
BP                             125
Cholesterol                    325
FBS over 120                     0
EKG results                      2
Max HR                         171
Exercise angina                  0
ST depression                  0.0
Slope of ST                      1
Number of vessels fluro          0
Thallium                         3
Heart Disease              Absence
Name: 1, dtype: object

In [35]:
# .iloc is EXCLUSIVE (like Python lists): 0:2 gives rows 0 and 1.
df.iloc[0:2]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence

In [36]:
# .loc is INCLUSIVE: 0:2 gives rows 0, 1, AND 2.
df.loc[0:2]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence

### 4.2 Slice columns

In [21]:
# Select a single column by name. Single brackets → returns a Series.
df["Age"]

id
0         58
1         52
2         56
3         44
4         58
          ..
629995    56
629996    54
629997    67
629998    52
629999    51
Name: Age, Length: 630000, dtype: int64

In [22]:
type(df["Age"])  # Single brackets → Series

pandas.Series

In [23]:
# Double brackets → returns a DataFrame (even for a single column).
df[["Age"]]

        Age
id
0        58
1        52
2        56
3        44
4        58
...     ...
629995   56
629996   54
629997   67
629998   52
629999   51

[630000 rows x 1 columns]

In [24]:
type(df[["Age"]])  # Double brackets → DataFrame

pandas.DataFrame

In [25]:
# Select multiple columns by passing a list of column names.
df[["Age", "Cholesterol", "BP"]]

        Age  Cholesterol   BP
id
0        58          239  152
1        52          325  125
2        56          188  160
3        44          229  134
4        58          234  140
...     ...          ...  ...
629995   56          226  110
629996   54          249  128
629997   67          275  130
629998   52          199  140
629999   51          199  130

[630000 rows x 3 columns]

### 4.3 Slice rows and columns

In [26]:
# .loc: rows 0-5, columns from "Age" to "BP" (inclusive on both ends).
# This gives us: Age, Sex, Chest pain type, BP
df.loc[0:5, "Age":"BP"]

    Age  Sex  Chest pain type   BP
id
0    58    1                4  152
1    52    1                1  125
2    56    0                2  160
3    44    0                3  134
4    58    1                4  140
5    38    1                4  138

In [27]:
# All rows, columns from "Age" to "BP".
df.loc[:, "Age":"BP"]

        Age  Sex  Chest pain type   BP
id
0        58    1                4  152
1        52    1                1  125
2        56    0                2  160
3        44    0                3  134
4        58    1                4  140
...     ...  ...              ...  ...
629995   56    0                1  110
629996   54    1                4  128
629997   67    1                4  130
629998   52    1                4  140
629999   51    0                2  130

[630000 rows x 4 columns]

In [28]:
# First 6 rows, columns from "Sex" to "Cholesterol".
df.loc[:5, "Sex":"Cholesterol"]

    Sex  Chest pain type   BP  Cholesterol
id
0     1                4  152          239
1     1                1  125          325
2     0                2  160          188
3     0                3  134          229
4     1                4  140          234
5     1                4  138          283

In [29]:
type(df.loc[:, "Age":"Sex"])

pandas.DataFrame

In [30]:
# .loc is INCLUSIVE — because it works with "names" (labels), not positions.
df.loc[0:3, "Age":"BP"]

# Inclusive: rows 0, 1, 2, 3 AND columns Age, Sex, Chest pain type, BP.

    Age  Sex  Chest pain type   BP
id
0    58    1                4  152
1    52    1                1  125
2    56    0                2  160
3    44    0                3  134

In [31]:
# First 11 rows, ALL columns.
df.loc[0:10, :]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence
5,38,1,4,138,283,0,0,147,1,1.6,2,2,7,Presence
6,59,1,4,130,246,0,2,152,0,0.8,2,2,3,Presence
7,60,0,3,120,245,0,0,151,0,1.2,1,0,3,Absence
8,48,0,4,140,212,0,2,125,0,0.0,1,0,3,Absence
9,44,0,4,150,197,0,0,150,0,0.0,2,0,3,Absence
10,41,1,2,120,212,0,0,173,0,0.6,2,0,3,Absence

In [32]:
# Rows 0-6, and a LIST of specific column names.
df.loc[0:6, ["Age", "Cholesterol"]]

    Age  Cholesterol
id
0    58          239
1    52          325
2    56          188
3    44          229
4    58          234
5    38          283
6    59          246

In [35]:
# A single value: row 8, column "Age".
df.loc[8, "Age"]

np.int64(48)

## 5. Alternative syntax to slice rows and columns.   
You may use similar notation to lists and strings indexing, without `.loc` nor `.iloc`.

**Dot notation caveat:** `df.Age` works (no spaces), but `df.Chest pain type` does **NOT**.  
Columns with spaces **must** use bracket notation: `df["Chest pain type"]`.

In [36]:
# Dot notation: value of "Age" for row 8.
df.Age[8]

np.int64(48)

In [37]:
# Basic indexing as we do it in lists and strings works similarly on df rows.
# EXCLUSIVE because it works with ordered indexing in numbers.

df[10:13]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
10,41,1,2,120,212,0,0,173,0,0.6,2,0,3,Absence
11,52,0,2,140,234,0,0,160,0,0.0,1,0,3,Absence
12,41,0,3,108,230,0,2,142,0,0.6,2,1,3,Absence

In [38]:
# Dot notation + slice — EXCLUSIVE (like list indexing).
df.Age[10:13]

id
10    41
11    52
12    41
Name: Age, dtype: int64

In [39]:
# Same result, bracket notation instead of dot notation.
# EXCLUSIVE — works like list/string indexing.
df["Age"][10:13]

id
10    41
11    52
12    41
Name: Age, dtype: int64

In [40]:
# Rows first, then column — same result, different order of operations.
df[10:13]["Age"]

id
10    41
11    52
12    41
Name: Age, dtype: int64

In [41]:
# Select columns first, then slice rows.
df[["Age", "Sex"]][10:13]

    Age  Sex
id
10   41    1
11   52    0
12   41    0

In [ ]:
# Slice rows first, then select columns — same result, different order.
df[10:13][["Age", "Sex"]]

    Age  Sex
id
10   41    1
11   52    0
12   41    0

In [42]:
# Negative indexing: last 10 to last 5 Cholesterol values.
df.Cholesterol[-10:-5]

id
629990    282
629991    263
629992    229
629993    288
629994    235
Name: Cholesterol, dtype: int64

In [43]:
type(df.Cholesterol[-10:-5])

pandas.Series

In [46]:
df[5:10]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
5,38,1,4,138,283,0,0,147,1,1.6,2,2,7,Presence
6,59,1,4,130,246,0,2,152,0,0.8,2,2,3,Presence
7,60,0,3,120,245,0,0,151,0,1.2,1,0,3,Absence
8,48,0,4,140,212,0,2,125,0,0.0,1,0,3,Absence
9,44,0,4,150,197,0,0,150,0,0.0,2,0,3,Absence

In [ ]:
# Chained slicing: slice rows, then slice rows again.
# First: rows 5-9. Then: first 3 of those → rows 5, 6, 7.
# Tricky! The second slice uses POSITIONAL indexing on the result.

df[5:10][0:3]

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
5,38,1,4,138,283,0,0,147,1,1.6,2,2,7,Presence

In [48]:
# Step 1: Slice rows 5 to 9.
slice_on_df_rows = df[5:10]

In [49]:
slice_on_df_rows

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
5,38,1,4,138,283,0,0,147,1,1.6,2,2,7,Presence
6,59,1,4,130,246,0,2,152,0,0.8,2,2,3,Presence
7,60,0,3,120,245,0,0,151,0,1.2,1,0,3,Absence
8,48,0,4,140,212,0,2,125,0,0.0,1,0,3,Absence
9,44,0,4,150,197,0,0,150,0,0.0,2,0,3,Absence

In [51]:
# Step 2: Take first 3 rows from the previous slice → rows 5, 6, 7.
second_slice = slice_on_df_rows[0:3]
second_slice

# Understanding chained slicing is important — it will save you hours of debugging.

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
5,38,1,4,138,283,0,0,147,1,1.6,2,2,7,Presence
6,59,1,4,130,246,0,2,152,0,0.8,2,2,3,Presence
7,60,0,3,120,245,0,0,151,0,1.2,1,0,3,Absence

### Can you spot the difference between `.loc` and bracket slicing?
Hint: count the rows returned in each cell below.

In [52]:
# .loc is INCLUSIVE — returns rows 0 through 5.
df.loc[:5, "Age"]

id
0    58
1    52
2    56
3    44
4    58
5    38
Name: Age, dtype: int64

In [53]:
# Bracket/slice notation is EXCLUSIVE — returns rows 0 through 4.
df.Age[:5]

id
0    58
1    52
2    56
3    44
4    58
Name: Age, dtype: int64

In [54]:
df[2:5]["Age"]

id
2    56
3    44
4    58
Name: Age, dtype: int64

## 6. Transpose a DataFrame
Sometimes useful for reshaping data.  
Here we use it to practice `.loc` and `.iloc` when row labels are **strings** (column names become row labels after transposing).

In [63]:
# Transpose: rows ↔ columns. Just a view, does NOT modify df.
df.transpose()#.head(4)  # alternative syntax: df.T

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0
Chest pain type,4,1,2,3,4,4,4,3,4,4,...,4,3,1,3,4,1,4,4,4,2
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130
Cholesterol,239,325,188,229,234,283,246,245,212,197,...,282,263,229,288,235,226,249,275,199,199
FBS over 120,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
EKG results,0,2,2,2,2,0,2,0,2,0,...,0,2,2,2,0,0,2,0,2,0
Max HR,158,171,151,150,125,147,152,151,125,150,...,160,160,142,171,162,132,150,149,157,168
Exercise angina,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ST depression,3.6,0.0,0.0,1.0,3.8,1.6,0.8,1.2,0.0,0.0,...,1.6,2.0,1.2,0.0,0.2,0.0,0.0,0.0,0.0,0.0
Slope of ST,2,1,1,2,2,2,2,1,1,2,...,2,2,1,2,1,1,2,1,1,1
Number of vessels fluro,2,0,0,0,3,2,2,0,0,0,...,1,2,0,0,2,0,0,2,0,0
Thallium,7,3,3,3,3,7,3,3,3,3,...,3,7,7,3,3,7,3,7,6,3
Heart Disease,Presence,Absence,Absence,Absence,Presence,Presence,Presence,Absence,Absence,Absence,...,Absence,Presence,Presence,Absence,Presence,Absence,Absence,Presence,Presence,Absence

In [56]:
# df has NOT changed in memory — transpose() returns a view.
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,56,0,1,110,226,0,0,132,0,0.0,1,0,7,Absence
629996,54,1,4,128,249,1,2,150,0,0.0,2,0,3,Absence
629997,67,1,4,130,275,0,0,149,0,0.0,1,2,7,Presence
629998,52,1,4,140,199,0,2,157,0,0.0,1,0,6,Presence
629999,51,0,2,130,199,0,0,168,0,0.0,1,0,3,Absence

In [68]:
# Nothing but a view of the transpose of the df.
df.T

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0
Chest pain type,4,1,2,3,4,4,4,3,4,4,...,4,3,1,3,4,1,4,4,4,2
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130
Cholesterol,239,325,188,229,234,283,246,245,212,197,...,282,263,229,288,235,226,249,275,199,199
FBS over 120,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
EKG results,0,2,2,2,2,0,2,0,2,0,...,0,2,2,2,0,0,2,0,2,0
Max HR,158,171,151,150,125,147,152,151,125,150,...,160,160,142,171,162,132,150,149,157,168
Exercise angina,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ST depression,3.6,0.0,0.0,1.0,3.8,1.6,0.8,1.2,0.0,0.0,...,1.6,2.0,1.2,0.0,0.2,0.0,0.0,0.0,0.0,0.0
Slope of ST,2,1,1,2,2,2,2,1,1,2,...,2,2,1,2,1,1,2,1,1,1
Number of vessels fluro,2,0,0,0,3,2,2,0,0,0,...,1,2,0,0,2,0,0,2,0,0
Thallium,7,3,3,3,3,7,3,3,3,3,...,3,7,7,3,3,7,3,7,6,3
Heart Disease,Presence,Absence,Absence,Absence,Presence,Presence,Presence,Absence,Absence,Absence,...,Absence,Presence,Presence,Absence,Presence,Absence,Absence,Presence,Presence,Absence

In [69]:
# df has not changed in memory.
df

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,56,0,1,110,226,0,0,132,0,0.0,1,0,7,Absence
629996,54,1,4,128,249,1,2,150,0,0.0,2,0,3,Absence
629997,67,1,4,130,275,0,0,149,0,0.0,1,2,7,Presence
629998,52,1,4,140,199,0,2,157,0,0.0,1,0,6,Presence
629999,51,0,2,130,199,0,0,168,0,0.0,1,0,3,Absence

In [57]:
# Assign the transposed view to a new variable (df stays unchanged).
transposed_df = df.T  # .T is shorthand for .transpose()

In [58]:
transposed_df

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0
Chest pain type,4,1,2,3,4,4,4,3,4,4,...,4,3,1,3,4,1,4,4,4,2
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130
Cholesterol,239,325,188,229,234,283,246,245,212,197,...,282,263,229,288,235,226,249,275,199,199
FBS over 120,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
EKG results,0,2,2,2,2,0,2,0,2,0,...,0,2,2,2,0,0,2,0,2,0
Max HR,158,171,151,150,125,147,152,151,125,150,...,160,160,142,171,162,132,150,149,157,168
Exercise angina,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ST depression,3.6,0.0,0.0,1.0,3.8,1.6,0.8,1.2,0.0,0.0,...,1.6,2.0,1.2,0.0,0.2,0.0,0.0,0.0,0.0,0.0
Slope of ST,2,1,1,2,2,2,2,1,1,2,...,2,2,1,2,1,1,2,1,1,1
Number of vessels fluro,2,0,0,0,3,2,2,0,0,0,...,1,2,0,0,2,0,0,2,0,0
Thallium,7,3,3,3,3,7,3,3,3,3,...,3,7,7,3,3,7,3,7,6,3
Heart Disease,Presence,Absence,Absence,Absence,Presence,Presence,Presence,Absence,Absence,Absence,...,Absence,Presence,Presence,Absence,Presence,Absence,Absence,Presence,Presence,Absence

In [59]:
# .iloc still works — it uses positional (integer) indexing.
transposed_df.iloc[0:4]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0
Chest pain type,4,1,2,3,4,4,4,3,4,4,...,4,3,1,3,4,1,4,4,4,2
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130

In [60]:
# .loc uses labels — now the row labels are the original column names (strings!).
transposed_df.loc["Age":"Sex"]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0

In [61]:
# Range of row labels AND range of column labels (columns are now the patient indices).
transposed_df.loc["Age":"BP", 1:6]

id                 1    2    3    4    5    6
Age               52   56   44   58   38   59
Sex                1    0    0    1    1    1
Chest pain type    1    2    3    4    4    4
BP               125  160  134  140  138  130

In [62]:
# Index of transposed_df = the original column names (strings).
transposed_df.index

Index(['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease'],
      dtype='str')

In [76]:
# Columns of transposed_df = the original row indices (integers).
transposed_df.columns

RangeIndex(start=0, stop=630000, step=1, name='id')

In [77]:
# Select a single row by its string label.
transposed_df.loc["Age"]

id
0         58
1         52
2         56
3         44
4         58
          ..
629995    56
629996    54
629997    67
629998    52
629999    51
Name: Age, Length: 630000, dtype: object

In [78]:
# Range of row labels — from "Age" to "BP" (inclusive).
transposed_df.loc["Age":"BP"]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
Sex,1,1,0,0,1,1,1,0,0,0,...,1,1,1,1,1,0,1,1,1,0
Chest pain type,4,1,2,3,4,4,4,3,4,4,...,4,3,1,3,4,1,4,4,4,2
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130

In [64]:
# A LIST of specific row labels.
transposed_df.loc[["Age", "BP", "Heart Disease"]]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130
Heart Disease,Presence,Absence,Absence,Absence,Presence,Presence,Presence,Absence,Absence,Absence,...,Absence,Presence,Presence,Absence,Presence,Absence,Absence,Presence,Presence,Absence

#### Revision example

In [65]:
# This raises an error! Can you figure out why?
# +5000 points if you spot it before running the cell.

transposed_df.loc[["Age", "BP"]]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130

In [ ]:
# Explanation:
# transposed_df.loc["Age", "BP"] means: row="Age", column="BP".
# But the COLUMNS of transposed_df are integers (0, 1, 2, ..., 425), not feature names!
# "BP" is a ROW label, not a column label.
# Fix: use double brackets to select a LIST of rows → transposed_df.loc[["Age", "BP"]]

In [81]:
# Correct: double brackets → list of row labels.
transposed_df.loc[["Age", "BP"]]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
Age,58,52,56,44,58,38,59,60,48,44,...,50,59,48,57,58,56,54,67,52,51
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130

In [82]:
# This works: row label "Age", column label 2 (patient index 2).
transposed_df.loc["Age", 2]

56

#### Summary: selecting multiple rows or columns by name requires a **list** inside `.loc`.
- Single label: `transposed_df.loc["Age"]` → one row  
- List of labels: `transposed_df.loc[["Age", "BP"]]` → multiple rows  
- Range of labels: `transposed_df.loc["Age":"BP"]` → continuous range

In [83]:
# List of row labels AND list of column labels (patient indices).
transposed_df.loc[["Age", "Cholesterol"], [2, 3, 4, 5]]

id             2    3    4    5
Age           56   44   58   38
Cholesterol  188  229  234  283

In [84]:
# Chained bracket slicing on the transposed df.
# First slice: rows up to "Cholesterol". Second slice: columns 3 to 5 (positional).
# Be very careful: BOTH slices here act on ROWS, not rows then columns!

transposed_df[:"Cholesterol"][3:6]

id,0,1,2,3,4,5,6,7,8,9,...,629990,629991,629992,629993,629994,629995,629996,629997,629998,629999
BP,152,125,160,134,140,138,130,120,140,150,...,120,140,140,140,150,110,128,130,140,130
Cholesterol,239,325,188,229,234,283,246,245,212,197,...,282,263,229,288,235,226,249,275,199,199