# Lecture 12a, Logistic Regression

## Available libraries and differences   
- [Scikit learn function and parameters](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)  

- [Scikit learn user guide](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression)   

- [Statsmodels](https://www.statsmodels.org/devel/discretemod.html)   

- [Pingouin docs](https://pingouin-stats.org/build/html/generated/pingouin.logistic_regression.html)   

- [Pingouin source code](https://pingouin-stats.org/build/html/_modules/pingouin/regression.html#logistic_regression), Check docstring, difference with scikit learn.

  > Notes
    .. caution:: This function is a wrapper around the
    :py:class:`sklearn.linear_model.LogisticRegression` class.
    However, Pingouin internally disables the L2 regularization and changes the
        default solver to 'newton-cg' to obtain results that are similar to R and
        statsmodels

- Other: TensorFlow, PyTorch.

[Different use of statsmodels and scikit-learn: stats or predictions](https://stats.stackexchange.com/a/48578)    
[Stats VS Machine Learning: complementarity and differences](https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning)

## Three Datasets: wikipedia, program effectiveness, iris flowers,
Loaded from python libraries.

[Program_Effectiveness Data Source and Info](https://www.statsmodels.org/devel/datasets/generated/spector.html)   

[Program_Effectiveness Original Source and Info](https://pages.stern.nyu.edu/~wgreene/Text/econometricanalysis.htm)  

**Remember**:   
Logistic Regression is a "supervised learning" model.
We know the labels. We have a "y" target variable. 


Goal of the algo: Classify instances (observations) in different use-cases:
* binary
* multi-class
* one VS rest

Classes can be:  
* unordered: all classes of equal "quantity"(?).
* ordered: some classes have "more" of what defines a class. Useful in socio-economic studies: Post Office code.   

Important notes:   
Sigmoid functions property: Non constant "returns".   
Slope: The slope of the sigmoid function is not constant and depends on the value of the input.

How much does a factor affect the result?
What will the result be?
What is the probability of the result?

In [1]:
pwd

'/home/tharg/venv_projects/uoa_py_course/lectures_07_12_pandas_plots_scikit/lecture_12_logistic_regression_naive_bayes_svm'

# A. Import the necessary modules.   
You may add libraries here as you go on with your work. But, all imports should be at the first code cell.

In [2]:
# data management libraries
import pandas as pd
import numpy as np

# scikit learn
from sklearn.linear_model import LogisticRegression
# metrics libraries
from sklearn import metrics
from sklearn.datasets import load_iris

# import pingouin stats library
import pingouin as pg

# import statsmodels stats library
import statsmodels.api as sm

# https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html?highlight=grid%20search#displaying-a-grid-search-over-a-pipeline-with-a-classifier

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# B. Inspect the data and understand its features.   
See which are the variables, what is their type, what are the values that the variables take.  
At this step, you should think about possible relations that you ought to examine.   
Which do you think might be more important?

## The wikipedia example

In [3]:
# First, let's create the dataframe
Hours = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,
         2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]

Pass = [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]

In [4]:
df = pd.DataFrame({'HoursStudy': Hours, 'PassExam': Pass})

In [5]:
df

    HoursStudy  PassExam
0         0.50         0
1         0.75         0
2         1.00         0
3         1.25         0
4         1.50         0
5         1.75         0
6         1.75         1
7         2.00         0
8         2.25         1
9         2.50         0
10        2.75         1
11        3.00         0
12        3.25         1
13        3.50         0
14        4.00         1
15        4.25         1
16        4.50         1
17        4.75         1
18        5.00         1
19        5.50         1

In [6]:
# X is the independent variable
X = df['HoursStudy']

In [7]:
X.sample(2)

16    4.50
3     1.25
Name: HoursStudy, dtype: float64

In [8]:
# y is the dependent variable
y = df['PassExam']

## Using logistic regression as a linear regression (example using Pingouin)

In [9]:

help(pg.logistic_regression)

Help on function logistic_regression in module pingouin.regression:

logistic_regression(X, y, coef_only=False, alpha=0.05, as_dataframe=True, remove_na=False, **kwargs)
    (Multiple) Binary logistic regression.

    Parameters
    ----------
    X : array_like
        Predictor(s), of shape *(n_samples, n_features)* or *(n_samples)*.
    y : array_like
        Dependent variable, of shape *(n_samples)*.
        ``y`` must be binary, i.e. only contains 0 or 1. Multinomial logistic
        regression is not supported.
    coef_only : bool
        If True, return only the regression coefficients.
    alpha : float
        Alpha value used for the confidence intervals.
        :math:`\text{CI} = [\alpha / 2 ; 1 - \alpha / 2]`
    as_dataframe : bool
        If True, returns a pandas DataFrame. If False, returns a dictionnary.
    remove_na : bool
        If True, apply a listwise deletion of missing values (i.e. the entire
        row is removed). Default is False, which will raise an error if missing
        values are present in either the predictor(s) or dependent
        variable.
    **kwargs : optional
        Optional arguments passed to
        :py:class:`sklearn.linear_model.LogisticRegression` (see Notes).

    Returns
    -------
    stats : :py:class:`pandas.DataFrame` or dict
        Logistic regression summary:

        * ``'names'``: name of variable(s) in the model (e.g. x1, x2...)
        * ``'coef'``: regression coefficients (log-odds)
        * ``'se'``: standard error
        * ``'z'``: z-scores
        * ``'pval'``: two-tailed p-values
        * ``'CI[2.5%]'``: lower confidence interval
        * ``'CI[97.5%]'``: upper confidence interval

    See also
    --------
    linear_regression

    Notes
    -----
    .. caution:: This function is a wrapper around the
        :py:class:`sklearn.linear_model.LogisticRegression` class. However,
        Pingouin internally disables the L2 regularization and changes the
        default solver to 'newton-cg' to obtain results that are similar to R and
        statsmodels.

    Logistic regression assumes that the log-odds (the logarithm of the
    odds) for the value labeled "1" in the response variable is a linear
    combination of the predictor variables. The log-odds are given by the
    `logit <https://en.wikipedia.org/wiki/Logit>`_ function,
    which map a probability :math:`p` of the response variable being "1"
    from :math:`[0, 1)` to :math:`(-\infty, +\infty)`.

    .. math:: \text{logit}(p) = \ln \frac{p}{1 - p} = \beta_0 + \beta X

    The odds of the response variable being "1" can be obtained by
    exponentiating the log-odds:

    .. math:: \frac{p}{1 - p} = e^{\beta_0 + \beta X}

    and the probability of the response variable being "1" is given by the
    `logistic function <https://en.wikipedia.org/wiki/Logistic_function>`_:

    .. math:: p = \frac{1}{1 + e^{-(\beta_0 + \beta X})}

    The first coefficient is always the constant term (intercept) of
    the model. Pingouin will automatically add the intercept
    to your predictor(s) matrix, therefore, :math:`X` should not include a
    constant term. Pingouin will remove any constant term (e.g column with only
    one unique value), or duplicate columns from :math:`X`.

    The calculation of the p-values and confidence interval is adapted from a
    `code by Rob Speare
    <https://gist.github.com/rspeare/77061e6e317896be29c6de9a85db301d>`_.
    Results have been compared against statsmodels, R, and JASP.

    Examples
    --------
    1. Simple binary logistic regression.

    In this first example, we'll use the
    `penguins dataset <https://github.com/allisonhorst/palmerpenguins>`_
    to see how well we can predict the sex of penguins based on their
    bodies mass.

    >>> import numpy as np
    >>> import pandas as pd
    >>> import pingouin as pg
    >>> df = pg.read_dataset('penguins')
    >>> # Let's first convert the target variable from string to boolean:
    >>> df['male'] = (df['sex'] == 'male').astype(int)  # male: 1, female: 0
    >>> # Since there are missing values in our outcome variable, we need to
    >>> # set `remove_na=True` otherwise regression will fail.
    >>> lom = pg.logistic_regression(df['body_mass_g'], df['male'],
    ...                              remove_na=True)
    >>> lom.round(2)
             names  coef    se     z  pval  CI[2.5%]  CI[97.5%]
    0    Intercept -5.16  0.71 -7.24   0.0     -6.56      -3.77
    1  body_mass_g  0.00  0.00  7.24   0.0      0.00       0.00

    Body mass is a significant predictor of sex (p<0.001). Here, it
    could be useful to rescale our predictor variable from *g* to *kg*
    (e.g divide by 1000) in order to get more intuitive coefficients and
    confidence intervals:

    >>> df['body_mass_kg'] = df['body_mass_g'] / 1000
    >>> lom = pg.logistic_regression(df['body_mass_kg'], df['male'],
    ...                              remove_na=True)
    >>> lom.round(2)
              names  coef    se     z  pval  CI[2.5%]  CI[97.5%]
    0     Intercept -5.16  0.71 -7.24   0.0     -6.56      -3.77
    1  body_mass_kg  1.23  0.17  7.24   0.0      0.89       1.56

    2. Multiple binary logistic regression

    We'll now add the species as a categorical predictor in our model. To do
    so, we first need to dummy-code our categorical variable, dropping the
    first level of our categorical variable (species = Adelie) which will be
    used as the reference level:

    >>> df = pd.get_dummies(df, columns=['species'], dtype=float, drop_first=True)
    >>> X = df[['body_mass_kg', 'species_Chinstrap', 'species_Gentoo']]
    >>> y = df['male']
    >>> lom = pg.logistic_regression(X, y, remove_na=True)
    >>> lom.round(2)
                   names   coef    se     z  pval  CI[2.5%]  CI[97.5%]
    0          Intercept -26.24  2.84 -9.24  0.00    -31.81     -20.67
    1       body_mass_kg   7.10  0.77  9.23  0.00      5.59       8.61
    2  species_Chinstrap  -0.13  0.42 -0.31  0.75     -0.96       0.69
    3     species_Gentoo  -9.72  1.12 -8.65  0.00    -11.92      -7.52

    3. Using NumPy aray and returning only the coefficients

    >>> pg.logistic_regression(X.to_numpy(), y.to_numpy(), coef_only=True,
    ...                        remove_na=True)
    array([-26.23906892,   7.09826571,  -0.13180626,  -9.71718529])

    4. Passing custom parameters to sklearn

    >>> lom = pg.logistic_regression(X, y, solver='sag', max_iter=10000,
    ...                           random_state=42, remove_na=True)
    >>> print(lom['coef'].to_numpy())
    [-25.98248153   7.02881472  -0.13119779  -9.62247569]

    **How to interpret the log-odds coefficients?**

    We'll use the `Wikipedia example
    <https://en.wikipedia.org/wiki/Logistic_regression#Probability_of_passing_an_exam_versus_hours_of_study>`_
    of the probability of passing an exam
    versus the hours of study:

    *A group of 20 students spends between 0 and 6 hours studying for an
    exam. How does the number of hours spent studying affect the
    probability of the student passing the exam?*

    >>> # First, let's create the dataframe
    >>> Hours = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,
    ...          2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]
    >>> Pass = [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]
    >>> df = pd.DataFrame({'HoursStudy': Hours, 'PassExam': Pass})
    >>> # And then run the logistic regression
    >>> lr = pg.logistic_regression(df['HoursStudy'], df['PassExam']).round(3)
    >>> lr
            names   coef     se      z   pval  CI[2.5%]  CI[97.5%]
    0   Intercept -4.078  1.761 -2.316  0.021    -7.529     -0.626
    1  HoursStudy  1.505  0.629  2.393  0.017     0.272      2.737

    The ``Intercept`` coefficient (-4.078) is the log-odds of ``PassExam=1``
    when ``HoursStudy=0``. The odds ratio can be obtained by exponentiating
    the log-odds:

    >>> np.exp(-4.078)
    0.016941314421496552

    i.e. :math:`0.017:1`. Conversely the odds of failing the exam are
    :math:`(1/0.017) \approx 59:1`.

    The probability can then be obtained with the following equation

    .. math:: p = \frac{1}{1 + e^{-(-4.078 + 0 * 1.505)}}

    >>> 1 / (1 + np.exp(-(-4.078)))
    0.016659087580814722

    The ``HoursStudy`` coefficient (1.505) means that for each additional hour
    of study, the log-odds of passing the exam increase by 1.505, and the odds
    are multipled by :math:`e^{1.505} \approx 4.50`.

    For example, a student who studies 2 hours has a probability of passing
    the exam of 25%:

    >>> 1 / (1 + np.exp(-(-4.078 + 2 * 1.505)))
    0.2557836148964987

    The table below shows the probability of passing the exam for several
    values of ``HoursStudy``:

    +----------------+----------+----------------+------------------+
    | Hours of Study | Log-odds | Odds           | Probability      |
    +================+==========+================+==================+
    | 0              | −4.08    | 0.017 ≈ 1:59   | 0.017            |
    +----------------+----------+----------------+------------------+
    | 1              | −2.57    | 0.076 ≈ 1:13   | 0.07             |
    +----------------+----------+----------------+------------------+
    | 2              | −1.07    | 0.34 ≈ 1:3     | 0.26             |
    +----------------+----------+----------------+------------------+
    | 3              | 0.44     | 1.55           | 0.61             |
    +----------------+----------+----------------+------------------+
    | 4              | 1.94     | 6.96           | 0.87             |
    +----------------+----------+----------------+------------------+
    | 5              | 3.45     | 31.4           | 0.97             |
    +----------------+----------+----------------+------------------+
    | 6              | 4.96     | 141.4          | 0.99             |
    +----------------+----------+----------------+------------------+

In [10]:
lr = pg.logistic_regression(X, y, penalty="l2").round(3)
lr

        names   coef     se      z   pval  CI[2.5%]  CI[97.5%]
0   Intercept -3.139  1.438 -2.183  0.029    -5.958     -0.320
1  HoursStudy  1.148  0.498  2.308  0.021     0.173      2.124

In [11]:
pg.logistic_regression(X.to_numpy(), y.to_numpy(), coef_only=True, penalty="l2")

array([-3.13904399,  1.14843327])

## The program effectiveness data

In [12]:
spector_data = sm.datasets.spector.load()

In [13]:
spector_data

In [14]:
spector_data.endog

0     0.0
1     0.0
2     0.0
3     0.0
4     1.0
5     0.0
6     0.0
7     0.0
8     0.0
9     1.0
10    0.0
11    0.0
12    0.0
13    1.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    1.0
20    0.0
21    1.0
22    0.0
23    0.0
24    1.0
25    1.0
26    1.0
27    0.0
28    1.0
29    1.0
30    0.0
31    1.0
Name: GRADE, dtype: float64

In [15]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)

In [16]:
spector_data.exog

     GPA  TUCE  PSI  const
0   2.66  20.0  0.0    1.0
1   2.89  22.0  0.0    1.0
2   3.28  24.0  0.0    1.0
3   2.92  12.0  0.0    1.0
4   4.00  21.0  0.0    1.0
5   2.86  17.0  0.0    1.0
6   2.76  17.0  0.0    1.0
7   2.87  21.0  0.0    1.0
8   3.03  25.0  0.0    1.0
9   3.92  29.0  0.0    1.0
10  2.63  20.0  0.0    1.0
11  3.32  23.0  0.0    1.0
12  3.57  23.0  0.0    1.0
13  3.26  25.0  0.0    1.0
14  3.53  26.0  0.0    1.0
15  2.74  19.0  0.0    1.0
16  2.75  25.0  0.0    1.0
17  2.83  19.0  0.0    1.0
18  3.12  23.0  1.0    1.0
19  3.16  25.0  1.0    1.0
20  2.06  22.0  1.0    1.0
21  3.62  28.0  1.0    1.0
22  2.89  14.0  1.0    1.0
23  3.51  26.0  1.0    1.0
24  3.54  24.0  1.0    1.0
25  2.83  27.0  1.0    1.0
26  3.39  17.0  1.0    1.0
27  2.67  24.0  1.0    1.0
28  3.65  21.0  1.0    1.0
29  4.00  23.0  1.0    1.0
30  3.10  21.0  1.0    1.0
31  2.39  19.0  1.0    1.0

In [17]:
spector_data

In [18]:
type(spector_data)

statsmodels.datasets.utils.Dataset

In [19]:
print(spector_data.exog.head())

    GPA  TUCE  PSI  const
0  2.66  20.0  0.0    1.0
1  2.89  22.0  0.0    1.0
2  3.28  24.0  0.0    1.0
3  2.92  12.0  0.0    1.0
4  4.00  21.0  0.0    1.0

In [20]:
print(spector_data.endog.head())

0    0.0
1    0.0
2    0.0
3    0.0
4    1.0
Name: GRADE, dtype: float64

In [21]:
X = pd.DataFrame(spector_data.exog)

In [22]:
X

     GPA  TUCE  PSI  const
0   2.66  20.0  0.0    1.0
1   2.89  22.0  0.0    1.0
2   3.28  24.0  0.0    1.0
3   2.92  12.0  0.0    1.0
4   4.00  21.0  0.0    1.0
5   2.86  17.0  0.0    1.0
6   2.76  17.0  0.0    1.0
7   2.87  21.0  0.0    1.0
8   3.03  25.0  0.0    1.0
9   3.92  29.0  0.0    1.0
10  2.63  20.0  0.0    1.0
11  3.32  23.0  0.0    1.0
12  3.57  23.0  0.0    1.0
13  3.26  25.0  0.0    1.0
14  3.53  26.0  0.0    1.0
15  2.74  19.0  0.0    1.0
16  2.75  25.0  0.0    1.0
17  2.83  19.0  0.0    1.0
18  3.12  23.0  1.0    1.0
19  3.16  25.0  1.0    1.0
20  2.06  22.0  1.0    1.0
21  3.62  28.0  1.0    1.0
22  2.89  14.0  1.0    1.0
23  3.51  26.0  1.0    1.0
24  3.54  24.0  1.0    1.0
25  2.83  27.0  1.0    1.0
26  3.39  17.0  1.0    1.0
27  2.67  24.0  1.0    1.0
28  3.65  21.0  1.0    1.0
29  4.00  23.0  1.0    1.0
30  3.10  21.0  1.0    1.0
31  2.39  19.0  1.0    1.0

In [23]:
y = pd.DataFrame(spector_data.endog)
y.sample(10)

    GRADE
19    1.0
30    0.0
21    1.0
18    0.0
6     0.0
27    0.0
29    1.0
7     0.0
3     0.0
1     0.0

## Using logistic regression as a linear regression (example using Statsmodels)

In [24]:
logit_mod = sm.Logit(spector_data.endog, spector_data.exog)

In [25]:
logit_mod = sm.Logit(y, X)

In [26]:
#results = logit_mod.fit()
logit_res = logit_mod.fit(disp=0)
print("Parameters:\n",logit_res.params)

Parameters:
 GPA       2.826113
TUCE      0.095158
PSI       2.378688
const   -13.021347
dtype: float64

In [27]:

help(logit_res)

Help on BinaryResultsWrapper in module statsmodels.discrete.discrete_model:

<statsmodels.discrete.discrete_model.BinaryResultsWrapper object>
    A results class for Logit Model

    Parameters
    ----------
    model : A DiscreteModel instance
    params : array_like
        The parameters of a fitted model.
    hessian : array_like
        The hessian of the fitted model.
    scale : float
        A scale parameter for the covariance matrix.

    Attributes
    ----------
    df_resid : float
        See model definition.
    df_model : float
        See model definition.
    llf : float
        Value of the loglikelihood

In [28]:
logit_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Tue, 27 May 2025   Pseudo R-squ.:                  0.3740
Time:                        15:20:06   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
==============================================================================
"""

In [29]:
A = np.identity(len(logit_res.params))
A = A[1:,:]

In [30]:
logit_res.f_test(A)

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=2.8850001268853, p=0.05331525256957256, df_denom=28, df_num=3>

In [31]:
margeff = logit_res.get_margeff()
print(margeff.summary())

        Logit Marginal Effects
=====================================
Dep. Variable:                  GRADE
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            0.3626      0.109      3.313      0.001       0.148       0.577
TUCE           0.0122      0.018      0.686      0.493      -0.023       0.047
PSI            0.3052      0.092      3.304      0.001       0.124       0.486
==============================================================================

In [32]:
print(logit_res.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Tue, 27 May 2025   Pseudo R-squ.:                  0.3740
Time:                        15:20:06   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
==============================================================================

In [33]:
print(logit_res.summary2())

                         Results: Logit
================================================================
Model:              Logit            Method:           MLE
Dependent Variable: GRADE            Pseudo R-squared: 0.374
Date:               2025-05-27 15:20 AIC:              33.7793
No. Observations:   32               BIC:              39.6422
Df Model:           3                Log-Likelihood:   -12.890
Df Residuals:       28               LL-Null:          -20.592
Converged:          1.0000           LLR p-value:      0.0015019
No. Iterations:     7.0000           Scale:            1.0000
-----------------------------------------------------------------
            Coef.    Std.Err.     z     P>|z|    [0.025    0.975]
-----------------------------------------------------------------
GPA          2.8261    1.2629   2.2377  0.0252    0.3508   5.3014
TUCE         0.0952    0.1416   0.6722  0.5014   -0.1823   0.3726
PSI          2.3787    1.0646   2.2344  0.0255    0.2922   4.4652
const      -13.0213    4.9313  -2.6405  0.0083  -22.6866  -3.3561
================================================================

## Iris from scikit-learn

In [34]:
dataset = load_iris()

In [35]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [38]:
X, y = load_iris(return_X_y=True)

In [39]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

### Always holdout data for testing in real life.
### in these lecture notes I performed no split of the datasets only to focus on other issues.

In [40]:
help(LogisticRegression)

Help on class LogisticRegression in module sklearn.linear_model._logistic:

class LogisticRegression(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
 |  that regularization is applied by default**. It can handle both dense
 |  and sparse input. Use C-ordered arrays or CSR matrices containing 64-bit
 |  floats for optimal performance; any other input format will be converted
 |  (and copied).
 |
 |  The 'newton-cg', 'sag', and 'lbfgs' solvers support only L2 regularization
 |  with primal formulation, or no regularization. The 'liblinear' solver
 |  supports both L1 and L2 regularization, with a dual formulation only for
 |  the L2 penalty. The Elastic-Net regularization is only supported by the
 |  'saga' solver.
 |
 |  Read more in the :ref:`User Guide <logistic_regression>`.
 |
 |  Parameters
 |  ----------
 |  penalty : {'l1', 'l2', 'elasticnet', None}, default='l2'
 |      Specify the norm of the penalty:
 |
 |      - `None`: no penalty is added;
 |      - `'l2'`: add a L2 penalty term and it is the default choice;
 |      - `'l1'`: add a L1 penalty term;
 |      - `'elasticnet'`: both L1 and L2 penalty terms are added.
 |
 |      .. warning::
 |         Some penalties may not work with some solvers. See the parameter
 |         `solver` below, to know the compatibility between the penalty and
 |         solver.
 |
 |      .. versionadded:: 0.19
 |         l1 penalty with SAGA solver (allowing 'multinomial' + L1)
 |
 |  dual : bool, default=False
 |      Dual (constrained) or primal (regularized, see also
 |      :ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulation
 |      is only implemented for l2 penalty with liblinear solver. Prefer dual=False when
 |      n_samples > n_features.
 |
 |  tol : float, default=1e-4
 |      Tolerance for stopping criteria.
 |
 |  C : float, default=1.0
 |      Inverse of regularization strength; must be a positive float.
 |      Like in support vector machines, smaller values specify stronger
 |      regularization.
 |
 |  fit_intercept : bool, default=True
 |      Specifies if a constant (a.k.a. bias or intercept) should be
 |      added to the decision function.
 |
 |  intercept_scaling : float, default=1
 |      Useful only when the solver 'liblinear' is used
 |      and self.fit_intercept is set to True. In this case, x becomes
 |      [x, self.intercept_scaling],
 |      i.e. a "synthetic" feature with constant value equal to
 |      intercept_scaling is appended to the instance vector.
 |      The intercept becomes ``intercept_scaling * synthetic_feature_weight``.
 |
 |      Note! the synthetic feature weight is subject to l1/l2 regularization
 |      as all other features.
 |      To lessen the effect of regularization on synthetic feature weight
 |      (and therefore on the intercept) intercept_scaling has to be increased.
 |
 |  class_weight : dict or 'balanced', default=None
 |      Weights associated with classes in the form ``{class_label: weight}``.
 |      If not given, all classes are supposed to have weight one.
 |
 |      The "balanced" mode uses the values of y to automatically adjust
 |      weights inversely proportional to class frequencies in the input data
 |      as ``n_samples / (n_classes * np.bincount(y))``.
 |
 |      Note that these weights will be multiplied with sample_weight (passed
 |      through the fit method) if sample_weight is specified.
 |
 |      .. versionadded:: 0.17
 |         *class_weight='balanced'*
 |
 |  random_state : int, RandomState instance, default=None
 |      Used when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle the
 |      data. See :term:`Glossary <random_state>` for details.
 |
 |  solver : {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'},             default='lbfgs'
 |
 |      Algorithm to use in the optimization problem. Default is 'lbfgs'.
 |      To choose a solver, you might want to consider the following aspects:
 |
 |          - For small datasets, 'liblinear' is a good choice, whereas 'sag'
 |            and 'saga' are faster for large ones;
 |          - For multiclass problems, only 'newton-cg', 'sag', 'saga' and
 |            'lbfgs' handle multinomial loss;
 |          - 'liblinear' is limited to one-versus-rest schemes.
 |          - 'newton-cholesky' is a good choice for `n_samples` >> `n_features`,
 |            especially with one-hot encoded categorical features with rare
 |            categories. Note that it is limited to binary classification and the
 |            one-versus-rest reduction for multiclass classification. Be aware that
 |            the memory usage of this solver has a quadratic dependency on
 |            `n_features` because it explicitly computes the Hessian matrix.
 |
 |      .. warning::
 |         The choice of the algorithm depends on the penalty chosen.
 |         Supported penalties by solver:
 |
 |         - 'lbfgs'           -   ['l2', None]
 |         - 'liblinear'       -   ['l1', 'l2']
 |         - 'newton-cg'       -   ['l2', None]
 |         - 'newton-cholesky' -   ['l2', None]
 |         - 'sag'             -   ['l2', None]
 |         - 'saga'            -   ['elasticnet', 'l1', 'l2', None]
 |
 |      .. note::
 |         'sag' and 'saga' fast convergence is only guaranteed on features
 |         with approximately the same scale. You can preprocess the data with
 |         a scaler from :mod:`sklearn.preprocessing`.
 |
 |      .. seealso::
 |         Refer to the User Guide for more information regarding
 |         :class:`LogisticRegression` and more specifically the
 |         :ref:`Table <Logistic_regression>`
 |         summarizing solver/penalty supports.
 |
 |      .. versionadded:: 0.17
 |         Stochastic Average Gradient descent solver.
 |      .. versionadded:: 0.19
 |         SAGA solver.
 |      .. versionchanged:: 0.22
 |          The default solver changed from 'liblinear' to 'lbfgs' in 0.22.
 |      .. versionadded:: 1.2
 |         newton-cholesky solver.
 |
 |  max_iter : int, default=100
 |      Maximum number of iterations taken for the solvers to converge.
 |
 |  multi_class : {'auto', 'ovr', 'multinomial'}, default='auto'
 |      If the option chosen is 'ovr', then a binary problem is fit for each
 |      label. For 'multinomial' the loss minimised is the multinomial loss fit
 |      across the entire probability distribution, *even when the data is
 |      binary*. 'multinomial' is unavailable when solver='liblinear'.
 |      'auto' selects 'ovr' if the data is binary, or if solver='liblinear',
 |      and otherwise selects 'multinomial'.
 |
 |      .. versionadded:: 0.18
 |         Stochastic Average Gradient descent solver for 'multinomial' case.
 |      .. versionchanged:: 0.22
 |          Default changed from 'ovr' to 'auto' in 0.22.
 |
 |  verbose : int, default=0
 |      For the liblinear and lbfgs solvers set verbose to any positive
 |      number for verbosity.
 |
 |  warm_start : bool, default=False
 |      When set to True, reuse the solution of the previous call to fit as
 |      initialization, otherwise, just erase the previous solution.
 |      Useless for liblinear solver. See :term:`the Glossary <warm_start>`.
 |
 |      .. versionadded:: 0.17
 |         *warm_start* to support *lbfgs*, *newton-cg*, *sag*, *saga* solvers.
 |
 |  n_jobs : int, default=None
 |      Number of CPU cores used when parallelizing over classes if
 |      multi_class='ovr'". This parameter is ignored when the ``solver`` is
 |      set to 'liblinear' regardless of whether 'multi_class' is specified or
 |      not. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`
 |      context. ``-1`` means using all processors.
 |      See :term:`Glossary <n_jobs>` for more details.
 |
 |  l1_ratio : float, default=None
 |      The Elastic-Net mixing parameter, with ``0 <= l1_ratio <= 1``. Only
 |      used if ``penalty='elasticnet'``. Setting ``l1_ratio=0`` is equivalent
 |      to using ``penalty='l2'``, while setting ``l1_ratio=1`` is equivalent
 |      to using ``penalty='l1'``. For ``0 < l1_ratio <1``, the penalty is a
 |      combination of L1 and L2.
 |
 |  Attributes
 |  ----------
 |
 |  classes_ : ndarray of shape (n_classes, )
 |      A list of class labels known to the classifier.
 |
 |  coef_ : ndarray of shape (1, n_features) or (n_classes, n_features)
 |      Coefficient of the features in the decision function.
 |
 |      `coef_` is of shape (1, n_features) when the given problem is binary.
 |      In particular, when `multi_class='multinomial'`, `coef_` corresponds
 |      to outcome 1 (True) and `-coef_` corresponds to outcome 0 (False).
 |
 |  intercept_ : ndarray of shape (1,) or (n_classes,)
 |      Intercept (a.k.a. bias) added to the decision function.
 |
 |      If `fit_intercept` is set to False, the intercept is set to zero.
 |      `intercept_` is of shape (1,) when the given problem is binary.
 |      In particular, when `multi_class='multinomial'`, `intercept_`
 |      corresponds to outcome 1 (True) and `-intercept_` corresponds to
 |      outcome 0 (False).
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_iter_ : ndarray of shape (n_classes,) or (1, )
 |      Actual number of iterations for all classes. If binary or multinomial,
 |      it returns only 1 element. For liblinear solver, only the maximum
 |      number of iteration across all classes is given.
 |
 |      .. versionchanged:: 0.20
 |
 |          In SciPy <= 1.0.0 the number of lbfgs iterations may exceed
 |          ``max_iter``. ``n_iter_`` will now report at most ``max_iter``.
 |
 |  See Also
 |  --------
 |  SGDClassifier : Incrementally trained logistic regression (when given
 |      the parameter ``loss="log_loss"``).
 |  LogisticRegressionCV : Logistic regression with built-in cross validation.
 |
 |  Notes
 |  -----
 |  The underlying C implementation uses a random number generator to
 |  select features when fitting the model. It is thus not uncommon,
 |  to have slightly different results for the same input data. If
 |  that happens, try with a smaller tol parameter.
 |
 |  Predict output may not match that of standalone liblinear in certain
 |  cases. See :ref:`differences from liblinear <liblinear_differences>`
 |  in the narrative documentation.
 |
 |  References
 |  ----------
 |
 |  L-BFGS-B -- Software for Large-scale Bound-constrained Optimization
 |      Ciyou Zhu, Richard Byrd, Jorge Nocedal and Jose Luis Morales.
 |      http://users.iems.northwestern.edu/~nocedal/lbfgsb.html
 |
 |  LIBLINEAR -- A Library for Large Linear Classification
 |      https://www.csie.ntu.edu.tw/~cjlin/liblinear/
 |
 |  SAG -- Mark Schmidt, Nicolas Le Roux, and Francis Bach
 |      Minimizing Finite Sums with the Stochastic Average Gradient
 |      https://hal.inria.fr/hal-00860051/document
 |
 |  SAGA -- Defazio, A., Bach F. & Lacoste-Julien S. (2014).
 |          :arxiv:`"SAGA: A Fast Incremental Gradient Method With Support
 |          for Non-Strongly Convex Composite Objectives" <1407.0202>`
 |
 |  Hsiang-Fu Yu, Fang-Lan Huang, Chih-Jen Lin (2011). Dual coordinate descent
 |      methods for logistic regression and maximum entropy models.
 |      Machine Learning 85(1-2):41-75.
 |      https://www.csie.ntu.edu.tw/~cjlin/papers/maxent_dual.pdf
 |
 |  Examples
 |  --------
 |  >>> from sklearn.datasets import load_iris
 |  >>> from sklearn.linear_model import LogisticRegression
 |  >>> X, y = load_iris(return_X_y=True)
 |  >>> clf = LogisticRegression(random_state=0).fit(X, y)
 |  >>> clf.predict(X[:2, :])
 |  array([0, 0])
 |  >>> clf.predict_proba(X[:2, :])
 |  array([[9.8...e-01, 1.8...e-02, 1.4...e-08],
 |         [9.7...e-01, 2.8...e-02, ...e-08]])
 |  >>> clf.score(X, y)
 |  0.97...
 |
 |  Method resolution order:
 |      LogisticRegression
 |      sklearn.linear_model._base.LinearClassifierMixin
 |      sklearn.base.ClassifierMixin
 |      sklearn.linear_model._base.SparseCoefMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y, sample_weight=None)
 |      Fit the model according to the given training data.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          Training vector, where `n_samples` is the number of samples and
 |          `n_features` is the number of features.
 |
 |      y : array-like of shape (n_samples,)
 |          Target vector relative to X.
 |
 |      sample_weight : array-like of shape (n_samples,) default=None
 |          Array of weights that are assigned to individual samples.
 |          If not provided, then each sample is given unit weight.
 |
 |          .. versionadded:: 0.17
 |             *sample_weight* support to LogisticRegression.
 |
 |      Returns
 |      -------
 |      self
 |          Fitted estimator.
 |
 |      Notes
 |      -----
 |      The SAGA solver supports both float64 and float32 bit arrays.
 |
 |  predict_log_proba(self, X)
 |      Predict logarithm of probability estimates.
 |
 |      The returned estimates for all classes are ordered by the
 |      label of classes.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Vector to be scored, where `n_samples` is the number of samples and
 |          `n_features` is the number of features.
 |
 |      Returns
 |      -------
 |      T : array-like of shape (n_samples, n_classes)
 |          Returns the log-probability of the sample for each class in the
 |          model, where classes are ordered as they are in ``self.classes_``.
 |
 |  predict_proba(self, X)
 |      Probability estimates.
 |
 |      The returned estimates for all classes are ordered by the
 |      label of classes.
 |
 |      For a multi_class problem, if multi_class is set to be "multinomial"
 |      the softmax function is used to find the predicted probability of
 |      each class.
 |      Else use a one-vs-rest approach, i.e. calculate the probability
 |      of each class assuming it to be positive using the logistic function.
 |      and normalize these values across all the classes.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Vector to be scored, where `n_samples` is the number of samples and
 |          `n_features` is the number of features.
 |
 |      Returns
 |      -------
 |      T : array-like of shape (n_samples, n_classes)
 |          Returns the probability of the sample for each class in the model,
 |          where classes are ordered as they are in ``self.classes_``.
 |
 |  set_fit_request(self: sklearn.linear_model._logistic.LogisticRegression, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.linear_model._logistic.LogisticRegression from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``fit`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  set_score_request(self: sklearn.linear_model._logistic.LogisticRegression, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.linear_model._logistic.LogisticRegression from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``score`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |

In [41]:
clf = LogisticRegression(max_iter=400, solver='lbfgs', penalty='l2')

In [42]:

clf

LogisticRegression(max_iter=400)

In [43]:
clf = LogisticRegression(max_iter=400).fit(X, y)

In [44]:

clf

LogisticRegression(max_iter=400)

In [45]:
clf.predict(X[:, :])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:

clf

LogisticRegression(max_iter=400)

In [47]:
np.set_printoptions(suppress=True)

In [48]:
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.99595572, 0.00404427, 0.        ],
       [0.95178337, 0.0482164 , 0.00000024],
       [0.9516439 , 0.04835589, 0.00000021],
       [0.95097208, 0.04902783, 0.00000009],
       [0.96929487, 0.03070504, 0.00000009],
       [0.9746081 , 0.02539188, 0.00000003],
       [0.97701547, 0.02298451, 0.00000002],
       [0.97098686, 0.02901308, 0.00000006],
       [0.96393942, 0.03606051, 0.00000007],
       [0.96439323, 0.03560671, 0.00000006],
       [0.98827211, 0.01172788, 0.00000001],
       [0.98892134, 0.01107866, 0.00000001],
       [0.96834355, 0.0316564 , 0.00000004],
       [0.98441638, 0.01558361, 0.00000001],
       [0.97856874, 0.02143125, 0.00000001],
       [0.9867328 , 0.01326719, 0.00000001],
       [0.98570608, 0.01429391, 0.00000002],
       [0.97378515, 0.02621482, 0.00000003],
       [0.98644397, 0.01355602, 0.00000001],
       [0.96166874, 0.03833119, 0.00000007],
       [0.98891483, 0.01108516, 0.00000001],
       [0.97215787, 0.027842  , 0.00000014],
       [0.96002286, 0.03997691, 0.00000022],
       [0.97352609, 0.02647387, 0.00000004],
       [0.9801403 , 0.01985967, 0.00000003],
       [0.98317946, 0.01682052, 0.00000002],
       [0.97831231, 0.02168768, 0.00000002],
       [0.97839393, 0.02160605, 0.00000002],
       [0.00212359, 0.87407819, 0.12379822],
       [0.00581427, 0.85981231, 0.13437342],
       [0.00105987, 0.72525793, 0.27368221],
       [0.01543153, 0.93964232, 0.04492615],
       [0.00237587, 0.81527699, 0.18234714],
       [0.00699746, 0.86006552, 0.13293702],
       [0.00377087, 0.71662283, 0.2796063 ],
       [0.1479972 , 0.8489463 , 0.00305651],
       [0.00277652, 0.89669226, 0.10053122],
       [0.04152028, 0.91183771, 0.04664201],
       [0.05592129, 0.93760263, 0.00647608],
       [0.0151753 , 0.89884805, 0.08597666],
       [0.00909833, 0.97656642, 0.01433525],
       [0.00305281, 0.77926874, 0.21767846],
       [0.07441596, 0.91513279, 0.01045126],
       [0.00527489, 0.92641289, 0.06831223],
       [0.00872745, 0.77461592, 0.21665663],
       [0.01646473, 0.96516591, 0.01836936],
       [0.00181135, 0.80099624, 0.19719241],
       [0.02398511, 0.95941064, 0.01660425],
       [0.00230811, 0.44016173, 0.55753016],
       [0.01681404, 0.95680135, 0.02638461],
       [0.00071596, 0.59626649, 0.40301755],
       [0.00304552, 0.85988459, 0.13706989],
       [0.00707077, 0.94298297, 0.04994625],
       [0.00507051, 0.92015665, 0.07477284],
       [0.00111942, 0.80162872, 0.19725186],
       [0.00057847, 0.48129715, 0.51812438],
       [0.00548614, 0.81309504, 0.18141882],
       [0.0616561 , 0.93496409, 0.00337981],
       [0.02917199, 0.95720898, 0.01361902],
       [0.03718691, 0.95527727, 0.00753582],
       [0.02517635, 0.95648404, 0.01833961],
       [0.00045021, 0.34963497, 0.64991483],
       [0.01024942, 0.75078545, 0.23896512],
       [0.00998985, 0.78875438, 0.20125577],
       [0.00226244, 0.80529023, 0.19244733],
       [0.00276378, 0.91317182, 0.0840644 ],
       [0.02708093, 0.92849077, 0.0444283 ],
       [0.01992924, 0.93804488, 0.04202588],
       [0.00873899, 0.89781907, 0.09344194],
       [0.00464876, 0.8282742 , 0.16707704],
       [0.01758242, 0.95700709, 0.02541049],
       [0.12185081, 0.87509808, 0.0030511 ],
       [0.0144845 , 0.92042754, 0.06508796],
       [0.02001004, 0.93806817, 0.04192179],
       [0.01711489, 0.92540309, 0.05748202],
       [0.00849614, 0.93513901, 0.05636485],
       [0.24355615, 0.75515201, 0.00129184],
       [0.01917167, 0.93602145, 0.04480688],
       [0.0000009 , 0.00391511, 0.99608399],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000248, 0.02559259, 0.97440493],
       [0.00003128, 0.0816796 , 0.91828912],
       [0.00000374, 0.01744695, 0.98254931],
       [0.00000006, 0.00464343, 0.99535651],
       [0.00578669, 0.51340727, 0.48080604],
       [0.00000062, 0.02135875, 0.97864062],
       [0.00000524, 0.05328474, 0.94671002],
       [0.00000065, 0.00574967, 0.99424967],
       [0.000302  , 0.21055263, 0.78914536],
       [0.00007279, 0.13730751, 0.8626197 ],
       [0.00002126, 0.06529715, 0.93468159],
       [0.00022956, 0.14516128, 0.85460916],
       [0.00006903, 0.04349228, 0.95643869],
       [0.00005158, 0.05405426, 0.94589415],
       [0.00005567, 0.1229304 , 0.87701392],
       [0.00000008, 0.00356624, 0.99643367],
       [0.        , 0.00100107, 0.99899892],
       [0.00039037, 0.45178362, 0.54782601],
       [0.0000056 , 0.02386557, 0.97612883],
       [0.00061421, 0.19037146, 0.80901433],
       [0.00000003, 0.00465871, 0.99534126],
       [0.00058553, 0.39306306, 0.60635141],
       [0.00001284, 0.03862669, 0.96136047],
       [0.00000486, 0.05153045, 0.94846469],
       [0.00107238, 0.45647594, 0.54245168],
       [0.00102345, 0.38536012, 0.61361643],
       [0.00001066, 0.03633929, 0.96365005],
       [0.00001691, 0.1420745 , 0.85790859],
       [0.00000106, 0.02921944, 0.9707795 ],
       [0.0000007 , 0.01744977, 0.98254952],
       [0.00000789, 0.02726308, 0.97272903],
       [0.00052954, 0.47556317, 0.52390729],
       [0.00006288, 0.18852658, 0.81141054],
       [0.00000039, 0.01175875, 0.98824086],
       [0.00001162, 0.01733402, 0.98265435],
       [0.00006776, 0.11950872, 0.88042352],
       [0.0016216 , 0.44036439, 0.55801401],
       [0.00003965, 0.09354291, 0.90641744],
       [0.0000063 , 0.02029973, 0.97969397],
       [0.00009945, 0.12072613, 0.87917442],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000205, 0.01259405, 0.9874039 ],
       [0.00000381, 0.01211188, 0.98788432],
       [0.00005584, 0.0801491 , 0.91979506],
       [0.00022707, 0.25188101, 0.74789192],
       [0.00013834, 0.15716862, 0.84269304],
       [0.00004565, 0.03844053, 0.96151382],
       [0.00047631, 0.23484773, 0.76467596]])

In [49]:
clf.score(X, y)

0.9733333333333334

In [50]:
clf.n_features_in_

4

In [51]:
# link to liblinear libary, go to datasets, phising dataset
# LogisticRegression?

clf.classes_

array([0, 1, 2])

In [52]:
clf.coef_

array([[-0.42456599,  0.96664261, -2.51554625, -1.08216927],
       [ 0.53541119, -0.32073935, -0.20740629, -0.94263206],
       [-0.1108452 , -0.64590325,  2.72295254,  2.02480133]])

In [53]:
clf.intercept_

array([  9.85494228,   2.23117432, -12.0861166 ])

In [54]:
len(clf.predict_proba(X))

150

In [55]:
clf.score(X, y)

0.9733333333333334

In [56]:
y_pred_default = clf.predict(X)
y_pred_default

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [57]:
clf.score(X, y_pred_default)

1.0

In [58]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.3).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
clf.score(X, y_pred_tuned)

0.6533333333333333

In [60]:
# Predict confidence scores for samples.
# where > 0 means this class would be predicted.
clf.decision_function(X)

array([[  7.33470626,   3.36028842, -10.69499468],
       [  6.93629815,   3.41357586, -10.34987401],
       [  7.4660945 ,   3.26308638, -10.72918088],
       [  6.90877759,   3.20013794, -10.10891552],
       [  7.47382712,   3.27467337, -10.74850048],
       [  6.62289578,   3.14186774,  -9.76476351],
       [  7.34210807,   3.03039356, -10.37250162],
       [  7.02894397,   3.31808061, -10.34702458],
       [  7.05191689,   3.1779442 , -10.22986109],
       [  6.88962472,   3.4550245 , -10.34464922],
       [  7.14911036,   3.43602328, -10.58513364],
       [  6.86230254,   3.19025774, -10.05256029],
       [  7.08697168,   3.45429795, -10.54126963],
       [  8.05391855,   3.24881424, -11.30273279],
       [  8.02394062,   3.61618783, -11.64012845],
       [  7.48195653,   3.18360267, -10.66555921],
       [  7.62911428,   3.22483025, -10.85394453],
       [  7.22648933,   3.26602521, -10.49251455],
       [  6.50707865,   3.42882823,  -9.93590688],
       [  7.26492749,   3.14906278, -10.41399027],
       [  6.35600833,   3.49076383,  -9.84677215],
       [  7.0600463 ,   3.08687351, -10.14691981],
       [  8.64987201,   3.14347141, -11.79334342],
       [  6.06206308,   3.07942479,  -9.14148787],
       [  6.10763867,   3.12803586,  -9.23567453],
       [  6.3907323 ,   3.42563572,  -9.81636803],
       [  6.56095549,   3.10881357,  -9.66976906],
       [  7.04069504,   3.39308891, -10.43378394],
       [  7.1955854 ,   3.44590347, -10.64148887],
       [  6.71143062,   3.20086449,  -9.91229512],
       [  6.57230976,   3.28647955,  -9.85878931],
       [  6.64268372,   3.34371867,  -9.98640239],
       [  7.72889753,   3.2949085 , -11.02380603],
       [  7.84152969,   3.34993535, -11.19146504],
       [  6.78140779,   3.3607613 , -10.14216908],
       [  7.59027933,   3.44445036, -11.03472969],
       [  7.41643449,   3.59519352, -11.01162801],
       [  7.62450064,   3.31539545, -10.9398961 ],
       [  7.40013577,   3.16661089, -10.56674667],
       [  6.98648737,   3.37162173, -10.3581091 ],
       [  7.52050056,   3.23322472, -10.75372528],
       [  6.57281242,   3.35040636,  -9.92321878],
       [  7.59346429,   3.10246302, -10.69592732],
       [  6.4411859 ,   2.88821322,  -9.32939912],
       [  6.15049206,   2.97183706,  -9.12232912],
       [  6.87053782,   3.26577154, -10.13630936],
       [  7.12158979,   3.22258536, -10.34417515],
       [  7.25699647,   3.18880463, -10.4458011 ],
       [  7.19156696,   3.38248216, -10.57404912],
       [  7.18383434,   3.37089517, -10.55472951],
       [ -3.36186766,   2.65819227,   0.70367539],
       [ -2.71223574,   2.28416361,   0.42807213],
       [ -4.0274015 ,   2.50098062,   1.52642087],
       [ -1.72589772,   2.38318851,  -0.6572908 ],
       [ -3.39290401,   2.44525984,   0.94764417],
       [ -2.58526274,   2.22619793,   0.35906481],
       [ -3.18444106,   2.06280409,   1.12163697],
       [  0.71103929,   2.45784188,  -3.16888118],
       [ -3.12226249,   2.65525344,   0.46700906],
       [ -1.06853318,   2.02074684,  -0.95221366],
       [ -0.2211836 ,   2.59819749,  -2.37701389],
       [ -1.93861739,   2.14282777,  -0.20421038],
       [ -1.71019419,   2.96575766,  -1.25556347],
       [ -3.26975105,   2.27254401,   0.99720704],
       [ -0.18215025,   2.32724853,  -2.14509828],
       [ -2.57649825,   2.59186473,  -0.01536649],
       [ -2.56591147,   1.91998253,   0.64592894],
       [ -1.39351431,   2.67756512,  -1.2840508 ],
       [ -3.59396515,   2.49782073,   1.09614442],
       [ -1.10703732,   2.5818488 ,  -1.47481149],
       [ -3.5792674 ,   1.67144651,   1.90782089],
       [ -1.49731601,   2.54406555,  -1.04674954],
       [ -4.35264747,   2.37217752,   1.98046994],
       [ -3.14998146,   2.49314435,   0.6568371 ],
       [ -2.28268542,   2.61039308,  -0.32770767],
       [ -2.63070591,   2.57039755,   0.06030836],
       [ -3.91516613,   2.65866515,   1.25650098],
       [ -4.50714104,   2.21670528,   2.29043576],
       [ -2.83240213,   2.16622094,   0.66618119],
       [  0.06160577,   2.7805417 ,  -2.84214748],
       [ -0.90969035,   2.58112225,  -1.6714319 ],
       [ -0.5499188 ,   2.69612608,  -2.14620728],
       [ -1.10683892,   2.53051996,  -1.42368104],
       [ -4.64327533,   2.01166183,   2.63161349],
       [ -2.48099827,   1.81290029,   0.66809798],
       [ -2.45729775,   1.91158806,   0.54570969],
       [ -3.43937905,   2.43537964,   1.00399941],
       [ -3.07176901,   2.72855495,   0.34321406],
       [ -1.34325912,   2.19147146,  -0.84821234],
       [ -1.5325692 ,   2.31904064,  -0.78647145],
       [ -2.33390651,   2.2982674 ,   0.03563911],
       [ -2.92153216,   2.2612107 ,   0.66032146],
       [ -1.4550578 ,   2.54185327,  -1.08679546],
       [  0.57191843,   2.54345694,  -3.11537537],
       [ -1.88480652,   2.26695263,  -0.38214611],
       [ -1.52905341,   2.31853515,  -0.78948174],
       [ -1.7339346 ,   2.25634588,  -0.52241128],
       [ -2.19777222,   2.50331085,  -0.30553863],
       [  1.3692373 ,   2.50080887,  -3.87004617],
       [ -1.57904424,   2.30916045,  -0.73011621],
       [ -7.42860353,   0.94480707,   6.48379646],
       [ -4.88301291,   1.62178998,   3.26122293],
       [ -7.37382677,   1.86715128,   5.50667549],
       [ -6.05152358,   1.81590777,   4.23561582],
       [ -6.97574948,   1.47238199,   5.50336749],
       [ -9.34699214,   1.98967247,   7.35731967],
       [ -2.96847044,   1.51703797,   1.45143247],
       [ -8.23697195,   2.20613455,   6.03083739],
       [ -7.11111627,   2.11688672,   4.99422955],
       [ -7.77227476,   1.3097147 ,   6.46256006],
       [ -4.80510473,   1.74194493,   3.0631598 ],
       [ -5.64086175,   1.90155544,   3.73930632],
       [ -6.24023847,   1.78949044,   4.45074804],
       [ -4.89054714,   1.55887416,   3.33167298],
       [ -5.32743329,   1.11840002,   4.20903327],
       [ -5.59040816,   1.36413294,   4.22627523],
       [ -5.78821789,   1.9116567 ,   3.8765612 ],
       [ -8.97590621,   1.67161827,   7.30428793],
       [-10.74720351,   1.92076103,   8.82644248],
       [ -4.76682508,   2.28703535,   2.47978973],
       [ -6.80890966,   1.54887601,   5.26003364],
       [ -4.30654313,   1.42985186,   2.87669127],
       [ -9.72611496,   2.18088404,   7.54523092],
       [ -4.48396973,   2.02524004,   2.45872969],
       [ -6.41089834,   1.59824625,   4.81265209],
       [ -7.14985869,   2.11859351,   5.03126518],
       [ -4.09329424,   1.96036561,   2.13292863],
       [ -4.10906375,   1.82193599,   2.28712776],
       [ -6.51529522,   1.6187332 ,   4.89656202],
       [ -6.62364411,   2.41274905,   4.21089505],
       [ -7.98120048,   2.23896766,   5.74223283],
       [ -8.08972167,   2.02944881,   6.06027287],
       [ -6.62351215,   1.52447   ,   5.09904215],
       [ -4.56576394,   2.23447446,   2.33128947],
       [ -5.82373546,   2.18210016,   3.6416353 ],
       [ -8.34810947,   1.95839032,   6.38971915],
       [ -6.21750384,   1.08995886,   5.12754499],
       [ -5.64909703,   1.82604164,   3.82305539],
       [ -3.81505252,   1.7891355 ,   2.02591702],
       [ -5.93447619,   1.83169825,   4.10277794],
       [ -6.67732302,   1.40034514,   5.27697789],
       [ -5.39624617,   1.70539372,   3.69085244],
       [ -4.88301291,   1.62178998,   3.26122293],
       [ -7.26956231,   1.45385364,   5.81570867],
       [ -6.84376605,   1.22119343,   5.62257262],
       [ -5.65955185,   1.60964479,   4.04990706],
       [ -5.0370698 ,   1.97438407,   3.06268573],
       [ -5.24998787,   1.78535217,   3.4646357 ],
       [ -5.56372107,   1.1721622 ,   4.39155887],
       [ -4.5272598 ,   1.6733725 ,   2.8538873 ]])

In [61]:
# clf?

In [62]:
clf.get_params([X])

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 400,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [63]:
clf.n_iter_

array([109], dtype=int32)

In [64]:
# clf.predict_log_proba(X)

In [65]:
clf.predict_proba?

In [66]:
# len(clf.predict_proba(X))
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.99595572, 0.00404427, 0.        ],
       [0.95178337, 0.0482164 , 0.00000024],
       [0.9516439 , 0.04835589, 0.00000021],
       [0.95097208, 0.04902783, 0.00000009],
       [0.96929487, 0.03070504, 0.00000009],
       [0.9746081 , 0.02539188, 0.00000003],
       [0.97701547, 0.02298451, 0.00000002],
       [0.97098686, 0.02901308, 0.00000006],
       [0.96393942, 0.03606051, 0.00000007],
       [0.96439323, 0.03560671, 0.00000006],
       [0.98827211, 0.01172788, 0.00000001],
       [0.98892134, 0.01107866, 0.00000001],
       [0.96834355, 0.0316564 , 0.00000004],
       [0.98441638, 0.01558361, 0.00000001],
       [0.97856874, 0.02143125, 0.00000001],
       [0.9867328 , 0.01326719, 0.00000001],
       [0.98570608, 0.01429391, 0.00000002],
       [0.97378515, 0.02621482, 0.00000003],
       [0.98644397, 0.01355602, 0.00000001],
       [0.96166874, 0.03833119, 0.00000007],
       [0.98891483, 0.01108516, 0.00000001],
       [0.97215787, 0.027842  , 0.00000014],
       [0.96002286, 0.03997691, 0.00000022],
       [0.97352609, 0.02647387, 0.00000004],
       [0.9801403 , 0.01985967, 0.00000003],
       [0.98317946, 0.01682052, 0.00000002],
       [0.97831231, 0.02168768, 0.00000002],
       [0.97839393, 0.02160605, 0.00000002],
       [0.00212359, 0.87407819, 0.12379822],
       [0.00581427, 0.85981231, 0.13437342],
       [0.00105987, 0.72525793, 0.27368221],
       [0.01543153, 0.93964232, 0.04492615],
       [0.00237587, 0.81527699, 0.18234714],
       [0.00699746, 0.86006552, 0.13293702],
       [0.00377087, 0.71662283, 0.2796063 ],
       [0.1479972 , 0.8489463 , 0.00305651],
       [0.00277652, 0.89669226, 0.10053122],
       [0.04152028, 0.91183771, 0.04664201],
       [0.05592129, 0.93760263, 0.00647608],
       [0.0151753 , 0.89884805, 0.08597666],
       [0.00909833, 0.97656642, 0.01433525],
       [0.00305281, 0.77926874, 0.21767846],
       [0.07441596, 0.91513279, 0.01045126],
       [0.00527489, 0.92641289, 0.06831223],
       [0.00872745, 0.77461592, 0.21665663],
       [0.01646473, 0.96516591, 0.01836936],
       [0.00181135, 0.80099624, 0.19719241],
       [0.02398511, 0.95941064, 0.01660425],
       [0.00230811, 0.44016173, 0.55753016],
       [0.01681404, 0.95680135, 0.02638461],
       [0.00071596, 0.59626649, 0.40301755],
       [0.00304552, 0.85988459, 0.13706989],
       [0.00707077, 0.94298297, 0.04994625],
       [0.00507051, 0.92015665, 0.07477284],
       [0.00111942, 0.80162872, 0.19725186],
       [0.00057847, 0.48129715, 0.51812438],
       [0.00548614, 0.81309504, 0.18141882],
       [0.0616561 , 0.93496409, 0.00337981],
       [0.02917199, 0.95720898, 0.01361902],
       [0.03718691, 0.95527727, 0.00753582],
       [0.02517635, 0.95648404, 0.01833961],
       [0.00045021, 0.34963497, 0.64991483],
       [0.01024942, 0.75078545, 0.23896512],
       [0.00998985, 0.78875438, 0.20125577],
       [0.00226244, 0.80529023, 0.19244733],
       [0.00276378, 0.91317182, 0.0840644 ],
       [0.02708093, 0.92849077, 0.0444283 ],
       [0.01992924, 0.93804488, 0.04202588],
       [0.00873899, 0.89781907, 0.09344194],
       [0.00464876, 0.8282742 , 0.16707704],
       [0.01758242, 0.95700709, 0.02541049],
       [0.12185081, 0.87509808, 0.0030511 ],
       [0.0144845 , 0.92042754, 0.06508796],
       [0.02001004, 0.93806817, 0.04192179],
       [0.01711489, 0.92540309, 0.05748202],
       [0.00849614, 0.93513901, 0.05636485],
       [0.24355615, 0.75515201, 0.00129184],
       [0.01917167, 0.93602145, 0.04480688],
       [0.0000009 , 0.00391511, 0.99608399],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000248, 0.02559259, 0.97440493],
       [0.00003128, 0.0816796 , 0.91828912],
       [0.00000374, 0.01744695, 0.98254931],
       [0.00000006, 0.00464343, 0.99535651],
       [0.00578669, 0.51340727, 0.48080604],
       [0.00000062, 0.02135875, 0.97864062],
       [0.00000524, 0.05328474, 0.94671002],
       [0.00000065, 0.00574967, 0.99424967],
       [0.000302  , 0.21055263, 0.78914536],
       [0.00007279, 0.13730751, 0.8626197 ],
       [0.00002126, 0.06529715, 0.93468159],
       [0.00022956, 0.14516128, 0.85460916],
       [0.00006903, 0.04349228, 0.95643869],
       [0.00005158, 0.05405426, 0.94589415],
       [0.00005567, 0.1229304 , 0.87701392],
       [0.00000008, 0.00356624, 0.99643367],
       [0.        , 0.00100107, 0.99899892],
       [0.00039037, 0.45178362, 0.54782601],
       [0.0000056 , 0.02386557, 0.97612883],
       [0.00061421, 0.19037146, 0.80901433],
       [0.00000003, 0.00465871, 0.99534126],
       [0.00058553, 0.39306306, 0.60635141],
       [0.00001284, 0.03862669, 0.96136047],
       [0.00000486, 0.05153045, 0.94846469],
       [0.00107238, 0.45647594, 0.54245168],
       [0.00102345, 0.38536012, 0.61361643],
       [0.00001066, 0.03633929, 0.96365005],
       [0.00001691, 0.1420745 , 0.85790859],
       [0.00000106, 0.02921944, 0.9707795 ],
       [0.0000007 , 0.01744977, 0.98254952],
       [0.00000789, 0.02726308, 0.97272903],
       [0.00052954, 0.47556317, 0.52390729],
       [0.00006288, 0.18852658, 0.81141054],
       [0.00000039, 0.01175875, 0.98824086],
       [0.00001162, 0.01733402, 0.98265435],
       [0.00006776, 0.11950872, 0.88042352],
       [0.0016216 , 0.44036439, 0.55801401],
       [0.00003965, 0.09354291, 0.90641744],
       [0.0000063 , 0.02029973, 0.97969397],
       [0.00009945, 0.12072613, 0.87917442],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000205, 0.01259405, 0.9874039 ],
       [0.00000381, 0.01211188, 0.98788432],
       [0.00005584, 0.0801491 , 0.91979506],
       [0.00022707, 0.25188101, 0.74789192],
       [0.00013834, 0.15716862, 0.84269304],
       [0.00004565, 0.03844053, 0.96151382],
       [0.00047631, 0.23484773, 0.76467596]])

In [67]:
clf.predict_proba(X)[:,1]

array([0.01844368, 0.02867258, 0.01473031, 0.02392443, 0.01478635,
       0.02985689, 0.01323307, 0.02387256, 0.02035283, 0.03123145,
       0.0238208 , 0.02479405, 0.02576404, 0.00812135, 0.0120359 ,
       0.01340868, 0.01207721, 0.01869799, 0.04401337, 0.01605002,
       0.05389863, 0.01846623, 0.00404427, 0.0482164 , 0.04835589,
       0.04902783, 0.03070504, 0.02539188, 0.02298451, 0.02901308,
       0.03606051, 0.03560671, 0.01172788, 0.01107866, 0.0316564 ,
       0.01558361, 0.02143125, 0.01326719, 0.01429391, 0.02621482,
       0.01355602, 0.03833119, 0.01108516, 0.027842  , 0.03997691,
       0.02647387, 0.01985967, 0.01682052, 0.02168768, 0.02160605,
       0.87407819, 0.85981231, 0.72525793, 0.93964232, 0.81527699,
       0.86006552, 0.71662283, 0.8489463 , 0.89669226, 0.91183771,
       0.93760263, 0.89884805, 0.97656642, 0.77926874, 0.91513279,
       0.92641289, 0.77461592, 0.96516591, 0.80099624, 0.95941064,
       0.44016173, 0.95680135, 0.59626649, 0.85988459, 0.94298297,
       0.92015665, 0.80162872, 0.48129715, 0.81309504, 0.93496409,
       0.95720898, 0.95527727, 0.95648404, 0.34963497, 0.75078545,
       0.78875438, 0.80529023, 0.91317182, 0.92849077, 0.93804488,
       0.89781907, 0.8282742 , 0.95700709, 0.87509808, 0.92042754,
       0.93806817, 0.92540309, 0.93513901, 0.75515201, 0.93602145,
       0.00391511, 0.16250271, 0.02559259, 0.0816796 , 0.01744695,
       0.00464343, 0.51340727, 0.02135875, 0.05328474, 0.00574967,
       0.21055263, 0.13730751, 0.06529715, 0.14516128, 0.04349228,
       0.05405426, 0.1229304 , 0.00356624, 0.00100107, 0.45178362,
       0.02386557, 0.19037146, 0.00465871, 0.39306306, 0.03862669,
       0.05153045, 0.45647594, 0.38536012, 0.03633929, 0.1420745 ,
       0.02921944, 0.01744977, 0.02726308, 0.47556317, 0.18852658,
       0.01175875, 0.01733402, 0.11950872, 0.44036439, 0.09354291,
       0.02029973, 0.12072613, 0.16250271, 0.01259405, 0.01211188,
       0.0801491 , 0.25188101, 0.15716862, 0.03844053, 0.23484773])

In [68]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.8).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.4).astype(bool)
y_pred_tuned

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [70]:
preds = clf.predict_proba(X)

In [71]:
preds

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.99595572, 0.00404427, 0.        ],
       [0.95178337, 0.0482164 , 0.00000024],
       [0.9516439 , 0.04835589, 0.00000021],
       [0.95097208, 0.04902783, 0.00000009],
       [0.96929487, 0.03070504, 0.00000009],
       [0.9746081 , 0.02539188, 0.00000003],
       [0.97701547, 0.02298451, 0.00000002],
       [0.97098686, 0.02901308, 0.00000006],
       [0.96393942, 0.03606051, 0.00000007],
       [0.96439323, 0.03560671, 0.00000006],
       [0.98827211, 0.01172788, 0.00000001],
       [0.98892134, 0.01107866, 0.00000001],
       [0.96834355, 0.0316564 , 0.00000004],
       [0.98441638, 0.01558361, 0.00000001],
       [0.97856874, 0.02143125, 0.00000001],
       [0.9867328 , 0.01326719, 0.00000001],
       [0.98570608, 0.01429391, 0.00000002],
       [0.97378515, 0.02621482, 0.00000003],
       [0.98644397, 0.01355602, 0.00000001],
       [0.96166874, 0.03833119, 0.00000007],
       [0.98891483, 0.01108516, 0.00000001],
       [0.97215787, 0.027842  , 0.00000014],
       [0.96002286, 0.03997691, 0.00000022],
       [0.97352609, 0.02647387, 0.00000004],
       [0.9801403 , 0.01985967, 0.00000003],
       [0.98317946, 0.01682052, 0.00000002],
       [0.97831231, 0.02168768, 0.00000002],
       [0.97839393, 0.02160605, 0.00000002],
       [0.00212359, 0.87407819, 0.12379822],
       [0.00581427, 0.85981231, 0.13437342],
       [0.00105987, 0.72525793, 0.27368221],
       [0.01543153, 0.93964232, 0.04492615],
       [0.00237587, 0.81527699, 0.18234714],
       [0.00699746, 0.86006552, 0.13293702],
       [0.00377087, 0.71662283, 0.2796063 ],
       [0.1479972 , 0.8489463 , 0.00305651],
       [0.00277652, 0.89669226, 0.10053122],
       [0.04152028, 0.91183771, 0.04664201],
       [0.05592129, 0.93760263, 0.00647608],
       [0.0151753 , 0.89884805, 0.08597666],
       [0.00909833, 0.97656642, 0.01433525],
       [0.00305281, 0.77926874, 0.21767846],
       [0.07441596, 0.91513279, 0.01045126],
       [0.00527489, 0.92641289, 0.06831223],
       [0.00872745, 0.77461592, 0.21665663],
       [0.01646473, 0.96516591, 0.01836936],
       [0.00181135, 0.80099624, 0.19719241],
       [0.02398511, 0.95941064, 0.01660425],
       [0.00230811, 0.44016173, 0.55753016],
       [0.01681404, 0.95680135, 0.02638461],
       [0.00071596, 0.59626649, 0.40301755],
       [0.00304552, 0.85988459, 0.13706989],
       [0.00707077, 0.94298297, 0.04994625],
       [0.00507051, 0.92015665, 0.07477284],
       [0.00111942, 0.80162872, 0.19725186],
       [0.00057847, 0.48129715, 0.51812438],
       [0.00548614, 0.81309504, 0.18141882],
       [0.0616561 , 0.93496409, 0.00337981],
       [0.02917199, 0.95720898, 0.01361902],
       [0.03718691, 0.95527727, 0.00753582],
       [0.02517635, 0.95648404, 0.01833961],
       [0.00045021, 0.34963497, 0.64991483],
       [0.01024942, 0.75078545, 0.23896512],
       [0.00998985, 0.78875438, 0.20125577],
       [0.00226244, 0.80529023, 0.19244733],
       [0.00276378, 0.91317182, 0.0840644 ],
       [0.02708093, 0.92849077, 0.0444283 ],
       [0.01992924, 0.93804488, 0.04202588],
       [0.00873899, 0.89781907, 0.09344194],
       [0.00464876, 0.8282742 , 0.16707704],
       [0.01758242, 0.95700709, 0.02541049],
       [0.12185081, 0.87509808, 0.0030511 ],
       [0.0144845 , 0.92042754, 0.06508796],
       [0.02001004, 0.93806817, 0.04192179],
       [0.01711489, 0.92540309, 0.05748202],
       [0.00849614, 0.93513901, 0.05636485],
       [0.24355615, 0.75515201, 0.00129184],
       [0.01917167, 0.93602145, 0.04480688],
       [0.0000009 , 0.00391511, 0.99608399],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000248, 0.02559259, 0.97440493],
       [0.00003128, 0.0816796 , 0.91828912],
       [0.00000374, 0.01744695, 0.98254931],
       [0.00000006, 0.00464343, 0.99535651],
       [0.00578669, 0.51340727, 0.48080604],
       [0.00000062, 0.02135875, 0.97864062],
       [0.00000524, 0.05328474, 0.94671002],
       [0.00000065, 0.00574967, 0.99424967],
       [0.000302  , 0.21055263, 0.78914536],
       [0.00007279, 0.13730751, 0.8626197 ],
       [0.00002126, 0.06529715, 0.93468159],
       [0.00022956, 0.14516128, 0.85460916],
       [0.00006903, 0.04349228, 0.95643869],
       [0.00005158, 0.05405426, 0.94589415],
       [0.00005567, 0.1229304 , 0.87701392],
       [0.00000008, 0.00356624, 0.99643367],
       [0.        , 0.00100107, 0.99899892],
       [0.00039037, 0.45178362, 0.54782601],
       [0.0000056 , 0.02386557, 0.97612883],
       [0.00061421, 0.19037146, 0.80901433],
       [0.00000003, 0.00465871, 0.99534126],
       [0.00058553, 0.39306306, 0.60635141],
       [0.00001284, 0.03862669, 0.96136047],
       [0.00000486, 0.05153045, 0.94846469],
       [0.00107238, 0.45647594, 0.54245168],
       [0.00102345, 0.38536012, 0.61361643],
       [0.00001066, 0.03633929, 0.96365005],
       [0.00001691, 0.1420745 , 0.85790859],
       [0.00000106, 0.02921944, 0.9707795 ],
       [0.0000007 , 0.01744977, 0.98254952],
       [0.00000789, 0.02726308, 0.97272903],
       [0.00052954, 0.47556317, 0.52390729],
       [0.00006288, 0.18852658, 0.81141054],
       [0.00000039, 0.01175875, 0.98824086],
       [0.00001162, 0.01733402, 0.98265435],
       [0.00006776, 0.11950872, 0.88042352],
       [0.0016216 , 0.44036439, 0.55801401],
       [0.00003965, 0.09354291, 0.90641744],
       [0.0000063 , 0.02029973, 0.97969397],
       [0.00009945, 0.12072613, 0.87917442],
       [0.00024314, 0.16250271, 0.83725414],
       [0.00000205, 0.01259405, 0.9874039 ],
       [0.00000381, 0.01211188, 0.98788432],
       [0.00005584, 0.0801491 , 0.91979506],
       [0.00022707, 0.25188101, 0.74789192],
       [0.00013834, 0.15716862, 0.84269304],
       [0.00004565, 0.03844053, 0.96151382],
       [0.00047631, 0.23484773, 0.76467596]])

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html?highlight=gridsearch#sklearn.model_selection.GridSearchCV

# Pipeline and GridSearchCV example

In [72]:

pipeline_instance = Pipeline([('classifier' , LogisticRegression())])

# Create param grid, 40 combinations of parameters
param_grid = [

SyntaxError: incomplete input (2244462395.py, line 4)

In [147]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Update pipeline instance with a placeholder for multiple classifiers
pipeline_instance = Pipeline([('classifier', LogisticRegression())])

# Update param grid with additional classifiers and their hyperparameters
param_grid = [
    # Logistic Regression parameters
    {'classifier': [LogisticRegression(max_iter=10000)],
     'classifier__penalty': ['l1', 'l2'],
     'classifier__C': np.logspace(-4, 4, 20),
     'classifier__solver': ['liblinear', 'saga']},

    # SVC parameters
    {'classifier': [SVC()],
     'classifier__C': [0.1, 1, 10, 100],
     'classifier__kernel': ['linear', 'rbf']},

    # Random Forest parameters
    {'classifier': [RandomForestClassifier()],
     'classifier__n_estimators': [10, 50, 100],
     'classifier__max_depth': [None, 10, 20, 30]}
]

# Create grid search object
clf = GridSearchCV(pipeline_instance, param_grid=param_grid, cv=5, verbose=True, n_jobs=3)

# Fit on data
grid_clf = clf.fit(X, y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

In [148]:
grid_clf.score(X, y)

0.98

In [149]:

grid_clf.best_estimator_

Pipeline(steps=[('classifier',
                 LogisticRegression(C=1.623776739188721, max_iter=10000,
                                    penalty='l1', solver='saga'))])

In [80]:
grid_clf.cv_results_

{'mean_fit_time': array([0.00076461, 0.00082331, 0.00097885, 0.00151606, 0.00074215,
        0.00088644, 0.00070205, 0.00169353, 0.00069695, 0.00093532,
        0.00081773, 0.00134239, 0.00062189, 0.00083241, 0.00069809,
        0.00240178, 0.00070682, 0.00094628, 0.00087762, 0.00358243,
        0.00070343, 0.00184202, 0.00066614, 0.00624175, 0.00078788,
        0.00436406, 0.00071387, 0.01348271, 0.00200453, 0.01701536,
        0.00083351, 0.02095718, 0.00346575, 0.03941498, 0.00086436,
        0.03130474, 0.00635819, 0.08497725, 0.0009057 , 0.04718671,
        0.00806899, 0.04089236, 0.00089941, 0.0422585 , 0.00919061,
        0.07637062, 0.00094509, 0.02497091, 0.01154122, 0.06979895,
        0.00097179, 0.01576576, 0.01019516, 0.06376667, 0.0009891 ,
        0.02439318, 0.01183958, 0.0583849 , 0.00144525, 0.03547692,
        0.01513295, 0.06286492, 0.00106711, 0.04376392, 0.01400261,
        0.06434679, 0.00120392, 0.04692259, 0.01378651, 0.06979203,
        0.00112123, 0.05196033, 0.01496911, 0.06120286, 0.00120902,
        0.05120149, 0.01811805, 0.07206883, 0.00258651, 0.05292373,
        0.00085182, 0.00110335, 0.00072417, 0.00090866, 0.00077715,
        0.00074401, 0.00075569, 0.00093079, 0.01011815, 0.05421667,
        0.08717165, 0.00948648, 0.06475391, 0.0949707 , 0.00909395,
        0.05901227, 0.1242887 , 0.01827335, 0.05700378, 0.11670313]),
 'std_fit_time': array([1.47003336e-04, 1.32572513e-04, 3.76700649e-04, 2.79557121e-04,
        7.78351621e-05, 5.14973093e-05, 1.29787121e-04, 1.85355344e-04,
        1.30086770e-04, 2.05634608e-04, 1.30556534e-04, 1.92583814e-04,
        1.17299867e-04, 1.60826973e-04, 6.96799253e-05, 1.84647172e-04,
        8.83134858e-05, 1.59017364e-04, 4.65772525e-05, 6.28787740e-04,
        1.19171480e-04, 4.21526448e-04, 1.38532971e-04, 9.31572074e-04,
        2.23819642e-04, 2.29109581e-04, 1.60873819e-04, 2.46381377e-04,
        5.25871242e-04, 1.20498079e-03, 8.36841741e-05, 2.19961962e-03,
        6.65477440e-04, 3.20918570e-03, 9.23335289e-05, 2.06558552e-03,
        6.64513143e-04, 1.33685996e-02, 8.24687625e-05, 4.72761461e-03,
        8.84812771e-04, 5.29152057e-03, 5.27711613e-05, 3.18130627e-03,
        1.30445999e-03, 3.78810048e-03, 6.35155328e-05, 4.40924430e-03,
        3.75473037e-03, 1.88139021e-02, 6.08859623e-05, 1.45563172e-03,
        2.49566957e-03, 1.42641128e-02, 6.97436248e-05, 2.70658688e-03,
        2.84273704e-03, 7.64777095e-03, 9.67912571e-04, 4.12012988e-03,
        3.81167749e-03, 1.03000952e-02, 8.37352933e-05, 5.88405208e-03,
        3.28129614e-03, 1.13809839e-02, 6.16431870e-05, 6.75456523e-03,
        3.26735252e-03, 1.17902587e-02, 8.70222457e-05, 9.60004946e-03,
        3.75951197e-03, 1.05106641e-02, 1.04691550e-04, 8.67788885e-03,
        3.41028494e-03, 1.98008607e-02, 2.77846846e-03, 9.83200228e-03,
        9.52483149e-05, 7.55354911e-05, 3.57804573e-05, 2.72162510e-05,
        6.92371166e-05, 1.84577252e-05, 2.58516992e-05, 3.34779080e-04,
        1.56368537e-04, 7.44924058e-03, 3.03110557e-02, 1.55076378e-03,
        9.39918365e-03, 3.83420917e-02, 1.78593168e-03, 6.59644668e-03,
        1.83464968e-02, 6.53651491e-03, 7.82299314e-03, 7.86173478e-03]),
 'mean_score_time': array([0.00037251, 0.00028615, 0.00041246, 0.00038657, 0.00036497,
        0.00035543, 0.00030618, 0.00042539, 0.00033479, 0.00038414,
        0.00034409, 0.00028329, 0.00029855, 0.00034657, 0.0003387 ,
        0.00050836, 0.00037785, 0.00039682, 0.00036612, 0.00040789,
        0.00036144, 0.00039697, 0.00030398, 0.00041137, 0.00030799,
        0.00044146, 0.00036788, 0.00050721, 0.00039196, 0.0005084 ,
        0.00039387, 0.00049253, 0.00040245, 0.0005209 , 0.00035214,
        0.00053577, 0.00044522, 0.00052123, 0.00036426, 0.00052118,
        0.00045824, 0.00052686, 0.00036464, 0.00052009, 0.00040746,
        0.00052304, 0.00035901, 0.0005197 , 0.00042305, 0.00051217,
        0.00034986, 0.00045443, 0.00372877, 0.00053735, 0.00035782,
        0.00047455, 0.00040946, 0.00053344, 0.00034623, 0.00053444,
        0.00048623, 0.000595  , 0.00041823, 0.00050669, 0.00048223,
        0.00053086, 0.00039477, 0.00054002, 0.00044413, 0.00054317,
        0.00037723, 0.00056148, 0.00046611, 0.00053458, 0.00041056,
        0.0005362 , 0.00055456, 0.00055122, 0.00043936, 0.00058999,
        0.00365524, 0.0005487 , 0.00040727, 0.00050826, 0.00039306,
        0.00041251, 0.00039415, 0.0004262 , 0.00079274, 0.00332398,
        0.00298772, 0.00075841, 0.00246987, 0.00310926, 0.00084558,
        0.00240097, 0.00368338, 0.00098882, 0.00238729, 0.00463328]),
 'std_score_time': array([1.36580813e-04, 1.75301060e-05, 2.01351908e-04, 7.10422718e-05,
        4.48509391e-05, 5.86527925e-05, 5.83770995e-05, 9.04030939e-06,
        4.85534973e-05, 3.40854861e-05, 6.24795709e-05, 3.05895404e-05,
        3.48435193e-05, 6.89204732e-05, 4.44438324e-05, 2.98324052e-05,
        7.95389536e-06, 4.34402577e-05, 4.41643888e-05, 7.87379875e-05,
        1.59964476e-05, 2.47326383e-05, 3.23237918e-05, 6.18712704e-05,
        5.02979353e-05, 3.26884306e-05, 7.07646264e-05, 2.42093376e-05,
        4.00174062e-05, 1.89554616e-05, 6.17558429e-05, 3.83975028e-05,
        4.55185964e-05, 4.74063435e-06, 1.59130783e-05, 1.98489159e-05,
        5.27470273e-05, 1.09925186e-05, 2.86762747e-05, 1.29213192e-05,
        5.24596729e-05, 1.79922482e-05, 4.22421208e-05, 1.66091356e-05,
        1.88087932e-05, 2.26878298e-05, 1.75670330e-05, 4.53254726e-05,
        4.43013799e-05, 8.18633722e-06, 9.78341568e-06, 7.91361511e-05,
        6.43767062e-03, 2.37680246e-05, 1.65349086e-05, 3.66006610e-05,
        3.73255993e-05, 1.61595041e-05, 1.92546585e-05, 1.17621336e-05,
        5.03939503e-05, 1.25499572e-04, 9.28174766e-05, 1.19983069e-05,
        6.88597435e-05, 2.01745513e-05, 6.81293344e-06, 3.76523253e-05,
        4.04641776e-05, 1.26747227e-05, 2.89709086e-05, 3.57815375e-05,
        4.48031586e-05, 2.38024386e-05, 7.94474243e-06, 2.36455465e-05,
        3.02846033e-05, 2.87406650e-05, 7.83510925e-05, 3.61175741e-05,
        6.45220057e-03, 1.78496397e-05, 1.89643359e-05, 9.87686194e-06,
        1.42091073e-05, 7.27766611e-06, 3.26694358e-06, 2.85272986e-05,
        5.45696327e-05, 2.08806396e-03, 1.08927958e-03, 6.86777950e-05,
        9.68203260e-05, 1.13150332e-03, 1.08931630e-04, 2.28223280e-04,
        5.26713846e-04, 6.44257294e-05, 2.80240123e-04, 1.40375546e-03]),
 'param_classifier': masked_array(data=[LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000),
                    LogisticRegression(max_iter=10000), SVC(), SVC(),
                    SVC(), SVC(), SVC(), SVC(), SVC(), SVC(),
                    RandomForestClassifier(), RandomForestClassifier(),
                    RandomForestClassifier(), RandomForestClassifier(),
                    RandomForestClassifier(), RandomForestClassifier(),
                    RandomForestClassifier(), RandomForestClassifier(),
                    RandomForestClassifier(), RandomForestClassifier(),
                    RandomForestClassifier(), RandomForestClassifier()],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_classifier__C': masked_array(data=[0.0001, 0.0001, 0.0001, 0.0001, 0.00026366508987303583,
                    0.00026366508987303583, 0.00026366508987303583,
                    0.00026366508987303583, 0.0006951927961775605,
                    0.0006951927961775605, 0.0006951927961775605,
                    0.0006951927961775605, 0.0018329807108324356,
                    0.0018329807108324356, 0.0018329807108324356,
                    0.0018329807108324356, 0.004832930238571752,
                    0.004832930238571752, 0.004832930238571752,
                    0.004832930238571752, 0.012742749857031334,
                    0.012742749857031334, 0.012742749857031334,
                    0.012742749857031334, 0.03359818286283781,
                    0.03359818286283781, 0.03359818286283781,
                    0.03359818286283781, 0.08858667904100823,
                    0.08858667904100823, 0.08858667904100823,
                    0.08858667904100823, 0.23357214690901212,
                    0.23357214690901212, 0.23357214690901212,
                    0.23357214690901212, 0.615848211066026,
                    0.615848211066026, 0.615848211066026,
                    0.615848211066026, 1.623776739188721,
                    1.623776739188721, 1.623776739188721,
                    1.623776739188721, 4.281332398719396,
                    4.281332398719396, 4.281332398719396,
                    4.281332398719396, 11.288378916846883,
                    11.288378916846883, 11.288378916846883,
                    11.288378916846883, 29.763514416313132,
                    29.763514416313132, 29.763514416313132,
                    29.763514416313132, 78.47599703514607,
                    78.47599703514607, 78.47599703514607,
                    78.47599703514607, 206.913808111479, 206.913808111479,
                    206.913808111479, 206.913808111479, 545.5594781168514,
                    545.5594781168514, 545.5594781168514,
                    545.5594781168514, 1438.44988828766, 1438.44988828766,
                    1438.44988828766, 1438.44988828766, 3792.690190732246,
                    3792.690190732246, 3792.690190732246,
                    3792.690190732246, 10000.0, 10000.0, 10000.0, 10000.0,
                    0.1, 0.1, 1, 1, 10, 10, 100, 100, --, --, --, --, --,
                    --, --, --, --, --, --, --],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True],
        fill_value='?',
             dtype=object),
 'param_classifier__penalty': masked_array(data=['l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1',
                    'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1',
                    'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2',
                    'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2',
                    'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1',
                    'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1',
                    'l2', 'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2',
                    'l2', 'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2',
                    'l1', 'l1', 'l2', 'l2', 'l1', 'l1', 'l2', 'l2', --, --,
                    --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                    --, --, --, --],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True],
        fill_value='?',
             dtype=object),
 'param_classifier__solver': masked_array(data=['liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga',
                    'liblinear', 'saga', 'liblinear', 'saga', 'liblinear',
                    'saga', 'liblinear', 'saga', 'liblinear', 'saga', --,
                    --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                    --, --, --, --, --],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True],
        fill_value='?',
             dtype=object),

In [150]:
# convert the results to a DataFrame
results_df = pd.DataFrame(grid_clf.cv_results_)
results_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_classifier__penalty,param_classifier__solver,param_classifier__kernel,param_classifier__max_depth,param_classifier__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001344,0.000131,0.000631,0.000046,LogisticRegression(max_iter=10000),0.0001,l1,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
1,0.001191,0.000117,0.000521,0.000037,LogisticRegression(max_iter=10000),0.0001,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
2,0.001013,0.000127,0.000491,0.000023,LogisticRegression(max_iter=10000),0.0001,l2,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
3,0.002180,0.000157,0.000527,0.000022,LogisticRegression(max_iter=10000),0.0001,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.700000,0.700000,0.666667,0.666667,0.666667,0.680000,0.016330,81
4,0.000818,0.000032,0.000446,0.000009,LogisticRegression(max_iter=10000),0.000264,l1,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.027042,0.000423,0.001130,0.000041,RandomForestClassifier(),NaN,NaN,NaN,NaN,20,50,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.933333,0.900000,1.000000,0.953333,0.033993,56
96,0.054905,0.001659,0.001983,0.000096,RandomForestClassifier(),NaN,NaN,NaN,NaN,20,100,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.933333,0.966667,1.000000,0.966667,0.021082,31
97,0.006245,0.000074,0.000548,0.000005,RandomForestClassifier(),NaN,NaN,NaN,NaN,30,10,"{'classifier': RandomForestClassifier(), 'clas...",0.933333,0.966667,0.900000,0.966667,1.000000,0.953333,0.033993,56
98,0.028352,0.000582,0.001185,0.000051,RandomForestClassifier(),NaN,NaN,NaN,NaN,30,50,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.900000,0.933333,1.000000,0.953333,0.033993,56
99,0.058809,0.004312,0.002111,0.000107,RandomForestClassifier(),NaN,NaN,NaN,NaN,30,100,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.933333,0.900000,1.000000,0.953333,0.033993,56

In [151]:
# get the top 5 results
top_5_results = results_df.nlargest(5, 'mean_test_score')
top_5_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_classifier__penalty,param_classifier__solver,param_classifier__kernel,param_classifier__max_depth,param_classifier__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
41,0.021802,0.002927,0.000283,0.000025,LogisticRegression(max_iter=10000),1.623777,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
43,0.027774,0.003591,0.000279,0.000019,LogisticRegression(max_iter=10000),1.623777,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
45,0.040159,0.001160,0.000333,0.000030,LogisticRegression(max_iter=10000),4.281332,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
47,0.013126,0.002071,0.000270,0.000009,LogisticRegression(max_iter=10000),4.281332,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
49,0.032871,0.005226,0.000318,0.000057,LogisticRegression(max_iter=10000),11.288379,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1

In [152]:
# get the best parameters
best_params = grid_clf.best_params_
best_params

{'classifier': LogisticRegression(max_iter=10000),
 'classifier__C': 1.623776739188721,
 'classifier__penalty': 'l1',
 'classifier__solver': 'saga'}

In [153]:
# The values 9.737937, -2.357894, -38.465492 are the decision scores for a single sample across three classes (e.g., class 0, class 1, and class 2).
# The class with the highest score is the predicted class for that sample.
grid_clf.decision_function(X)

array([[ 9.67367710e+00,  4.11078015e+00, -1.58436460e+01],
       [ 8.13704208e+00,  4.11078015e+00, -1.46076839e+01],
       [ 9.06235192e+00,  4.11078015e+00, -1.50153107e+01],
       [ 8.13371325e+00,  4.11078015e+00, -1.39215255e+01],
       [ 9.98100410e+00,  4.11078015e+00, -1.58604913e+01],
       [ 9.97101761e+00,  4.11078015e+00, -1.49030333e+01],
       [ 9.36635009e+00,  4.11078015e+00, -1.43206384e+01],
       [ 9.05569426e+00,  4.11078015e+00, -1.51237971e+01],
       [ 7.82971508e+00,  4.11078015e+00, -1.36036365e+01],
       [ 8.13371325e+00,  4.11078015e+00, -1.49340868e+01],
       [ 9.97767527e+00,  4.11078015e+00, -1.63260687e+01],
       [ 8.74503843e+00,  4.11078015e+00, -1.44207934e+01],
       [ 8.13704208e+00,  4.11078015e+00, -1.49621105e+01],
       [ 9.06900958e+00,  4.11078015e+00, -1.52612511e+01],
       [ 1.18316238e+01,  4.11078015e+00, -1.86501492e+01],
       [ 1.21289643e+01,  4.11078015e+00, -1.70514018e+01],
       [ 1.12136409e+01,  4.11078015e+00, -1.63987786e+01],
       [ 9.67367710e+00,  4.11078015e+00, -1.53246857e+01],
       [ 9.66369061e+00,  4.11078015e+00, -1.57342157e+01],
       [ 1.02850023e+01,  4.11078015e+00, -1.54948863e+01],
       [ 8.43438259e+00,  4.11078015e+00, -1.50340592e+01],
       [ 9.97767527e+00,  4.11078015e+00, -1.47945470e+01],
       [ 1.12236274e+01,  4.11078015e+00, -1.66981019e+01],
       [ 8.12705559e+00,  4.11078015e+00, -1.28021982e+01],
       [ 7.81307093e+00,  4.11078015e+00, -1.32989845e+01],
       [ 7.51573041e+00,  4.11078015e+00, -1.40243449e+01],
       [ 8.74503843e+00,  4.11078015e+00, -1.37119401e+01],
       [ 9.36302126e+00,  4.11078015e+00, -1.56342434e+01],
       [ 9.36635009e+00,  4.11078015e+00, -1.58268007e+01],
       [ 8.13038442e+00,  4.11078015e+00, -1.38935018e+01],
       [ 7.82305742e+00,  4.11078015e+00, -1.38766565e+01],
       [ 9.05569426e+00,  4.11078015e+00, -1.47440111e+01],
       [ 1.12069833e+01,  4.11078015e+00, -1.72414775e+01],
       [ 1.18249661e+01,  4.11078015e+00, -1.77714335e+01],
       [ 8.13371325e+00,  4.11078015e+00, -1.44151265e+01],
       [ 9.37300775e+00,  4.11078015e+00, -1.58828481e+01],
       [ 9.98433293e+00,  4.11078015e+00, -1.68757171e+01],
       [ 9.98100410e+00,  4.11078015e+00, -1.62149180e+01],
       [ 8.44769791e+00,  4.11078015e+00, -1.41589518e+01],
       [ 9.05569426e+00,  4.11078015e+00, -1.52883308e+01],
       [ 9.98433293e+00,  4.11078015e+00, -1.55340883e+01],
       [ 6.29640889e+00,  4.11078015e+00, -1.25348724e+01],
       [ 9.06235192e+00,  4.11078015e+00, -1.45217097e+01],
       [ 9.05236543e+00,  4.11078015e+00, -1.28553984e+01],
       [ 9.04237894e+00,  4.11078015e+00, -1.34801807e+01],
       [ 8.13704208e+00,  4.11078015e+00, -1.39241899e+01],
       [ 9.97434644e+00,  4.11078015e+00, -1.56399103e+01],
       [ 8.75169609e+00,  4.11078015e+00, -1.44768408e+01],
       [ 9.97767527e+00,  4.11078015e+00, -1.61615350e+01],
       [ 9.05902309e+00,  4.11078015e+00, -1.53163544e+01],
       [-1.49994641e+00,  4.11078015e+00,  1.41773256e-01],
       [-8.78634740e-01,  4.11078015e+00,  9.00063024e-01],
       [-2.42858508e+00,  4.11078015e+00,  1.75451885e+00],
       [-2.09129860e+00,  4.11078015e+00,  1.10567457e+00],
       [-2.41859859e+00,  4.11078015e+00,  1.83498151e+00],
       [-2.10794275e+00,  4.11078015e+00,  1.73939396e+00],
       [-1.19261940e+00,  4.11078015e+00,  2.15005069e+00],
       [ 3.90619232e-01,  4.11078015e+00, -2.26293750e+00],
       [-2.11127158e+00,  4.11078015e+00,  4.51148214e-01],
       [-5.51334757e-01,  4.11078015e+00,  1.01878376e+00],
       [-1.46000045e+00,  4.11078015e+00, -9.54082702e-01],
       [-5.61321247e-01,  4.11078015e+00,  9.63680399e-01],
       [-2.39862561e+00,  4.11078015e+00, -1.09249584e+00],
       [-2.42192742e+00,  4.11078015e+00,  2.16671324e+00],
       [ 9.95286749e-01,  4.11078015e+00, -1.64287814e+00],
       [-8.75305910e-01,  4.11078015e+00, -3.05055687e-01],
       [-1.49328875e+00,  4.11078015e+00,  2.57909037e+00],
       [-1.17264642e+00,  4.11078015e+00, -1.29638699e+00],
       [-3.95190477e+00,  4.11078015e+00,  3.04292001e+00],
       [-1.16598876e+00,  4.11078015e+00, -8.33474004e-01],
       [-1.81060224e+00,  4.11078015e+00,  4.40142134e+00],
       [-5.54663587e-01,  4.11078015e+00, -7.88422312e-01],
       [-4.27254710e+00,  4.11078015e+00,  3.82999470e+00],
       [-2.72925442e+00,  4.11078015e+00,  1.31017155e+00],
       [-1.17930408e+00,  4.11078015e+00, -3.41593369e-01],
       [-1.18263291e+00,  4.11078015e+00,  4.08569540e-02],
       [-3.03991025e+00,  4.11078015e+00,  1.57029278e+00],
       [-3.04656791e+00,  4.11078015e+00,  3.67682214e+00],
       [-1.80061575e+00,  4.11078015e+00,  2.10233462e+00],
       [ 3.83961572e-01,  4.11078015e+00, -3.19409223e+00],
       [-1.16265993e+00,  4.11078015e+00, -8.61497676e-01],
       [-8.52004101e-01,  4.11078015e+00, -1.75439432e+00],
       [-5.51334757e-01,  4.11078015e+00, -1.00633896e+00],
       [-4.27920476e+00,  4.11078015e+00,  5.22767076e+00],
       [-1.49328875e+00,  4.11078015e+00,  2.90815773e+00],
       [-2.63980734e-01,  4.11078015e+00,  1.71440014e+00],
       [-1.80727341e+00,  4.11078015e+00,  1.33571358e+00],
       [-3.33392194e+00,  4.11078015e+00,  1.28515040e+00],
       [-2.50665414e-01,  4.11078015e+00,  4.54244617e-02],
       [-1.47664460e+00,  4.11078015e+00,  7.42916644e-01],
       [-2.41194093e+00,  4.11078015e+00,  1.53832260e+00],
       [-1.80394458e+00,  4.11078015e+00,  1.61139797e+00],
       [-1.16931759e+00,  4.11078015e+00, -4.51023681e-01],
       [ 8.32922288e-02,  4.11078015e+00, -2.24609222e+00],
       [-1.48330226e+00,  4.11078015e+00,  9.63497665e-01],
       [-5.61321247e-01,  4.11078015e+00, -2.64133232e-01],
       [-8.68648250e-01,  4.11078015e+00,  4.36206060e-01],
       [-1.17930408e+00,  4.11078015e+00, -1.25260141e-02],
       [ 1.62991373e+00,  4.11078015e+00, -3.37623243e+00],
       [-8.65319420e-01,  4.11078015e+00,  2.43648711e-01],
       [-5.23114523e+00,  4.11078015e+00,  1.16818657e+01],
       [-4.27920476e+00,  4.11078015e+00,  7.11361910e+00],
       [-5.84247041e+00,  4.11078015e+00,  8.45995556e+00],
       [-5.21782991e+00,  4.11078015e+00,  7.27891402e+00],
       [-5.53181458e+00,  4.11078015e+00,  9.59218164e+00],
       [-8.01706124e+00,  4.11078015e+00,  1.02548414e+01],
       [-3.02992376e+00,  4.11078015e+00,  5.67564159e+00],
       [-7.39242075e+00,  4.11078015e+00,  8.25113143e+00],
       [-7.06844959e+00,  4.11078015e+00,  8.09416779e+00],
       [-4.61982006e+00,  4.11078015e+00,  1.00308620e+01],
       [-2.74256974e+00,  4.11078015e+00,  5.57394887e+00],
       [-4.90051642e+00,  4.11078015e+00,  6.87428966e+00],
       [-4.59984708e+00,  4.11078015e+00,  7.45781134e+00],
       [-4.58320293e+00,  4.11078015e+00,  7.78593472e+00],
       [-3.97187775e+00,  4.11078015e+00,  9.52704178e+00],
       [-3.36388141e+00,  4.11078015e+00,  8.04323616e+00],
       [-4.59984708e+00,  4.11078015e+00,  6.39453139e+00],
       [-5.86910105e+00,  4.11078015e+00,  9.53217262e+00],
       [-1.01783368e+01,  4.11078015e+00,  1.29755531e+01],
       [-5.50518394e+00,  4.11078015e+00,  5.24166893e+00],
       [-4.60650474e+00,  4.11078015e+00,  8.71631302e+00],
       [-3.35056609e+00,  4.11078015e+00,  7.03239519e+00],
       [-8.94237108e+00,  4.11078015e+00,  1.03080416e+01],
       [-3.65789309e+00,  4.11078015e+00,  5.02411776e+00],
       [-4.29917773e+00,  4.11078015e+00,  7.82608075e+00],
       [-5.53847224e+00,  4.11078015e+00,  6.74971928e+00],
       [-3.03991025e+00,  4.11078015e+00,  4.63333616e+00],
       [-2.73591208e+00,  4.11078015e+00,  4.80904822e+00],
       [-5.52515692e+00,  4.11078015e+00,  8.85264029e+00],
       [-5.53181458e+00,  4.11078015e+00,  5.32668393e+00],
       [-7.07843608e+00,  4.11078015e+00,  8.03906442e+00],
       [-4.93713355e+00,  4.11078015e+00,  7.04337567e+00],
       [-5.52515692e+00,  4.11078015e+00,  9.37160062e+00],
       [-3.97187775e+00,  4.11078015e+00,  4.03373043e+00],
       [-6.13981092e+00,  4.11078015e+00,  6.07627695e+00],
       [-6.46378208e+00,  4.11078015e+00,  9.25854678e+00],
       [-3.68119490e+00,  4.11078015e+00,  9.48578117e+00],
       [-4.29252007e+00,  4.11078015e+00,  6.37768610e+00],
       [-2.42525625e+00,  4.11078015e+00,  4.59964559e+00],
       [-3.98186424e+00,  4.11078015e+00,  6.73796239e+00],
       [-4.60317591e+00,  4.11078015e+00,  9.37178335e+00],
       [-3.04989674e+00,  4.11078015e+00,  6.65407411e+00],
       [-4.27920476e+00,  4.11078015e+00,  7.11361910e+00],
       [-5.22781640e+00,  4.11078015e+00,  9.62871932e+00],
       [-4.29917773e+00,  4.11078015e+00,  9.90192207e+00],
       [-3.66787958e+00,  4.11078015e+00,  7.53845674e+00],
       [-4.58320293e+00,  4.11078015e+00,  6.27977232e+00],
       [-3.66787958e+00,  4.11078015e+00,  6.31064311e+00],
       [-3.05988323e+00,  4.11078015e+00,  8.38348190e+00],
       [-3.35722375e+00,  4.11078015e+00,  5.88598820e+00]])