# Lecture 6b: Pandas methods, basic examples.

* View method output VS dataframe modification.  
* Methods on index.
* Methods on columns. (rename column, replace values in a column)
* Methods on dataframe.  (replace values in df, drop rows, drop columns)
* Selecting data using conditions.
* axis=0 (rows) and axis=1 (columns)

In [3]:
# Present working directory. This is the location of the notebook in your computer.
!pwd

/home/tharg/venv_projects/uoa_py_course/lectures_07_12_pandas_plots_scikit/lecture_07_pandas

In [4]:
import pandas as pd

### use the code below to read the csv file.
Make sure to change the path to the location of the file in your computer.

Read the commnent to decide, or send me an email.

In [6]:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
df = pd.read_csv(
    "../../data/kaggle_survey_2020_responses.csv",
    # the location of the file in my PC.
    # "kaggle_survey_2020_responses.csv",  # use this if the file is in the same folder as the notebook.

    usecols=[0, 1, 2, 3, 4, 5, 6, 118],
    low_memory=False)

In [7]:
# mind the decreasing number of non-null
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20037 entries, 0 to 20036
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Time from Start to Finish (seconds)  20037 non-null  object
 1   Q1                                   20037 non-null  object
 2   Q2                                   20037 non-null  object
 3   Q3                                   20037 non-null  object
 4   Q4                                   19570 non-null  object
 5   Q5                                   19278 non-null  object
 6   Q6                                   19121 non-null  object
 7   Q24                                  10730 non-null  object
dtypes: object(8)
memory usage: 1.2+ MB

In [8]:
# first 3 rows
df.head(3)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...,What is your current yearly compensation (appr...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

## 1. View versus "modify". Reindex or not.

In [9]:
# view the names of the df columns
df.columns

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5',
       'Q6', 'Q24'],
      dtype='object')

In [10]:
# View first row data values, as a Series.
#  A slice of a row returns a Series.
df.loc[0]

Time from Start to Finish (seconds)                                Duration (in seconds)
Q1                                                           What is your age (# years)?
Q2                                                What is your gender? - Selected Choice
Q3                                             In which country do you currently reside?
Q4                                     What is the highest level of formal education ...
Q5                                     Select the title most similar to your current ...
Q6                                     For how many years have you been writing code ...
Q24                                    What is your current yearly compensation (appr...
Name: 0, dtype: object

In [11]:
# A single column is a pandas Series, not a DataFrame
# https://pandas.pydata.org/docs/reference/api/pandas.Series.html

type(df.loc[0])

pandas.core.series.Series

In [12]:
# if you are sentimentally atouched to beauty, use a dataframe view output.
# .loc is inclusive
df.loc[0:2]

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...,What is your current yearly compensation (appr...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

In [13]:
# The first row in this file is the "questions". Not real data.
# This returns a view of the object, DOES NOT modify it "inplace".
# Also, the index DOES NOT CHANGE.
df.loc[1:]#.reset_index(drop=True)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
3,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"
4,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
5,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years,NaN
...,...,...,...,...,...,...,...,...
20032,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN,NaN
20033,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years,NaN
20034,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years,$0-999
20035,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years,$0-999
20036,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years,$0-999

In [14]:
df.head(2)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...,What is your current yearly compensation (appr...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN

In [15]:
# This also DOES NOT modify the dataframe AND does NOT reset the index.
# Also a view of the df
df.loc[1:].reset_index(drop=True)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"
3,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
4,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years,NaN
...,...,...,...,...,...,...,...,...
20031,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN,NaN
20032,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years,NaN
20033,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years,$0-999
20034,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years,$0-999
20035,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years,$0-999

In [16]:
df.head(2)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...,What is your current yearly compensation (appr...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN

### 1.1 Create a copy, and reset the index

In [15]:
# create a copy to see the difference and still be able to access the original one.
copy_df = df.copy()

In [16]:
# we modify by assignment.
# chose rows 1 to end
# set new index and drop the previous one
copy_df = copy_df.loc[1:].reset_index(drop=True)

In [17]:
# New first row, new index.
# Now the index starts from zero.
copy_df.head(2)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

## 2. Basic Methods in pandas dataframe

### 2.1 Rename columns

In [18]:
# Another view, no modification
# show how to rename a single column.
copy_df.rename(columns={"Q1": "age"}).head(2)  # rename(dictionary "key": "value")

,Time from Start to Finish (seconds),age,Q2,Q3,Q4,Q5,Q6,Q24
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

In [19]:
# the name of Q1 columns is still the same
copy_df.head(2)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q24
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

In [20]:
# the name of Q1 columns is the same
copy_df.columns

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5',
       'Q6', 'Q24'],
      dtype='object')

In [21]:
# create a list of column names
list_of_column_names =  list(df.columns)
list_of_column_names

['Time from Start to Finish (seconds)',
 'Q1',
 'Q2',
 'Q3',
 'Q4',
 'Q5',
 'Q6',
 'Q24']

In [22]:
# # Cool comprehension example, but then you need to add by hand one by one the values in the dict
# dict_of_column_renames = {i : "new_name" for i in list(df.columns) }

# dict_of_column_renames

In [23]:
# create a list for the new names
# btw, no spaces, no capital letters in names => faster coding
list_of_new_column_names = [
    "duration", "age", "gender", "country", "education", "role", "prog_xp", "salary"]

list_of_new_column_names

['duration',
 'age',
 'gender',
 'country',
 'education',
 'role',
 'prog_xp',
 'salary']

In [24]:
# recommended way to create a dictionary from two lists
dict_of_column_renames = dict(
    zip(list_of_column_names, list_of_new_column_names)
)

In [25]:
dict_of_column_renames

{'Time from Start to Finish (seconds)': 'duration',
 'Q1': 'age',
 'Q2': 'gender',
 'Q3': 'country',
 'Q4': 'education',
 'Q5': 'role',
 'Q6': 'prog_xp',
 'Q24': 'salary'}

In [26]:
# JUST A VIEW, not a modifaction
# show what the rename function will do
copy_df.rename(columns=dict_of_column_renames).head(2)

,duration,age,gender,country,education,role,prog_xp,salary
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"

In [27]:
# column names have not changed
copy_df.columns

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5',
       'Q6', 'Q24'],
      dtype='object')

In [28]:
# we modify by assignment.
# rename() function. The parameter is: columns.
# rename() function. The argument is: dict_of_column_renames and is type dictionary
# Reminder: argument is the value of the parameter.
copy_df = copy_df.rename(columns=dict_of_column_renames)#.head(2)  If you keep this, the new df will be two rows!

In [29]:
# copy_df.rename?

In [30]:
copy_df.head(3)

,duration,age,gender,country,education,role,prog_xp,salary
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"

### 2.2 Find missing values and drop them from the dataframe

Advanced Reading: [Is inplace harmful or not?](https://stackoverflow.com/a/59242208)

In [31]:
copy_df.isnull()

       duration    age  gender  country  education   role  prog_xp  salary
0         False  False   False    False      False  False    False    True
1         False  False   False    False      False  False    False   False
2         False  False   False    False      False  False    False   False
3         False  False   False    False      False  False    False   False
4         False  False   False    False      False  False    False    True
...         ...    ...     ...      ...        ...    ...      ...     ...
20031     False  False   False    False      False   True     True    True
20032     False  False   False    False      False  False    False    True
20033     False  False   False    False      False  False    False   False
20034     False  False   False    False      False  False    False   False
20035     False  False   False    False      False  False    False   False

[20036 rows x 8 columns]

In [32]:
# show in which columns there is at least one missing value. Is there any missing value?
copy_df.isnull().any(axis=0) # axis=0 Rows

duration     False
age          False
gender       False
country      False
education     True
role          True
prog_xp       True
salary        True
dtype: bool

In [33]:
copy_df.isnull().any(axis=1) # axis=1 Columns

0         True
1        False
2        False
3        False
4         True
         ...
20031     True
20032     True
20033    False
20034    False
20035    False
Length: 20036, dtype: bool

In [34]:
# show only the rows with NaN values. NaN means not any number.
# any() is a function that returns if at least one exists.
# axis=1 means to go and check by columns. It is necessary here.
copy_df[copy_df.isnull().any(axis=1)]#[30:40]

,duration,age,gender,country,education,role,prog_xp,salary
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
4,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years,NaN
5,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years,NaN
6,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years,NaN
7,171196,25-29,Woman,China,Master’s degree,Student,< 1 years,NaN
...,...,...,...,...,...,...,...,...
20027,739,25-29,Man,India,Master’s degree,Student,3-5 years,NaN
20028,801,30-34,Man,Russia,Master’s degree,Data Analyst,< 1 years,NaN
20030,922,18-21,Man,India,Master’s degree,NaN,NaN,NaN
20031,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN,NaN
20032,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years,NaN

In [35]:
# number of rows where ALL values are missing
# all() function. Show where all satisfy the conditon.
copy_df[copy_df.isnull().all(axis=1)]

Empty DataFrame
Columns: [duration, age, gender, country, education, role, prog_xp, salary]
Index: []

In [36]:
# same result faster implementation
copy_df[copy_df.isnull().values.any(axis=1)]

,duration,age,gender,country,education,role,prog_xp,salary
0,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years,NaN
4,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years,NaN
5,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years,NaN
6,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years,NaN
7,171196,25-29,Woman,China,Master’s degree,Student,< 1 years,NaN
...,...,...,...,...,...,...,...,...
20027,739,25-29,Man,India,Master’s degree,Student,3-5 years,NaN
20028,801,30-34,Man,Russia,Master’s degree,Data Analyst,< 1 years,NaN
20030,922,18-21,Man,India,Master’s degree,NaN,NaN,NaN
20031,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN,NaN
20032,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years,NaN

In [37]:
# copy_df.dropna?

In [38]:
# there are only 10730 rows with value in column salary
copy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20036 entries, 0 to 20035
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   duration   20036 non-null  object
 1   age        20036 non-null  object
 2   gender     20036 non-null  object
 3   country    20036 non-null  object
 4   education  19569 non-null  object
 5   role       19277 non-null  object
 6   prog_xp    19120 non-null  object
 7   salary     10729 non-null  object
dtypes: object(8)
memory usage: 1.2+ MB

In [40]:
# uncomment the line below to see how df.dropna(0) works.
# copy_df.dropna?

In [114]:
# Just a view
# drop data with NaN, by rows
copy_df.dropna(axis=0, inplace=False)#, thresh=5)

,duration,age,gender,country,education,role,prog_xp,salary
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"
3,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
8,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years,"70,000-79,999"
11,742,35-39,Man,United States of America,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
...,...,...,...,...,...,...,...,...
20024,2104,35-39,Man,Malaysia,I prefer not to answer,Machine Learning Engineer,1-2 years,"2,000-2,999"
20029,5461,35-39,Man,Thailand,Bachelor’s degree,Other,10-20 years,"15,000-19,999"
20033,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years,$0-999
20034,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years,$0-999
20035,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years,$0-999

In [41]:
# Just a view
# drop data with NaN, by columns
copy_df.dropna(axis=1)#, thresh=19000)

,duration,age,gender,country
0,1838,35-39,Man,Colombia
1,289287,30-34,Man,United States of America
2,860,35-39,Man,Argentina
3,507,30-34,Man,United States of America
4,78,30-34,Man,Japan
...,...,...,...,...
20031,126,18-21,Man,Turkey
20032,566,55-59,Woman,United Kingdom of Great Britain and Northern I...
20033,238,30-34,Man,Brazil
20034,625,22-24,Man,India
20035,1031,22-24,Man,Pakistan

In [42]:
# no data have been dropped yet.
len(copy_df)

20036

In [43]:
# Works but not recommended, will most likely be deprecated.
# copy_df.dropna(inplace=True)

In [44]:
# we modify by assignment
copy_df = copy_df.dropna()

In [45]:
# the new dataframe has 10729 rows
len(copy_df)

10729

In [46]:
# the index is NOT reset. Always mind the index when dropping rows.
copy_df.head(5)

,duration,age,gender,country,education,role,prog_xp,salary
1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"
3,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
8,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years,"70,000-79,999"
11,742,35-39,Man,United States of America,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"

In [47]:
# copy_df = copy_df.reset_index(drop=True)  # reset and drop the old index.
copy_df = copy_df.reset_index()  # drop the old index or get an extra column.

In [48]:
copy_df.head()

,index,duration,age,gender,country,education,role,prog_xp,salary
0,1,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
1,2,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years,"15,000-19,999"
2,3,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
3,8,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years,"70,000-79,999"
4,11,742,35-39,Man,United States of America,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"

In [49]:
# the previous index has been retained as a new column named "index"
copy_df.tail(5)

,index,duration,age,gender,country,education,role,prog_xp,salary
10724,20024,2104,35-39,Man,Malaysia,I prefer not to answer,Machine Learning Engineer,1-2 years,"2,000-2,999"
10725,20029,5461,35-39,Man,Thailand,Bachelor’s degree,Other,10-20 years,"15,000-19,999"
10726,20033,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years,$0-999
10727,20034,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years,$0-999
10728,20035,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years,$0-999

### 2.3 Drop a column by using its name

In [125]:
copy_df = copy_df.drop("index", axis=1)  # drop the column named index.

In [126]:
copy_df.tail(2)

,duration,age,gender,country,education,role,prog_xp,salary
10727,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years,$0-999
10728,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years,$0-999

## 3. Replace values in a column, using a dictionary

[map or replace with a dict](https://stackoverflow.com/a/49259581)

In [50]:
# copy_df["country"].unique()  # this works too
copy_df.country.unique()

array(['United States of America', 'Argentina', 'Germany', 'Canada',
       'Switzerland', 'India', 'Russia', 'South Africa', 'Netherlands',
       'Pakistan', 'Other', 'Indonesia', 'Belarus', 'Ukraine',
       'Saudi Arabia', 'Taiwan', 'China', 'Italy', 'United Arab Emirates',
       'Colombia', 'Viet Nam',
       'United Kingdom of Great Britain and Northern Ireland', 'Egypt',
       'Brazil', 'Mexico', 'Poland', 'Nigeria', 'France', 'Belgium',
       'Turkey', 'Spain', 'Iran, Islamic Republic of...', 'Japan',
       'Tunisia', 'Romania', 'Republic of Korea', 'Chile', 'Ireland',
       'Sweden', 'Greece', 'Australia', 'Malaysia', 'Philippines',
       'Nepal', 'Kenya', 'South Korea', 'Morocco', 'Portugal', 'Thailand',
       'Peru', 'Bangladesh', 'Israel', 'Sri Lanka', 'Singapore', 'Ghana'],
      dtype=object)

In [51]:
# this works fine but the code is not so readable.
# copy_df.country = copy_df.country.replace(
#     {
#         "United States of America": "USA",
#         "United Kingdom of Great Britain and Northern Ireland": "UK",
#         "Iran, Islamic Republic of...": "Iran",
#         "Republic of Korea": "Korea, Republic of",
#         "South Korea": "Korea, Republic of",
#     }
# )

In [52]:
country_names_replacements = {
    "United States of America": "USA",
    "United Kingdom of Great Britain and Northern Ireland": "UK",
    "Iran, Islamic Republic of...": "Iran",
    "Republic of Korea": "Korea, Republic of",
    "South Korea": "Korea, Republic of",
    "United Arab Emirates": "UAE",
}

In [53]:
# the arguments of replace() is a dictionary
# replace() function. The parameter is: dictionary keys.
# replace() function. The argument is:  dictionary values
# Reminder: argument is the value of a parameter.
copy_df.country = copy_df.country.replace(country_names_replacements)  # replace(dict_name)

In [54]:
copy_df.country.unique()

array(['USA', 'Argentina', 'Germany', 'Canada', 'Switzerland', 'India',
       'Russia', 'South Africa', 'Netherlands', 'Pakistan', 'Other',
       'Indonesia', 'Belarus', 'Ukraine', 'Saudi Arabia', 'Taiwan',
       'China', 'Italy', 'UAE', 'Colombia', 'Viet Nam', 'UK', 'Egypt',
       'Brazil', 'Mexico', 'Poland', 'Nigeria', 'France', 'Belgium',
       'Turkey', 'Spain', 'Iran', 'Japan', 'Tunisia', 'Romania',
       'Korea, Republic of', 'Chile', 'Ireland', 'Sweden', 'Greece',
       'Australia', 'Malaysia', 'Philippines', 'Nepal', 'Kenya',
       'Morocco', 'Portugal', 'Thailand', 'Peru', 'Bangladesh', 'Israel',
       'Sri Lanka', 'Singapore', 'Ghana'], dtype=object)

In [55]:
copy_df.sample(10)

,index,duration,age,gender,country,education,role,prog_xp,salary
3483,6581,496,22-24,Man,Belgium,Master’s degree,Data Scientist,1-2 years,"1,000-1,999"
356,669,404,30-34,Woman,Japan,Doctoral degree,Other,< 1 years,"20,000-24,999"
5830,10968,607,25-29,Man,Taiwan,Master’s degree,Software Engineer,1-2 years,"25,000-29,999"
9234,17268,734,40-44,Man,Germany,Bachelor’s degree,Data Analyst,5-10 years,$0-999
9692,18096,417,18-21,Woman,Canada,Bachelor’s degree,Software Engineer,3-5 years,"50,000-59,999"
4053,7657,48664,22-24,Woman,India,Master’s degree,Software Engineer,1-2 years,$0-999
5206,9813,842,18-21,Woman,India,Doctoral degree,Research Scientist,3-5 years,$0-999
6564,12276,583,25-29,Woman,Viet Nam,Bachelor’s degree,Data Analyst,3-5 years,$0-999
3785,7160,45200,40-44,Man,Germany,Doctoral degree,Data Scientist,5-10 years,"50,000-59,999"
5657,10677,618,45-49,Man,UK,Bachelor’s degree,Other,20+ years,"30,000-39,999"

## 4. Select a part of the dataframe using conditions

In [64]:
# this is boolean indexing, True or False.
copy_df["country"] == "USA"

0         True
1        False
2         True
3        False
4         True
         ...
10724    False
10725    False
10726    False
10727    False
10728    False
Name: country, Length: 10729, dtype: bool

In [65]:
# this is a VIEW of a dataframe subset 
copy_df[copy_df["country"] == "USA"]

,duration,age,gender,country,education,role,prog_xp,salary
0,289287,30-34,Man,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,507,30-34,Man,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
4,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
11,571,50-54,Man,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
16,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...
10672,647,55-59,Man,USA,Doctoral degree,Data Scientist,3-5 years,"300,000-500,000"
10677,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
10687,5936,50-54,Man,USA,Master’s degree,Research Scientist,10-20 years,$0-999
10706,653,45-49,Man,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
10712,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"

In [66]:
len(copy_df[copy_df["country"] == "USA"])

1484

In [67]:
copy_df[copy_df.country == "USA"]

,duration,age,gender,country,education,role,prog_xp,salary
0,289287,30-34,Man,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,507,30-34,Man,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
4,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
11,571,50-54,Man,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
16,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...
10672,647,55-59,Man,USA,Doctoral degree,Data Scientist,3-5 years,"300,000-500,000"
10677,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
10687,5936,50-54,Man,USA,Master’s degree,Research Scientist,10-20 years,$0-999
10706,653,45-49,Man,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
10712,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"

In [59]:
len(copy_df[copy_df.country == "USA"])

1484

In [56]:
# if we don't reset the integer index, pandas keeps the previous index numbers
df_USA = copy_df[copy_df["country"] == "USA"]

In [57]:
df_USA

,index,duration,age,gender,country,education,role,prog_xp,salary
0,1,289287,30-34,Man,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,3,507,30-34,Man,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
4,11,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
11,24,571,50-54,Man,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
16,34,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...,...
10672,19949,647,55-59,Man,USA,Doctoral degree,Data Scientist,3-5 years,"300,000-500,000"
10677,19955,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
10687,19973,5936,50-54,Man,USA,Master’s degree,Research Scientist,10-20 years,$0-999
10706,20000,653,45-49,Man,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
10712,20006,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"

### 4.1 the OR operator is `|`

In [58]:
# parenthesis at the beginning allows for line split syntax => readability and ease of use.
(copy_df[
 (copy_df.country == "USA")
    # | (copy_df.country == "UK")
    | (copy_df.country == "Greece")
    | (copy_df.country == "Turkey")
])

# We ALWAYS need the OR operator, not the AND operator if we want a "union" of data.

,index,duration,age,gender,country,education,role,prog_xp,salary
0,1,289287,30-34,Man,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
2,3,507,30-34,Man,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
4,11,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
11,24,571,50-54,Man,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
16,34,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...,...
10677,19955,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
10687,19973,5936,50-54,Man,USA,Master’s degree,Research Scientist,10-20 years,$0-999
10706,20000,653,45-49,Man,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
10712,20006,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"
10718,20013,681,30-34,Woman,Turkey,Bachelor’s degree,Other,1-2 years,"15,000-19,999"

### 4.2 the AND operator is `&`

In [60]:
# Split rows -> Readability and ease of use
copy_df[
 (copy_df.country == "USA")
    & (copy_df.gender == "Woman")
]

,index,duration,age,gender,country,education,role,prog_xp,salary
16,34,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
62,123,778,45-49,Woman,USA,Doctoral degree,Data Scientist,10-20 years,"250,000-299,999"
96,187,356,40-44,Woman,USA,Bachelor’s degree,Data Analyst,< 1 years,"30,000-39,999"
119,243,603,40-44,Woman,USA,Master’s degree,Statistician,1-2 years,"40,000-49,999"
180,375,6378,25-29,Woman,USA,Master’s degree,Data Scientist,3-5 years,$0-999
...,...,...,...,...,...,...,...,...,...
10593,19791,976,22-24,Woman,USA,Bachelor’s degree,Data Analyst,1-2 years,"40,000-49,999"
10605,19810,765,35-39,Woman,USA,Bachelor’s degree,Other,5-10 years,$0-999
10606,19811,594,25-29,Woman,USA,Bachelor’s degree,Research Scientist,3-5 years,"4,000-4,999"
10666,19936,1139,35-39,Woman,USA,Master’s degree,Data Analyst,1-2 years,"80,000-89,999"
10677,19955,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"

In [72]:
# Union using "or"
copy_df[
    (copy_df.education == "Doctoral degree")
    | (copy_df.role == "Research Scientist")
]  

# Make sure to become familiar with unions and intersections.

,duration,age,gender,country,education,role,prog_xp,salary
3,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years,"70,000-79,999"
4,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
7,3313,22-24,Woman,India,Doctoral degree,Statistician,3-5 years,"1,000-1,999"
15,459,30-34,Man,Other,Doctoral degree,Machine Learning Engineer,10-20 years,"10,000-14,999"
20,787,25-29,Man,Indonesia,Doctoral degree,Data Analyst,5-10 years,$0-999
...,...,...,...,...,...,...,...,...
10712,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"
10716,375,40-44,Man,UK,Doctoral degree,Research Scientist,5-10 years,"125,000-149,999"
10722,611,25-29,Prefer not to say,Germany,Doctoral degree,Research Scientist,10-20 years,$0-999
10723,864,25-29,Man,Brazil,Master’s degree,Research Scientist,5-10 years,"7,500-9,999"
10726,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years,$0-999

In [62]:
# Intersection of data
copy_df[
    (copy_df.education == "Doctoral degree")
    # & (copy_df.role == "Research Scientist")
    & (copy_df.age <= "22-24")
]

# Please become familiar with unions and intersections.

,index,duration,age,gender,country,education,role,prog_xp,salary
7,20,3313,22-24,Woman,India,Doctoral degree,Statistician,3-5 years,"1,000-1,999"
80,158,623,22-24,Man,Russia,Doctoral degree,Research Scientist,3-5 years,"2,000-2,999"
587,1101,637,18-21,Prefer to self-describe,Other,Doctoral degree,Other,I have never written code,"> $500,000"
970,1807,383,22-24,Woman,Iran,Doctoral degree,Research Scientist,5-10 years,$0-999
1427,2650,412,22-24,Man,Greece,Doctoral degree,Machine Learning Engineer,3-5 years,"1,000-1,999"
1613,3013,8998,22-24,Man,India,Doctoral degree,Research Scientist,1-2 years,"1,000-1,999"
2306,4339,358,18-21,Prefer not to say,Other,Doctoral degree,Machine Learning Engineer,10-20 years,"2,000-2,999"
2442,4618,518,22-24,Prefer not to say,France,Doctoral degree,Research Scientist,3-5 years,"7,500-9,999"
2509,4734,1017,22-24,Man,India,Doctoral degree,Machine Learning Engineer,1-2 years,$0-999
2908,5457,480,22-24,Man,Italy,Doctoral degree,Research Scientist,5-10 years,"15,000-19,999"
3063,5760,561,22-24,Man,Romania,Doctoral degree,Data Scientist,3-5 years,$0-999
3068,5768,636,22-24,Man,Taiwan,Doctoral degree,Research Scientist,1-2 years,"5,000-7,499"
3172,5961,406,22-24,Woman,India,Doctoral degree,Software Engineer,I have never written code,$0-999
3217,6047,2584,22-24,Man,Tunisia,Doctoral degree,Other,3-5 years,"3,000-3,999"
3317,6238,725,22-24,Man,Brazil,Doctoral degree,Other,1-2 years,"2,000-2,999"
3827,7237,620,22-24,Man,India,Doctoral degree,Research Scientist,5-10 years,$0-999
3898,7375,1329,22-24,Woman,Morocco,Doctoral degree,Data Analyst,3-5 years,"25,000-29,999"
3977,7511,4199,22-24,Man,Iran,Doctoral degree,Data Analyst,I have never written code,$0-999
4677,8854,764,22-24,Woman,Other,Doctoral degree,Research Scientist,3-5 years,$0-999
4774,9043,438,22-24,Man,India,Doctoral degree,Statistician,1-2 years,"3,000-3,999"
5206,9813,842,18-21,Woman,India,Doctoral degree,Research Scientist,3-5 years,$0-999
5566,10499,5310,18-21,Man,Other,Doctoral degree,Research Scientist,20+ years,"> $500,000"
5656,10676,2102,22-24,Man,India,Doctoral degree,Software Engineer,5-10 years,$0-999
5806,10920,3766,18-21,Man,Other,Doctoral degree,Software Engineer,< 1 years,$0-999
6103,11462,333,18-21,Woman,USA,Doctoral degree,Research Scientist,20+ years,"> $500,000"
6350,11887,3698,22-24,Man,India,Doctoral degree,Machine Learning Engineer,< 1 years,$0-999
8085,15147,388,18-21,Woman,India,Doctoral degree,Business Analyst,< 1 years,"15,000-19,999"
8311,15557,1210,22-24,Man,India,Doctoral degree,Statistician,3-5 years,"1,000-1,999"
8656,16172,412,22-24,Man,France,Doctoral degree,Data Scientist,3-5 years,"50,000-59,999"
9713,18128,1242,22-24,Man,Bangladesh,Doctoral degree,Statistician,1-2 years,$0-999
10238,19104,162,22-24,Woman,India,Doctoral degree,Machine Learning Engineer,I have never written code,$0-999

In [63]:
# create a new dataframe containing only USA residents
# keep it in RAM using assignment
usa_df = copy_df[
    copy_df["country"] == "USA"].reset_index(drop=True)

usa_df

,index,duration,age,gender,country,education,role,prog_xp,salary
0,1,289287,30-34,Man,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
1,3,507,30-34,Man,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
2,11,742,35-39,Man,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
3,24,571,50-54,Man,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
4,34,65598,50-54,Woman,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...,...
1479,19949,647,55-59,Man,USA,Doctoral degree,Data Scientist,3-5 years,"300,000-500,000"
1480,19955,425,50-54,Woman,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
1481,19973,5936,50-54,Man,USA,Master’s degree,Research Scientist,10-20 years,$0-999
1482,20000,653,45-49,Man,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
1483,20006,487,45-49,Man,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"

## 5. Set a column as index

In [64]:
# set gender as index
# use a new name if necessary!
by_gender_usa_df =usa_df.set_index("gender")
by_gender_usa_df

,index,duration,age,country,education,role,prog_xp,salary
gender,,,,,,,,
Man,1,289287,30-34,USA,Master’s degree,Data Engineer,5-10 years,"100,000-124,999"
Man,3,507,30-34,USA,Master’s degree,Data Scientist,5-10 years,"125,000-149,999"
Man,11,742,35-39,USA,Doctoral degree,Research Scientist,1-2 years,"30,000-39,999"
Man,24,571,50-54,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
Woman,34,65598,50-54,USA,Bachelor’s degree,Other,I have never written code,"125,000-149,999"
...,...,...,...,...,...,...,...,...
Man,19949,647,55-59,USA,Doctoral degree,Data Scientist,3-5 years,"300,000-500,000"
Woman,19955,425,50-54,USA,Master’s degree,Software Engineer,20+ years,"150,000-199,999"
Man,19973,5936,50-54,USA,Master’s degree,Research Scientist,10-20 years,$0-999
Man,20000,653,45-49,USA,Bachelor’s degree,Software Engineer,20+ years,"150,000-199,999"
Man,20006,487,45-49,USA,Doctoral degree,Software Engineer,20+ years,"> $500,000"

## 6. Group_by a column or a list of columns

In [65]:
# return a series. Size() is suited for categorical values
# group by country
by_country_obs = copy_df.groupby(by="country").size().sort_values(ascending=False)

by_country_obs[:7]

country
India     2353
USA       1484
Other      815
Brazil     443
Japan      385
Russia     351
UK         350
dtype: int64

In [66]:
# same result as above, more verbose code
by_country_obs = copy_df.groupby(by="country").size()
by_country_obs = by_country_obs.sort_values(ascending=False)

by_country_obs[:7]

country
India     2353
USA       1484
Other      815
Brazil     443
Japan      385
Russia     351
UK         350
dtype: int64

In [62]:
by_country_obs.head(7)

country
India     2353
USA       1484
Other      815
Brazil     443
Japan      385
Russia     351
UK         350
dtype: int64

In [63]:
type(by_country_obs)

pandas.core.series.Series

In [67]:
# group by gender
by_gender_obs = copy_df.groupby(by="gender").size().sort_values()

by_gender_obs

gender
Nonbinary                    20
Prefer to self-describe      23
Prefer not to say           131
Woman                      1683
Man                        8872
dtype: int64

In [68]:
# group by gender and country.
# The order of columns matters.
by_gender_country_obs = copy_df.groupby(
    by=["gender", "country"]).size().sort_values(ascending=False)

by_gender_country_obs.head(10)

gender  country
Man     India      1892
        USA        1160
        Other       688
Woman   India       433
Man     Brazil      394
        Japan       361
        Russia      310
        UK          285
Woman   USA         280
Man     Germany     215
dtype: int64

In [71]:
# group by gender and country, order of columns matters.
by_country_gender_obs = copy_df.groupby(
    by=["country", "gender"]).size().sort_values(ascending=False)

by_country_gender_obs.head(10)

country  gender
India    Man       1892
USA      Man       1160
Other    Man        688
India    Woman      433
Brazil   Man        394
Japan    Man        361
Russia   Man        310
UK       Man        285
USA      Woman      280
Germany  Man        215
dtype: int64

In [72]:
# convert series data type to dataframe
by_gender_country_obs = by_gender_country_obs.to_frame()
by_gender_country_obs

                                        0
gender                  country
Man                     India        1892
                        USA          1160
                        Other         688
Woman                   India         433
Man                     Brazil        394
...                                   ...
Prefer to self-describe Spain           1
                        Portugal        1
                        Netherlands     1
                        Indonesia       1
Prefer not to say       Philippines     1

[156 rows x 1 columns]

In [73]:
type(by_gender_country_obs)

pandas.core.frame.DataFrame

#### Resources
[kaggle competition](https://www.kaggle.com/c/kaggle-survey-2020)

[My submission, at the kaggle competition](https://www.kaggle.com/pmav99/spam-identification-and-data-scientists-profile)

[github link with the notebook code for the kaggle competition](https://github.com/thanarg1979/dsml_survey_20)