# Lecture 06a: Introduction to Pandas

## What is [pandas.](https://pandas.pydata.org/)

[Pandas wikipedia entry:](https://en.wikipedia.org/wiki/Pandas_(software))

**Necessary homework reading:**
1) From the [User Guide](https://pandas.pydata.org/docs/user_guide/index.html), study: [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html). As the title says, it takes no more than 2 hours and 10 minutes!
2) More on [indexing and selecting data:](https://pandas.pydata.org/docs/user_guide/indexing.html#)   

Advanced Reading: more complex recipes in the pandas [Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook).

### Open a csv file.
### Basic info about a pandas dataframe.
### Indexing, slicing a pandas dataframe.

### Extra lecture Resources:  
[kaggle competition](https://www.kaggle.com/c/kaggle-survey-2020)

[My team submission, at the kaggle competition](https://www.kaggle.com/pmav99/spam-identification-and-data-scientists-profile)

[Github link with the notebook code for the kaggle competition](https://github.com/argythana/dsml_survey_20)

In [36]:
pwd  # Present working directory. This is where you norebook is running on your computer.

'/home/tharg/venv_projects/uoa_py_course/lectures_07_12_pandas_plots_scikit/lecture_07_pandas'

#### Module not found error if not installed.
**To Install it, open CLI, go to course folder, activate venv, type`pip install pandas` .**

In [4]:
# Import module_name as alias (useful convention)
import pandas as pd

## 1. Open a `.csv` file and read the data as a pandas dataframe.

#### If you get a very red, angry "FileNotFoundError" (file not found Error):  

Guess what is the problem:   
a) You don't have the file in the correct folder.   
b) You don't use the correct file name.   
c) YOu don't run the notebook from the correct folder.

**d) Our teacher is sooo bad, and it is his fault!**

e) All of the above.   

e) Is is the correct answer, if you are a beginner, and that's normal because it is mainly **d)**.

In [5]:
# First download the file from the eclass directory!

# Uncomment to use the code below if you put the data file in the same folder as the notebook.
# df = pd.read_csv("temp_to_coffee.csv")

In [6]:
# Use the code below if you put the data file in a directory that has the same structure as I do.
# If not, comment it out.
df = pd.read_csv("../../data/temp_to_coffee.csv")

In [7]:
# see the dataframe
df

     X    Y
0   20  396
1   22  297
2   23  397
3   18  425
4   19  425
5   24  260
6   25  250
7   20  299
8   22  520
9   18  498
10  16  434
11  16  285
12  17  496
13  20  360
14  21  417
15  19  409
16  15  493
17  15  509
18  18  406
19  20  410

In [10]:
# first 4 rows
df.head(4)

    X    Y
0  20  396
1  22  297
2  23  397
3  18  425

In [11]:
type(df)

pandas.core.frame.DataFrame

## 2. Basic dataframe methods, functions, attributes.

In [12]:
# number of rows.
len(df)

20

In [13]:
# the names of the columns in the data
df.columns

Index(['X', 'Y'], dtype='object')

In [14]:
# number of observations in each column.
df.count()

X    20
Y    20
dtype: int64

In [15]:
# number of data points (rows * columns).
df.size

40

In [16]:
# number of rows and columns.
df.shape

(20, 2)

In [17]:
df.shape[0]

20

In [18]:
# number of columns.
df.shape[1]

2

In [19]:
# index with the number of rows.
df.index

RangeIndex(start=0, stop=20, step=1)

In [20]:
type(df.index)

pandas.core.indexes.range.RangeIndex

In [21]:
df.describe()

               X           Y
count  20.000000   20.000000
mean   19.400000  399.300000
std     2.872739   84.109014
min    15.000000  250.000000
25%    17.750000  344.750000
50%    19.500000  409.500000
75%    21.250000  448.750000
max    25.000000  520.000000

In [22]:
# percentiles takes a list as an argument
df.describe(percentiles=[0.1, 0.2, 0.4, 0.95])

               X           Y
count  20.000000   20.000000
mean   19.400000  399.300000
std     2.872739   84.109014
min    15.000000  250.000000
10%    15.900000  282.500000
20%    16.800000  298.600000
40%    18.600000  402.400000
50%    19.500000  409.500000
95%    24.050000  509.550000
max    25.000000  520.000000

### New dataframe   
Same name, df. Why? Convention, Reproducabilty, Readability, Presentation purposes.

In [18]:
# Uncomment the code below and press tab. 
#pd.read_


# Comment it out again.

In [98]:
# Uncomment the code below and run. 
# pd.read_csv?

# Comment it out again.

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

In [24]:
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
df = pd.read_csv(
    "../../data/kaggle_survey_2020_responses.csv",
    # "kaggle_survey_2020_responses.csv",
    usecols=[0, 1, 2, 3, 4, 5, 6],
    low_memory=False,
)

# Use the code below if you put the data file in the same folder as the notebook.
# df = pd.read_csv(
#     "kaggle_survey_2020_responses.csv",  # Only change is the file name.
#     usecols=[0, 1, 2, 3, 4, 5, 6],
#     low_memory=False,
# )

In [25]:
# pandas dataframe
df

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years
3,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years
4,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years
...,...,...,...,...,...,...,...
20032,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN
20033,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years
20034,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years
20035,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years
20036,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years

In [26]:
# a random sample of 5 rows
df.sample(5)

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
538,673,35-39,Man,United States of America,Bachelor’s degree,Product/Project Manager,3-5 years
10117,394,25-29,Woman,India,Master’s degree,Other,1-2 years
17027,753,40-44,Man,United States of America,Bachelor’s degree,Software Engineer,10-20 years
13568,408,22-24,Man,India,Master’s degree,Student,3-5 years
302,2613,35-39,Man,Spain,Master’s degree,Data Engineer,5-10 years

In [27]:
df.columns

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5',
       'Q6'],
      dtype='object')

In [ ]:
# df.head(3)

In [28]:
# df.tail(3)

In [29]:
len(df)

20037

In [31]:
# info on non-null and data types
df.info()  # Mind the decreasing number of non-null.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20037 entries, 0 to 20036
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Time from Start to Finish (seconds)  20037 non-null  object
 1   Q1                                   20037 non-null  object
 2   Q2                                   20037 non-null  object
 3   Q3                                   20037 non-null  object
 4   Q4                                   19570 non-null  object
 5   Q5                                   19278 non-null  object
 6   Q6                                   19121 non-null  object
dtypes: object(7)
memory usage: 1.1+ MB

## 3. Columns and Index 
#### Columns: features, dimensions, variables (dependent, independent), X, y values (usually).

#### Integer Index = number or rows, observations, sample (usually).

In [32]:
# the index of the rows is a range of numbers, starting from 0.
df.index

RangeIndex(start=0, stop=20037, step=1)

In [30]:
# the data types
df.dtypes

Time from Start to Finish (seconds)    object
Q1                                     object
Q2                                     object
Q3                                     object
Q4                                     object
Q5                                     object
Q6                                     object
dtype: object

## 4. Select (Locate) based on index, or "labels", or "position".
Recommended [answer](https://stackoverflow.com/a/31593712)  
Please pay attention to the examples understand the difference between `.loc` and `.iloc`.   
**Index for rows is first, then index for columns. (Rows, Columns).**

### 4.1 Slice rows

In [29]:
# first row
df.iloc[0]

Time from Start to Finish (seconds)                                Duration (in seconds)
Q1                                                           What is your age (# years)?
Q2                                                What is your gender? - Selected Choice
Q3                                             In which country do you currently reside?
Q4                                     What is the highest level of formal education ...
Q5                                     Select the title most similar to your current ...
Q6                                     For how many years have you been writing code ...
Name: 0, dtype: object

In [108]:
df.loc[0]  # same result different method. Be careful!

Time from Start to Finish (seconds)                                Duration (in seconds)
Q1                                                           What is your age (# years)?
Q2                                                What is your gender? - Selected Choice
Q3                                             In which country do you currently reside?
Q4                                     What is the highest level of formal education ...
Q5                                     Select the title most similar to your current ...
Q6                                     For how many years have you been writing code ...
Name: 0, dtype: object

In [31]:
# second row
df.iloc[1]

Time from Start to Finish (seconds)               1838
Q1                                               35-39
Q2                                                 Man
Q3                                            Colombia
Q4                                     Doctoral degree
Q5                                             Student
Q6                                          5-10 years
Name: 1, dtype: object

In [32]:
# iloc gets rows (and/or columns) at integer locations. Works on position.
# Works on index, works with numbers.
# iloc is exclusive.
df.iloc[0:2]  # exclusive of last index

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years

In [109]:
# .loc gets rows (and/or columns) with particular labels.
# .loc is label-based
#  (inclusive)
df.loc[0:2]

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years

### 4.2 Slice columns

In [34]:
# locate by name. Single brackets. This is a Series.
df["Q2"]

0        What is your gender? - Selected Choice
1                                           Man
2                                           Man
3                                           Man
4                                           Man
                          ...
20032                                       Man
20033                                     Woman
20034                                       Man
20035                                       Man
20036                                       Man
Name: Q2, Length: 20037, dtype: object

In [35]:
type(df["Q2"])  # One bracket => Series.

pandas.core.series.Series

In [36]:
# Locate by name but use double brackets => This is a dataframe.
df[["Q2"]]

                                           Q2
0      What is your gender? - Selected Choice
1                                         Man
2                                         Man
3                                         Man
4                                         Man
...                                       ...
20032                                     Man
20033                                   Woman
20034                                     Man
20035                                     Man
20036                                     Man

[20037 rows x 1 columns]

In [37]:
type(df[["Q2"]])  # two brackets => dataframe

pandas.core.frame.DataFrame

In [110]:
# A list of [column names]
df[["Q2", "Q5", "Q3"]]

,Q2,Q5,Q3
0,What is your gender? - Selected Choice,Select the title most similar to your current ...,In which country do you currently reside?
1,Man,Student,Colombia
2,Man,Data Engineer,United States of America
3,Man,Software Engineer,Argentina
4,Man,Data Scientist,United States of America
...,...,...,...
20032,Man,NaN,Turkey
20033,Woman,Currently not employed,United Kingdom of Great Britain and Northern I...
20034,Man,Research Scientist,Brazil
20035,Man,Software Engineer,India
20036,Man,Machine Learning Engineer,Pakistan

### 4.3 Slice rows and columns

In [111]:
# Locate a range of names for the rows and a range of names for the columns.
# All rows, and only columns with names from 'Q2' to 'Q5'
df.loc[0:5, 'Q2':'Q4']

,Q2,Q3,Q4
0,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...
1,Man,Colombia,Doctoral degree
2,Man,United States of America,Master’s degree
3,Man,Argentina,Bachelor’s degree
4,Man,United States of America,Master’s degree
5,Man,Japan,Master’s degree

In [113]:
# Locate a range of names for the rows and a range of names for the columns.
df.loc[:, 'Q2':'Q4']

,Q2,Q3,Q4
0,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...
1,Man,Colombia,Doctoral degree
2,Man,United States of America,Master’s degree
3,Man,Argentina,Bachelor’s degree
4,Man,United States of America,Master’s degree
...,...,...,...
20032,Man,Turkey,Some college/university study without earning ...
20033,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree
20034,Man,Brazil,Master’s degree
20035,Man,India,Bachelor’s degree
20036,Man,Pakistan,Master’s degree

In [114]:
# Locate a range of names for the rows and a range of names for the columns.
df.loc[:5, 'Q3':'Q5']

,Q3,Q4,Q5
0,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...
1,Colombia,Doctoral degree,Student
2,United States of America,Master’s degree,Data Engineer
3,Argentina,Bachelor’s degree,Software Engineer
4,United States of America,Master’s degree,Data Scientist
5,Japan,Master’s degree,Software Engineer

In [115]:
type(df.loc[:, 'Q2':'Q3'])

pandas.core.frame.DataFrame

In [116]:
# .loc is inclusive, because it works with "names".
# Locate a range of names for the rows and a range of names for the columns.
df.loc[0:3, 'Q2':'Q4']    

# Inclusive, I repeat this many times, in case you missed it.

,Q2,Q3,Q4
0,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...
1,Man,Colombia,Doctoral degree
2,Man,United States of America,Master’s degree
3,Man,Argentina,Bachelor’s degree

In [117]:
# Locate a range of names for the rows and a range of names for the columns.
# First 11 rows, all columns.
df.loc[0:10, :]

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years
3,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years
4,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years
5,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years
6,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years
7,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years
8,171196,25-29,Woman,China,Master’s degree,Student,< 1 years
9,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years
10,150,22-24,Man,China,No formal education past high school,Student,< 1 years

In [45]:
# Locate a range of names for the rows and a list of names for the columns.
df.loc[0:6, ['Q2', 'Q5']]

,Q2,Q5
0,What is your gender? - Selected Choice,Select the title most similar to your current ...
1,Man,Student
2,Man,Data Engineer
3,Man,Software Engineer
4,Man,Data Scientist
5,Man,Software Engineer
6,Man,Data Analyst

In [118]:
# Locate a names of a row and a name of a column.
# value of a single "value" in a row.

df.loc[8, 'Q2']

'Woman'

## 5. Alternative syntax to slice rows and columns.   
You may use similar notation to lists and strings indexing, without `.loc` nor `iloc` .

In [47]:
# value of a single "value" in a row.
df.Q2[8]

'Woman'

In [119]:
# Basic indexing as we do it in lists and strings works similarly on df rows.
# EXCLUSIVE because it works with ordered indexing in numbers.

df[10:13]

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
10,150,22-24,Man,China,No formal education past high school,Student,< 1 years
11,7469,18-21,Man,India,Bachelor’s degree,Student,1-2 years
12,742,35-39,Man,United States of America,Doctoral degree,Research Scientist,1-2 years

In [120]:
# Basic indexing as we do it in lists and strings works similarly on df columns.
# EXCLUSIVE because it works with ordered indexing in number.
df.Q2[10:13]

10    Man
11    Man
12    Man
Name: Q2, dtype: object

In [51]:
# Basic indexing as we do it in lists and strings works similarly on df columns.
# Same result as above, different syntax.
# EXCLUSIVE because it works with ordered indexing in numbers.

df["Q2"][10:13]

10    Man
11    Man
12    Man
Name: Q2, dtype: object

In [121]:
df[10:13]["Q2"]

10    Man
11    Man
12    Man
Name: Q2, dtype: object

In [133]:
# Basic indexing as we do it in lists and strings works similarly on df columns and rows.
# Same result as above, different syntax.
df[["Q1", "Q2"]][10:13]

       Q1   Q2
10  22-24  Man
11  18-21  Man
12  35-39  Man

In [126]:
# Basic indexing as we do it in lists and strings works similarly on df columns and rows.
# Same result as above, different syntax.
df[10:13][["Q1", "Q2"]]

       Q1   Q2
10  22-24  Man
11  18-21  Man
12  35-39  Man

In [127]:
# Five values of column Q6, before the last five values. Sorry for this example.
df.Q6[-10:-5]

20027      3-5 years
20028      3-5 years
20029      < 1 years
20030    10-20 years
20031            NaN
Name: Q6, dtype: object

In [128]:
type(df.Q6[-10:-5])

pandas.core.series.Series

In [136]:
# Expert slcicing pandas example to burn your brains cells. 
# Really very sorry for this one.
# Slice rows and then slice rows again.
# Again, I feel the need to apologize.

df[5:10][0:3]

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
5,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years
6,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years
7,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years

In [137]:
# df[0:5][0:3] 
# Produce the same result, step by step,  in the two code cells below:
slice_on_df_rows = df[5:10]  # Rows with index number from 5 to 9
# first_slice_on_all_df_rows

In [138]:
slice_on_df_rows

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
5,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years
6,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years
7,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years
8,171196,25-29,Woman,China,Master’s degree,Student,< 1 years
9,762,35-39,Man,Germany,Doctoral degree,Data Scientist,5-10 years

In [140]:
second_slice = slice_on_df_rows[0:3]  # (Rows 1 until 3) from (rows 5 to 9)
second_slice

# REALY SORRY FOR THIS, but if you get it, it will save you hundreds of hours in the future.

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
5,78,30-34,Man,Japan,Master’s degree,Software Engineer,3-5 years
6,401,30-34,Man,India,Bachelor’s degree,Data Analyst,< 1 years
7,748,22-24,Man,Brazil,Bachelor’s degree,Student,3-5 years

### Can you spot the difference in the two alternative syntaxes?

In [141]:
df.loc[:5, 'Q2']

0    What is your gender? - Selected Choice
1                                       Man
2                                       Man
3                                       Man
4                                       Man
5                                       Man
Name: Q2, dtype: object

In [142]:
df.Q2[:5]

0    What is your gender? - Selected Choice
1                                       Man
2                                       Man
3                                       Man
4                                       Man
Name: Q2, dtype: object

In [143]:
df[2:5]["Q1"]

2    30-34
3    35-39
4    30-34
Name: Q1, dtype: object

## 6. Transpose a df.
Sometimes it is needed.    
Here I use it to explain `.loc` and `.iloc` and to demonstrate row indices that have worded labels instead of numbers.

In [144]:
# Nothing but a view.
df.transpose().head(4)  # alternative syntax: df.T

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Time from Start to Finish (seconds),Duration (in seconds),1838,289287,860,507,78,401,748,171196,762,...,132,739,801,5461,922,126,566,238,625,1031
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan

In [33]:
# df has not changed in memory. This is a view of the df.
df

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years
3,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years
4,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years
...,...,...,...,...,...,...,...
20032,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN
20033,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years
20034,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years
20035,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years
20036,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years

In [34]:
# Nothing but a view of the transpose of the df.
df.T

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Time from Start to Finish (seconds),Duration (in seconds),1838,289287,860,507,78,401,748,171196,762,...,132,739,801,5461,922,126,566,238,625,1031
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree
Q5,Select the title most similar to your current ...,Student,Data Engineer,Software Engineer,Data Scientist,Software Engineer,Data Analyst,Student,Student,Data Scientist,...,Currently not employed,Student,Data Analyst,Other,NaN,NaN,Currently not employed,Research Scientist,Software Engineer,Machine Learning Engineer
Q6,For how many years have you been writing code ...,5-10 years,5-10 years,10-20 years,5-10 years,3-5 years,< 1 years,3-5 years,< 1 years,5-10 years,...,3-5 years,3-5 years,< 1 years,10-20 years,NaN,NaN,20+ years,< 1 years,3-5 years,< 1 years

In [35]:
# df has not changed in memory.
df

,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...
1,1838,35-39,Man,Colombia,Doctoral degree,Student,5-10 years
2,289287,30-34,Man,United States of America,Master’s degree,Data Engineer,5-10 years
3,860,35-39,Man,Argentina,Bachelor’s degree,Software Engineer,10-20 years
4,507,30-34,Man,United States of America,Master’s degree,Data Scientist,5-10 years
...,...,...,...,...,...,...,...
20032,126,18-21,Man,Turkey,Some college/university study without earning ...,NaN,NaN
20033,566,55-59,Woman,United Kingdom of Great Britain and Northern I...,Master’s degree,Currently not employed,20+ years
20034,238,30-34,Man,Brazil,Master’s degree,Research Scientist,< 1 years
20035,625,22-24,Man,India,Bachelor’s degree,Software Engineer,3-5 years
20036,1031,22-24,Man,Pakistan,Master’s degree,Machine Learning Engineer,< 1 years

In [36]:
# Store a new name in memory and keep df as it is.
transposed_df = df.T  # T is an alias for the transpose() function

In [37]:
transposed_df

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Time from Start to Finish (seconds),Duration (in seconds),1838,289287,860,507,78,401,748,171196,762,...,132,739,801,5461,922,126,566,238,625,1031
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree
Q5,Select the title most similar to your current ...,Student,Data Engineer,Software Engineer,Data Scientist,Software Engineer,Data Analyst,Student,Student,Data Scientist,...,Currently not employed,Student,Data Analyst,Other,NaN,NaN,Currently not employed,Research Scientist,Software Engineer,Machine Learning Engineer
Q6,For how many years have you been writing code ...,5-10 years,5-10 years,10-20 years,5-10 years,3-5 years,< 1 years,3-5 years,< 1 years,5-10 years,...,3-5 years,3-5 years,< 1 years,10-20 years,NaN,NaN,20+ years,< 1 years,3-5 years,< 1 years

In [149]:
# this works, using numerical index
transposed_df.iloc[0:4]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Time from Start to Finish (seconds),Duration (in seconds),1838,289287,860,507,78,401,748,171196,762,...,132,739,801,5461,922,126,566,238,625,1031
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan

In [150]:
# This does work with names of rows, using the names.
transposed_df.loc["Q1": "Q2"]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man

In [68]:
# using ranges of [names of rows, names of columns]
transposed_df.loc["Q1": "Q4", 1:6]

,1,2,3,4,5,6
Q1,35-39,30-34,35-39,30-34,30-34,30-34
Q2,Man,Man,Man,Man,Man,Man
Q3,Colombia,United States of America,Argentina,United States of America,Japan,India
Q4,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree

In [151]:
transposed_df.index

Index(['Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5',
       'Q6'],
      dtype='object')

In [152]:
# the rows are the columns of the transposed df
transposed_df.columns

RangeIndex(start=0, stop=20037, step=1)

In [38]:
# first row using the name of the row.
transposed_df.loc["Q1"]

0        What is your age (# years)?
1                              35-39
2                              30-34
3                              35-39
4                              30-34
                    ...
20032                          18-21
20033                          55-59
20034                          30-34
20035                          22-24
20036                          22-24
Name: Q1, Length: 20037, dtype: object

In [154]:
# this works using a range of [names of rows]
transposed_df.loc["Q1": "Q4"]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q2,What is your gender? - Selected Choice,Man,Man,Man,Man,Man,Man,Man,Woman,Man,...,Woman,Man,Man,Man,Man,Man,Woman,Man,Man,Man
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree

In [155]:
# this works # using selected names of rows
transposed_df.loc[["Q1", "Q4", "Q6"]]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree
Q6,For how many years have you been writing code ...,5-10 years,5-10 years,10-20 years,5-10 years,3-5 years,< 1 years,3-5 years,< 1 years,5-10 years,...,3-5 years,3-5 years,< 1 years,10-20 years,NaN,NaN,20+ years,< 1 years,3-5 years,< 1 years

#### Revision example

In [157]:
# This does not work. Do you understand why?
# No We don't!
# +500 points if you find it.

transposed_df.loc["Q1", "Q4"]

KeyError: 'Q2'

In [74]:
# Solution: double brackets. There is no index named ("Q1", "Q2").
# With a single bracket it is read as a single row name "Q1", not as list of row names.
# Then, after the comma, pandas looks for a column with name "Q2" but there is no such column in the transposed df.

In [158]:
# Locates a [list of names] of rows.
transposed_df.loc[["Q1", "Q4"]]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Q1,What is your age (# years)?,35-39,30-34,35-39,30-34,30-34,30-34,22-24,25-29,35-39,...,22-24,25-29,30-34,35-39,18-21,18-21,55-59,30-34,22-24,22-24
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree

In [159]:
# locate the name for row "Q1" and then, after the comma, locate the name of the column 2.
transposed_df.loc["Q1", 2]

'30-34'

#### Summary: a list of names for columns or rows needs the proper syntax.

In [160]:
# Locates a [list of names] of rows and a [list of names] for the columns.
transposed_df.loc[["Q1", "Q5"], [2, 3, 4, 5]]

                2                  3               4                  5
Q1          30-34              35-39           30-34              30-34
Q5  Data Engineer  Software Engineer  Data Scientist  Software Engineer

In [161]:
# Slice a range of names OF  rows and a range of names OF THE ROWS AGAIN.
# COLUMNS are not sliced with this syntax. Be very careful.
# SORRY, hope you don't hate me after this example.

transposed_df[:"Q5"][3:6]

,0,1,2,3,4,5,6,7,8,9,...,20027,20028,20029,20030,20031,20032,20033,20034,20035,20036
Q3,In which country do you currently reside?,Colombia,United States of America,Argentina,United States of America,Japan,India,Brazil,China,Germany,...,Russia,India,Russia,Thailand,India,Turkey,United Kingdom of Great Britain and Northern I...,Brazil,India,Pakistan
Q4,What is the highest level of formal education ...,Doctoral degree,Master’s degree,Bachelor’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Bachelor’s degree,Master’s degree,Doctoral degree,...,Master’s degree,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree,Some college/university study without earning ...,Master’s degree,Master’s degree,Bachelor’s degree,Master’s degree
Q5,Select the title most similar to your current ...,Student,Data Engineer,Software Engineer,Data Scientist,Software Engineer,Data Analyst,Student,Student,Data Scientist,...,Currently not employed,Student,Data Analyst,Other,NaN,NaN,Currently not employed,Research Scientist,Software Engineer,Machine Learning Engineer