# Lecture 06a. Basic examples of user defined functions

In this notebook, we will learn how to define and use custom functions in Python using a practical example.

We combine user defined functions with functions from the `pandas` library to create a report on a dataset.

In the next notebook of this lecture, we will discuss more about topics in functions, in a more abstract way, using more examples.

Learning Goals:
* syntax for defining a function.
* `docstrings` (documentation strings) for functions.
* syntax for `calling` a function.
* the difference between `parameters` and `arguments`.
* the difference between `positional` and `keyword` arguments.
* the difference between `required` and `optional` arguments.
* the `return` statement.


<mark>Necessary homework reading:</mark>

The notes from the 2nd lecture on `built-in` functions, `parameters`, `arguments`, `docstrings` from the file:

`function_parameters_arguments.ipynb`.

 You may find the file on eclass (lecture_02) or in the [GitHub Course Repo](https://github.com/argythana/uoa_py_course/blob/main/lectures_01_06_fundamentals_for_data_science/lecture_06_define_functions/function_parameters_arguments.ipynb).

**First: activate venv and install the following 3 python packages**
```bash
pip install pandas matplotlib openpyxl
```

In [ ]:
import pandas as pd  # Pandas is the next lecture material

In [ ]:
# This is the Present Working Directory (pwd) of this notebook in your PC.
!pwd

/home/tharg/venv_projects/uoa_py_course/lectures_01_06_fundamentals_for_data_science/lecture_06_define_functions

In [ ]:
# # if your data file is NOT in the same directory as your notebook, you need to specify the path.
# data_dir = "./../../data/"
# data = pd.read_excel(data_dir + "grades_factors.xlsx")

In [ ]:
# if the data file is in the same directory as your notebook, you can just use the file name.

# read the data from the Excel file and load the data into the PC memory
data = pd.read_excel("grades_factors.xlsx")

In [ ]:
# Uncomment to see the data
# data

In [ ]:
# length of the data
len(data)

80

This is the dataset from your assignment in another course.
Factors that affect the grade in Calculus.

## 1. Some `pandas` methods to get info about the data.
We will learn about `pandas` in the next class. For now, just a few useful methods to work with columns.

In [ ]:
# The columns in the data. Notice the notation: Index(['...', '...'])
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [ ]:
# Using indexing to get the first item of the columns
data.columns[0]

'Calc HS'

In [ ]:
# data.columns is a pandas Index object, an iterable, works like a list and as an Index.
type(data.columns)

pandas.core.indexes.base.Index

In [ ]:
# a view of the columns as a list
data.columns.to_list()

['Calc HS',
 'ACT Math',
 'Alg Place',
 'Alg2 Grade',
 'HS Rank',
 'Gender Code',
 'Gender',
 'Calc']

In [ ]:
# Assign the column headers list to a variable name
column_headers = data.columns.to_list()

In [ ]:
type(column_headers)

list

In [ ]:
column_headers

['Calc HS',
 'ACT Math',
 'Alg Place',
 'Alg2 Grade',
 'HS Rank',
 'Gender Code',
 'Gender',
 'Calc']

In [ ]:
# Replace white spaces inside the column names with underscores using a loop
column_headers = [header.replace(" ", "_") for header in column_headers]
column_headers

['Calc_HS',
 'ACT_Math',
 'Alg_Place',
 'Alg2_Grade',
 'HS_Rank',
 'Gender_Code',
 'Gender',
 'Calc']

In [ ]:
type(column_headers[2])

str

In [ ]:
# Convert all capital letters to lowercase in the column names using a loop
column_headers = [i.lower() for i in column_headers]
column_headers

['calc_hs',
 'act_math',
 'alg_place',
 'alg2_grade',
 'hs_rank',
 'gender_code',
 'gender',
 'calc']

In [ ]:
# a pandas syntax to replace white spaces inside the column names with underscores
data.columns.str.replace(" ", "_")

Index(['Calc_HS', 'ACT_Math', 'Alg_Place', 'Alg2_Grade', 'HS_Rank',
       'Gender_Code', 'Gender', 'Calc'],
      dtype='object')

In [ ]:
# pandas syntax to convert all capital letters to lowercase in the column names
data.columns.str.lower()

Index(['calc hs', 'act math', 'alg place', 'alg2 grade', 'hs rank',
       'gender code', 'gender', 'calc'],
      dtype='object')

## 2. Define a simple function to modify the headers of the data.

In [ ]:
# function definition: name, parameters, docstring, body
def fix_headers(headers_list):
    """
    This function takes a list of headers and returns a list of headers in which the
    white spaces are replaced by underscores, and all letters converted to lowercase.
    Params:
        headers_list: list of strings.
    Returns:
        headers_list: list of strings.
    """
    # Replace white spaces inside the column names with underscores
    headers_list = headers_list.str.replace(" ", "_")  # Does not word in-place, need to reassign.

    # Convert all capital letters to lowercase in the column names
    headers_list = headers_list.str.lower()

    return headers_list

In [ ]:
# The column names
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [ ]:
# An interactive view of how fix_headers() works on the data.columns object.
fix_headers(data.columns)

Index(['calc_hs', 'act_math', 'alg_place', 'alg2_grade', 'hs_rank',
       'gender_code', 'gender', 'calc'],
      dtype='object')

In [ ]:
# The headers did not change because? What do you think?
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [ ]:
# To modify the headers, you need to assign the returned VALUE of the function to data columns
data.columns = fix_headers(data.columns)

In [ ]:
data.columns

Index(['calc_hs', 'act_math', 'alg_place', 'alg2_grade', 'hs_rank',
       'gender_code', 'gender', 'calc'],
      dtype='object')

In [ ]:
data

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,gender,calc
0,0,27,21,3.5,68,0,F,62
1,0,29,16,4.0,99,0,F,75
2,1,30,22,4.0,98,1,M,95
3,0,34,25,3.0,90,1,M,78
4,0,29,22,4.0,99,0,F,95
...,...,...,...,...,...,...,...,...
75,0,29,22,4.0,88,1,M,85
76,0,29,17,3.0,92,0,F,75
77,1,27,26,4.0,95,0,F,88
78,0,28,26,4.0,99,0,F,95
79,0,28,21,4.0,99,0,F,85

## 3. Pandas custom functions to calculate statistics of data features.

In [ ]:
# Get average of a column
data["calc_hs"].mean()

0.25

In [ ]:
# Get standard deviation of a column
data["calc_hs"].std()

0.4357446703305951

In [ ]:
# Get average descriptive stats from all columns.
data.describe()

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,calc
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,0.250000,28.250000,19.425000,3.612500,87.675000,0.537500,80.150000
std,0.435745,3.247199,4.711352,0.556748,12.181928,0.501737,11.436229
min,0.000000,16.000000,10.000000,2.000000,46.000000,0.000000,49.000000
25%,0.000000,27.000000,15.750000,3.000000,82.000000,0.000000,72.000000
50%,0.000000,28.000000,19.000000,4.000000,92.000000,1.000000,80.500000
75%,0.250000,30.000000,23.000000,4.000000,97.000000,1.000000,89.250000
max,1.000000,35.000000,30.000000,4.000000,99.000000,1.000000,99.000000

In [ ]:
# Slice the data to get descriptive stats from some columns.
data[["calc_hs", "act_math", "alg2_grade"]].describe()

         calc_hs   act_math  alg2_grade
count  80.000000  80.000000   80.000000
mean    0.250000  28.250000    3.612500
std     0.435745   3.247199    0.556748
min     0.000000  16.000000    2.000000
25%     0.000000  27.000000    3.000000
50%     0.000000  28.000000    4.000000
75%     0.250000  30.000000    4.000000
max     1.000000  35.000000    4.000000

## 4. Define a function to create a report on the data.

In [ ]:
def report_on_data(data_file, columns=None, save_to_file=False):
    """
    Take an Excel file and selected columns and return a report on the data as DataFrame.
    Params:
        data_file: An Excel filename as string.
        columns: A list of columns to include in the report. If None, all columns are included.
        save_to_file: A boolean value to save the report to a file.
    Returns:
        descr_stats_report: A pandas DataFrame with descriptive stats of the data.
    """

    # Load the data from the Excel file into memory
    my_data = pd.read_excel(data_file)

    # this block of code does the same as the next one, using the opposite logic.
    # if columns == None:
    #     my_data = my_data.describe()

    # if user provides a list of columns, slice the data to get descriptive stats from those columns.
    if columns is not None:
        my_data = my_data[columns]

    # Fix the column headers
    my_data.columns = fix_headers(my_data.columns)

    # Create report
    descr_stats_report = my_data.describe()

    # if user wants to save the report to a file, ask for the filename and save it.
    if save_to_file:
        new_filename = input("Enter the name of the file to save the report: ")
        descr_stats_report.to_excel(f"{new_filename}.xlsx", index=True)
        print("Report saved to file.")
    return descr_stats_report

In [ ]:
report_on_data.__doc__

'\n    Take an Excel file and selected columns and return a report on the data as Datafrane.\n    Params:\n        data_file: An Excel filename as string.\n        columns: A list of columns to include in the report. If None, all columns are included.\n        save_to_file: A boolean value to save the report to a file.\n    Returns:\n        descr_stats_report: A pandas DataFrame with descriptive stats of the data.\n    '

In [ ]:
help(report_on_data)

Help on function report_on_data in module __main__:

report_on_data(data_file, columns=None, save_to_file=False)
    Take an Excel file and selected columns and return a report on the data as Datafrane.
    Params:
        data_file: An Excel filename as string.
        columns: A list of columns to include in the report. If None, all columns are included.
        save_to_file: A boolean value to save the report to a file.
    Returns:
        descr_stats_report: A pandas DataFrame with descriptive stats of the data.

## 5. Call the function using only 'positional' arguments
**When we use positional arguments, we need to use the same order for arguments as in the function definition.**

In [ ]:
# Call the function with only the filename.
# This means that the function will use all columns and the report will not be saved to a file.
report_on_data("grades_factors.xlsx")

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,calc
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,0.250000,28.250000,19.425000,3.612500,87.675000,0.537500,80.150000
std,0.435745,3.247199,4.711352,0.556748,12.181928,0.501737,11.436229
min,0.000000,16.000000,10.000000,2.000000,46.000000,0.000000,49.000000
25%,0.000000,27.000000,15.750000,3.000000,82.000000,0.000000,72.000000
50%,0.000000,28.000000,19.000000,4.000000,92.000000,1.000000,80.500000
75%,0.250000,30.000000,23.000000,4.000000,97.000000,1.000000,89.250000
max,1.000000,35.000000,30.000000,4.000000,99.000000,1.000000,99.000000

In [ ]:
# call the function with the filename and a list of columns
# report only for 2 columns
# report will not be saved to a file
report_on_data(
    "grades_factors.xlsx",
    ['Calc HS', 'ACT Math'],
    False,
)

         calc_hs   act_math
count  80.000000  80.000000
mean    0.250000  28.250000
std     0.435745   3.247199
min     0.000000  16.000000
25%     0.000000  27.000000
50%     0.000000  28.000000
75%     0.250000  30.000000
max     1.000000  35.000000

In [ ]:
# When we use positional arguments, we need the same order for arguments as in the definition.
# THIS WILL NOT WORK.
report_on_data(
    ['Calc HS', 'ACT Math'],
    "grades_factors.xlsx",
    False,
)

ValueError: Invalid file path or buffer object type: <class 'list'>

## 6. Call the function using 'keyword' arguments
This will change nothing in the function, but it will **make the call to the function more readable**.

In [ ]:
# Call the function with the filename and a list of columns
# Report only for 2 columns
# Report will not be saved to a file
report_on_data(
    data_file="grades_factors.xlsx",
    columns=['Calc HS', 'ACT Math'],
    save_to_file=False,
)

         calc_hs   act_math
count  80.000000  80.000000
mean    0.250000  28.250000
std     0.435745   3.247199
min     0.000000  16.000000
25%     0.000000  27.000000
50%     0.000000  28.000000
75%     0.250000  30.000000
max     1.000000  35.000000

In [ ]:
# When we use keyword arguments, we can change the order of the arguments.
# Changing keyword arguments orders is not recommended, but works.
report_on_data(
    columns=['Calc HS', 'ACT Math'],
    data_file="grades_factors.xlsx",
    save_to_file=False,
)

         calc_hs   act_math
count  80.000000  80.000000
mean    0.250000  28.250000
std     0.435745   3.247199
min     0.000000  16.000000
25%     0.000000  27.000000
50%     0.000000  28.000000
75%     0.250000  30.000000
max     1.000000  35.000000

## 7. Call the function and assign the returned value to a variable
**The `return` statement returns the output of the function to the caller for further processing.**

Actually, functions should be defined to do just one thing and do it well.

So, it is not optimal to define a function that does two things: 1. create a report and 2. save it to a file.

It is better to define two functions: one for creating the report and another for saving it to a file. And then just call the functions one after another in the main program.

In [ ]:
# call the function and assign the returned value to a variable
example_small_report = report_on_data(
    data_file="grades_factors.xlsx",
    columns=['Calc HS', 'ACT Math'],
    save_to_file=False, # Do not save to a file.
)

In [ ]:
# show the value of the variable "example_small_report"
example_small_report

         calc_hs   act_math
count  80.000000  80.000000
mean    0.250000  28.250000
std     0.435745   3.247199
min     0.000000  16.000000
25%     0.000000  27.000000
50%     0.000000  28.000000
75%     0.250000  30.000000
max     1.000000  35.000000

In [ ]:
# the type of the returned value
type(example_small_report)

pandas.core.frame.DataFrame

## 8. Save the report to a file using the pandas method `to_excel()`

In [ ]:
# Since it is a pandas DataFrame, we can use a pandas method to
# save the report to an Excel file.
example_small_report.to_excel(
    "my_first_python_report_to_excel.xlsx",
    index=True, # comment out to see what happens
    # header=False # uncomment to see what happens
)