# Demo how functions looks like and how useful they are

** Activate venv and install packages**
```bash
pip install pandas matplotlib openpyxl
```

In [5]:
import pandas as pd  # Pandas is next lecture material

In [6]:
pwd

'/home/tharg/venv_projects/uoa_py_course/lectures_01_06_fundamentals_for_data_science/lecture_06_define_functions_modules'

In [5]:
# # if your data file is NOT in the same directory as your notebook, you need to specify the path.
# data_dir = "./../../data/"
# data = pd.read_excel(data_dir + "grades_factors.xlsx")

In [8]:
# if data file is in the same directory as your notebook, you can just use the file name.
data = pd.read_excel("grades_factors.xlsx")

In [11]:
# data

In [12]:
len(data)

80

Academic independent variables considered:
ACT scores, high school rank, high school
GPA, high school algebra grades, and the score from an
algebra pretest.
Biographical independent variables considered were:
sex, birth order, family size, and high
school size.

## 1. A simple function to modify column names of the data.

In [13]:
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [14]:
data.columns[0]  # first item of the columns

'Calc HS'

In [11]:
type(data.columns)  # data.columns is a pandas Index object, an iterable, works also like a list among others.

pandas.core.indexes.base.Index

In [15]:
data.columns.to_list()  # a view of the columns as list

['Calc HS',
 'ACT Math',
 'Alg Place',
 'Alg2 Grade',
 'HS Rank',
 'Gender Code',
 'Gender',
 'Calc']

In [16]:
column_headers = data.columns.to_list()  # assign the column headers to a variable

In [17]:
type(column_headers)

list

In [18]:
column_headers

['Calc HS',
 'ACT Math',
 'Alg Place',
 'Alg2 Grade',
 'HS Rank',
 'Gender Code',
 'Gender',
 'Calc']

In [19]:
# Replace white spaces inside the column names with underscores
column_headers = [dataset_header.replace(" ", "_") for dataset_header in column_headers]
column_headers

['Calc_HS',
 'ACT_Math',
 'Alg_Place',
 'Alg2_Grade',
 'HS_Rank',
 'Gender_Code',
 'Gender',
 'Calc']

In [20]:
type(column_headers[2])

str

In [21]:
# Convert all capital letters to lowercase in the column names
column_headers = [i.lower() for i in column_headers]
column_headers

['calc_hs',
 'act_math',
 'alg_place',
 'alg2_grade',
 'hs_rank',
 'gender_code',
 'gender',
 'calc']

In [34]:
# function definition
def fix_headers(headers_list):
    """
    This function takes a list of headers and returns a list of headers with
    white spaces replaced by underscores and all letters converted to lowercase.
    Params: headers: list of strings.
    Returns: headers: list of strings.
    """
    # Replace white spaces inside the column names with underscores
    headers_list = [header.replace(" ", "_") for header in headers_list]

    # Convert all capital letters to lowercase in the column names
    headers_list_modified = [header.lower() for header in headers_list]

    return headers_list_modified

In [40]:
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [41]:
fix_headers(data.columns)

['calc_hs',
 'act_math',
 'alg_place',
 'alg2_grade',
 'hs_rank',
 'gender_code',
 'gender',
 'calc']

In [42]:
data.columns

Index(['Calc HS', 'ACT Math', 'Alg Place', 'Alg2 Grade', 'HS Rank',
       'Gender Code', 'Gender', 'Calc'],
      dtype='object')

In [46]:
data.columns = fix_headers(data.columns)  # assign the returned VALUE of the function to data columns

In [47]:
data.columns

Index(['calc_hs', 'act_math', 'alg_place', 'alg2_grade', 'hs_rank',
       'gender_code', 'gender', 'calc'],
      dtype='object')

In [48]:
data

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,gender,calc
0,0,27,21,3.5,68,0,F,62
1,0,29,16,4.0,99,0,F,75
2,1,30,22,4.0,98,1,M,95
3,0,34,25,3.0,90,1,M,78
4,0,29,22,4.0,99,0,F,95
...,...,...,...,...,...,...,...,...
75,0,29,22,4.0,88,1,M,85
76,0,29,17,3.0,92,0,F,75
77,1,27,26,4.0,95,0,F,88
78,0,28,26,4.0,99,0,F,95
79,0,28,21,4.0,99,0,F,85

## 2. Pandas custom functions to calculate statistics of data features.

In [24]:
# Get average of a column
data["calc_hs"].mean()

0.25

In [49]:
# Get standard deviation of a column
data["calc_hs"].std()

0.4357446703305951

In [50]:
# Get average descriptive stats from all columns.
data.describe()

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,calc
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,0.250000,28.250000,19.425000,3.612500,87.675000,0.537500,80.150000
std,0.435745,3.247199,4.711352,0.556748,12.181928,0.501737,11.436229
min,0.000000,16.000000,10.000000,2.000000,46.000000,0.000000,49.000000
25%,0.000000,27.000000,15.750000,3.000000,82.000000,0.000000,72.000000
50%,0.000000,28.000000,19.000000,4.000000,92.000000,1.000000,80.500000
75%,0.250000,30.000000,23.000000,4.000000,97.000000,1.000000,89.250000
max,1.000000,35.000000,30.000000,4.000000,99.000000,1.000000,99.000000

In [51]:
# Slice the data to get average descriptive stats from some columns.
data[["calc_hs", "act_math", "alg2_grade"]].describe()

         calc_hs   act_math  alg2_grade
count  80.000000  80.000000   80.000000
mean    0.250000  28.250000    3.612500
std     0.435745   3.247199    0.556748
min     0.000000  16.000000    2.000000
25%     0.000000  27.000000    3.000000
50%     0.000000  28.000000    4.000000
75%     0.250000  30.000000    4.000000
max     1.000000  35.000000    4.000000

## 3. Custom function to create a report on the data.

In [61]:
def report_on_data(data, columns=None, save_to_file=False):
    """
    Take an Excel file and selected columns and return a report on the data as Datafrane.
    Params:
        data: An Excel file name as string.
        columns: A list of columns to include in the report. If None, all columns are included.
        save_to_file: A boolean value to save the report to a file.
    Returns:
        report: A pandas DataFrame with the average descriptive stats of the data.
    """

    my_data = pd.read_excel(data)

    # Get average descriptive stats from all columns.
    # if columns == None:
    #     my_data = my_data.describe()
    if columns is not None:
        my_data = my_data[columns]

    # Fix the column headers
    my_data.columns = fix_headers(my_data.columns)

    # Create report
    report = my_data.describe()

    if save_to_file == True:
        new_filename = input("Enter the name of the file to save the report: ")
        report.to_excel(f"{new_filename}.xlsx", index=True)
        print("Report saved to file.")
    return report

In [62]:
# help(report_on_data)

In [63]:
report_on_data("grades_factors.xlsx")

,calc_hs,act_math,alg_place,alg2_grade,hs_rank,gender_code,calc
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,0.250000,28.250000,19.425000,3.612500,87.675000,0.537500,80.150000
std,0.435745,3.247199,4.711352,0.556748,12.181928,0.501737,11.436229
min,0.000000,16.000000,10.000000,2.000000,46.000000,0.000000,49.000000
25%,0.000000,27.000000,15.750000,3.000000,82.000000,0.000000,72.000000
50%,0.000000,28.000000,19.000000,4.000000,92.000000,1.000000,80.500000
75%,0.250000,30.000000,23.000000,4.000000,97.000000,1.000000,89.250000
max,1.000000,35.000000,30.000000,4.000000,99.000000,1.000000,99.000000

In [72]:
no_key_word_report = report_on_data(
    "grades_factors.xlsx",
    # data="grades_factors.xlsx",
    ['Calc HS', 'ACT Math'],
    False,
    # save_to_file=False
)

In [73]:
no_key_word_report

         calc_hs   act_math
count  80.000000  80.000000
mean    0.250000  28.250000
std     0.435745   3.247199
min     0.000000  16.000000
25%     0.000000  27.000000
50%     0.000000  28.000000
75%     0.250000  30.000000
max     1.000000  35.000000

In [29]:
type(report)

pandas.core.frame.DataFrame